---
sidebar: sidebar
permalink: br-limitations.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database
summary: The BlueXP backup and recovery service needs to first discover data in order for you to use the service. During discovery, BlueXP backup and recovery analyzes all volumes and files in working environments within your organization. 
---

= Known limitations for BlueXP backup and recovery Preview version
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

== Standard deployment mode only
The BlueXP backup and recovery Preview version works only in standard deployment mode, not restricted or private modes. 


== Windows cluster name restriction

The Windows cluster name cannot contain an underscore (_) character.


== SnapCenter migration issues

The migration of resources from SnapCenter into BlueXP backup and recovery has the following limitations:

=== Resource group limitations 

If all the resources in a resource group are protected and one of those resources is also protected outside of the resource group, the migration from SnapCenter is blocked. 

*Workaround*: Protect the resource either in a resource group or by itself, but not in both. 

=== Resources with multiple policies using the same schedule tier not supported

You cannot have assign multiple policies that use the same schedule tier (for example, hourly, daily, weekly, etc.) to a resource. BlueXP backup and recovery will not import those resources from SnapCenter.

*Workaround*: Attach only one policy using the same schedule tier to a resource.
 
=== Hourly policies must begin at the start of the hour

If you have a SnapCenter policy that repeats every hours, but the hours are not at intervals at the start of the hour, BlueXP backup and recovery will not import the resource. For example, policies with schedules of 1:30, 2:30, 3:30, etc. are not supported, while policies with schedules of 1:00, 2:00, 3:00, etc. are supported.

*Workaround*: Use a policy that repeats in 1-hour intervals starting at the top of the hour.

=== Both daily and monthly policies attached to one resource not supported

If a SnapCenter policy repeats both in day and month intervals, BlueXP backup and recovery will not import the policy.

For example, you cannot attach a daily policy (with less than or equal to 7 days or greater than 7 days) to a resource and also attach a monthly policy to the same resource. 

*Workaround*: Use a policy that uses a daily or a monthly interval, but not both.

=== On demand backup policies not migrated

BlueXP backup and recovery does not import on demand backup policies from SnapCenter.

=== Log-only backup policies not migrated 

BlueXP backup and recovery does not import log-only backup policies from SnapCenter. If a SnapCenter policy includes log-only backups, BlueXP backup and recovery will not import the resource.


*Workaround*: Use a policy in SnapCenter that uses more than just log-only backups. 


=== OLD stuff


=== Host mapping (was #2 in the document)
SnapCenter does not have map storage clusters or SVMs for the resources to hosts, but BlueXP backup and recovery does. The on-premises ONTAP cluster or SVM will not be mapped to a host in BlueXP backup and recovery Preview version. Additionally, BlueXP does not support SVMs. 


*Workaround*: Before importing resources from SnapCenter, create a working environment in BlueXP backup and recovery for all the on-premises ONTAP storage systems that are registered in on-premises SnapCenter. Then, import the resources for that cluster from SnapCenter into BlueXP backup and recovery.



=== Schedules not in 15-minute intervals (was #9 in document)

If you have a SnapCenter policy schedule that starts at a certain time and repeats every so many minutes but the minutes are not in 15-minute intervals, BlueXP backup and recovery will not import the schedule.


*Workaround*: Use SnapCenter to adjust the policy so that it repeats in 15-minute intervals.


=== Log backup retention (was #18 in the document)

With SnapCenter, you can have multiple retention values across multiple policies attached to a resource. However, BlueXP backup and recovery Preview version supports only a single retention value for all policies attached to a resource.




