---
sidebar: sidebar
permalink: br-start-faq.html
keywords: backup and recovery faq, bluexp backup and recovery frequently asked questions
summary: This FAQ can help if you're just looking for a quick answer to a question.
---

= Frequently asked questions for BlueXP backup and recovery
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
This FAQ can help if you're just looking for a quick answer to a question.

== Deployment

*Do you need a license to use BlueXP backup and recoveryPreview version?*

You can use the following license types:

* Sign up for a 30-day free trial.
//* Purchase a pay-as-you-go (PAYGO) subscription with Amazon Web Services (AWS) Marketplace, and Microsoft Azure Marketplace (coming soon). 
//* Bring your own license (BYOL), which is a NetApp License File (NLF) that you obtain from your NetApp Sales Rep. You can use the license serial number to get the BYOL activated in BlueXP digital wallet.


*How do you enable BlueXP backup and recovery?* 
BlueXP backup and recovery does not require any enablement. The backup and recovery option is automatically enabled on the BlueXP left navigation. 

To get going, you need to sign up or reach out to your NetApp Sales rep to try out this service. Then, when you use the BlueXP Connector, it will include the appropriate capabilities for the service.

To get started with BlueXP backup and recovery, you click "Start discovering workloads" from its initial landing page. 

*Is BlueXP backup and recovery available in standard, restricted, and private modes?*
At this time, BlueXP backup and recovery Preview version is available only in standard mode. Stay tuned for more. 

For an explanation about these modes across all BlueXP services, refer to https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html[BlueXP deployment modes^].

== Access

*What's the BlueXP backup and recovery URL?*
For the URL, in a browser, enter: https://console.bluexp.netapp.com/[https://console.bluexp.netapp.com/backup-and-recovery^] to access the BlueXP console. 




*How are access permissions handled?*
Only Organization admins have the ability to initiate the service and discover workloads (because this involves committing to usage of a resource). Subsequent interactions can be done by any role.

*What device resolution is best?*
The recommended device resolution for BlueXP backup and recovery is 1920x1080 or better. 

*Which browser should I use?*
Any modern browser will work. 



== Interaction with other services

*Is BlueXP backup and recovery aware of protection settings made in NetApp ONTAP?*
Yes, BlueXP backup and recovery discovers Snapshot schedules set in ONTAP. 

*If you set a policy using BlueXP backup and recovery, do you have to make future changes only in this service?* 
We recommend that you make policy changes from the BlueXP backup and recovery service.

//*How does BlueXP backup and recovery interact with SnapCenter?*

//BlueXP backup and recovery uses the following products and services:

//* SnapCenter to discover and set snapshot and backup policies for application workloads

//* SnapCenter to perform file- and workload-consistent recovery 



== Workloads

*What makes up a workload?*
A workload is an application for the Preview 2025 version. A workload includes all volumes that are used by a single application instance. For example, a Microsoft SQL Server DB instance deployed on mssql3.host.com can have vol1 and vol2 for its data and logs, respectively. Those volumes together constitute the workload for that specific instance of the DB instance.

//A workload is an application, a VM, or a file share. A workload includes all volumes that are used by a single application instance. For example, an Oracle DB instance deployed on ora3.host.com can have vol1 and vol2 for its data and logs, respectively. Those volumes together constitute the workload for that specific instance of the Oracle DB instance.


*What workloads does BlueXP backup and recovery support?*

For the Preview 2025 version, BlueXP backup and recovery can identify the following workloads: Microsoft SQL Server applications.

//BlueXP backup and recovery can identify the following workloads: Oracle, MySQL, file shares, VMs, and VM datastores.

//In addition, if you are using SnapCenter or SnapCenter for VMware, all workloads supported by those products are also identified in BlueXP backup and recovery and BlueXP backup and recovery can protect and recover these in a workload-consistent manner.

*How do you associate data with a workload?*

BlueXP backup and recovery associates data with a workload in the following ways:

* BlueXP backup and recovery discovers the volumes and the file extensions and associates them to the appropriate workload.
* In addition, if you have SnapCenter and have configured workloads in BlueXP backup and recovery, then BlueXP backup and recovery discovers the workloads managed by SnapCenter and their associated volumes.

*What is a "protected" workload?*
In BlueXP backup and recovery, a workload shows a “protected” status when it has a primary detection policy enabled. 

//Coming soon, this could also be that CISWS is monitoring user activity. 

*What is an “at risk” workload?*
If a workload does not have a primary detection policy enabled, it is “at risk” even if it has a backup and snapshot policy enabled. 


*New volume added, but doesn't appear yet*
If you added a new volume to your environment, initiate discovery again and apply protection policies to protect that new volume. 

*The Dashboard doesn't show all my workloads. What might be wrong?*
Currently, only NFS and CIFS volumes are supported. iSCSI volumes  and other non-supported configurations are filtered out and do not appear on the Dashboard. 

== Protection policies


*Is BlueXP backup and recovery aware of protection settings made in NetApp ONTAP?*

Yes, BlueXP backup and recovery discovers snapshot schedules set in ONTAP and whether ARP and FPolicy are enabled across all volumes in a discovered workload. The info you see initially in the Dashboard is aggregated from other NetApp solutions and products. 


*Is BlueXP backup and recovery aware of policies already made in SnapCenter?*

Yes, if you have workloads managed in SnapCenter, the policies managed by those products are brought into BlueXP backup and recovery.

*Can you modify policies carried over from SnapCenter?*

No, you cannot modify policies managed by SnapCenter within BlueXP backup and recovery. You manage any changes to those policies in SnapCenter.

*If policies exist from ONTAP (already enabled in System Manager such as ARP, FPolicy, and snapshots) are those changed in BlueXP backup and recovery?*

No. BlueXP backup and recovery does not modify any existing detection policies (ARP, FPolicy settings) from ONTAP.

*What happens if you add new policies in SnapCenter after signing up for BlueXP backup and recovery?*

BlueXP backup and recovery recognizes any new polices created in SnapCenter.

*Can you change policies from ONTAP?*

Yes, you can change policies from ONTAP in BlueXP backup and recovery. You can also create new policies in BlueXP backup and recovery and apply them to workloads. This action replaces existing ONTAP policies with the policies created in BlueXP backup and recovery. 

