---
sidebar: sidebar
permalink: br-use-kubernetes-protect-overview.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery
summary: You can protect Kubernetes applications and application data from on-premises ONTAP systems to Amazon Web Services, Microsoft Azure, Google Cloud Platform, and StorageGRID, ensuring that your data is protected. 
---

= Manage Kubernetes workloads overview 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Managing Kubernetes workloads in BlueXP backup and recovery enables you to discover, manage, and protect your Kubernetes clusters and applications all in one place. You can manage resources and applications hosted on your Kubernetes clusters. You can also create and associate protection policies with your Kubernetes workloads, all using a single interface.

BlueXP backup and recovery provides the following benefits for managing Kubernetes workloads:

* A single control plane for protecting applications running across multiple Kubernetes clusters. These applications can include containers or virtual machines running on your Kubernetes clusters.
* Native integration with NetApp SnapMirror, enabling storage offloading capabilities for all backup and recovery workflows. 
* Incremental forever backups for Kubernetes applications, translating to lower Recovery Point Objectives (RPOs) and Recovery Time Objectives (RTOs).

NOTE: THIS DOCUMENTATION IS PROVIDED AS A TECHNOLOGY PREVIEW. During the preview, Kubernetes functionality is not recommended for production workloads. With this preview offering, NetApp reserves the right to modify offering details, contents, and timeline before General Availability.

You can accomplish the following tasks related to managing Kubernetes workloads:

* link:br-start-discover.html#discover-kubernetes-workloads[Discover Kubernetes workloads].
* link:br-use-manage-kubernetes-clusters.html[Manage Kubernetes clusters].
* link:br-use-protect-kubernetes-applications.html[Add and protect Kubernetes applications].
* link:br-use-manage-kubernetes-applications.html[Manage Kubernetes applications].
* link:br-use-restore-kubernetes-applications.html[Restore Kubernetes applications].

 
