---
sidebar: sidebar
permalink: br-use-restore-overview.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery
summary: Backups of your data are available for restore from the locations where you created backups, which includes snapshot, replications, and backups in object storage. Review the restore-from locations, restore points, and resource types to restore.
---

= Restore workloads overview 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Backups of your data are available for restore from the locations where you created backups: snapshots, replications, or backups in object storage. You can restore a workload to the original working environment, to a different working environment that's using the same cloud account, or to an on-premises ONTAP system. Review the restore-from locations, restore points, and resource types to restore.

//different types of restore operations, volume restore or file/folder restore, Browse and restore vs Search and restore)

.Restore from these locations

You can restore workloads from different starting locations: 

* Restore from a snapshot copy
* Restore from a replicated resource
* Restore from an object store backup

.Restore to these points   

You can restore data to the latest snapshot or to these points: 

* Restore from latest snapshot 
* Restore to a point in time
* Restore to the latest state 

== Restore methods

You can restore workloads using one of the following methods. Typically, choose one of the following methods based on your restore needs:

* *From the Restore page*: Use this when you need to restore a resource, but you don't remember the exact name or the location in which it resides, or the date when it was last in good shape. You search for the resource using filters. 
* *From the Inventory page*: Use this when you need to restore a specific resource from the last week or month -- and you know the name and location of the resource, and the date when it was last in good shape. You browse through a list of resources to find the one you want to restore.

//Inventory is browse and restore. Restore page is Search and restore. 

== What's next

For details on how to restore workloads, see link:br-use-restore-database.html[Restore workloads].     

