---
sidebar: sidebar
permalink: br-use-restore-overview.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery
summary: Backups of your data are available for restore from the locations where you created backups, which includes snapshot, replications, and backups in object storage. Review the restore-from locations, restore points, and resource types to restore.
---

= Restore workloads overview 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Backups of your data are available for restore from the locations where you created backups: snapshots, replications, or backups in object storage. You can restore a workload to the original working environment, to a different working environment that's using the same cloud account, or to an on-premises ONTAP system. Review the restore-from locations, restore points, and resource types to restore.

//different types of restore operations, volume restore or file/folder restore, Browse and restore vs Search and restore)

.Restore from these locations

You can restore workloads from different starting locations: 

* Restore from a snapshot copy
* Restore from a replicated volume
* Restore from an object store backup

.Restore to these points   

You can restore data to the latest snapshot or to these points: 

* Restore from latest snapshot 
* Restore to a point in time
* Restore to the latest state 

.Resource types to restore    

You can restore workloads from a backup file, or if you only need to restore a few files, you can restore a folder or individual files.



== Restore methods

You can restore workloads using one of the following methods. Typically, choose one of the following methods based on your restore needs:

* From the Restore page 
* From the Inventory page: 

** _Browse & restore_ is typically better when you need to restore a specific volume, folder, or file from the last week or month -- and you know the name and location of the file, and the date when it was last in good shape. 

** _Search & Restore_ is typically better when you need to restore a volume, folder, or file, but you don't remember the exact name, or the volume in which it resides, or the date when it was last in good shape.

This table compares the two methods from the Inventory page.

[cols=2*,options="header",cols="50,50"]
|===

| Browse & Restore
| Search & Restore

| Browse through a folder-style structure to find the resource, folder, or file within a single backup file. | Search for a resource, folder, or file across *all backup files* by partial or full name, partial or full folder/file name, size range, and additional search filters.
| Does not handle file recovery if the file has been deleted or renamed, and you don't know the original file name | Handles newly created/deleted/renamed directories and newly created/deleted/renamed files
| No additional cloud provider resources required | When you restore from the cloud, additional bucket and public cloud provider resources required per account.
| No additional cloud provider costs required | When you restore from the cloud, additional costs are required when scanning your backups and volumes for search results.
| Quick restore is supported. | Quick restore is not supported. 


|===

This table provides a list of valid restore operations based on the location where your backup files reside. 

[cols=7*,options="header",cols="14h,14,14,14,14,14,14",width="100%"]
|===
| Backup Type
3+^| Browse & Restore
3+^| Search & Restore

|  | *Restore resource* | *Restore files* | *Restore folder* | *Restore resource* | *Restore files* | *Restore folder* 
| Snapshot copy | Yes | No | No | Yes | Yes | Yes 
| Replicated on secondary storage | Yes | No | No | Yes | Yes | Yes 
| Backup file on object storage | Yes | Yes | Yes | Yes | Yes | Yes 

|===





