---
sidebar: sidebar
permalink: br-use-vmware-protect-overview.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database
summary: Protect your VMware workloads with NetApp BlueXP backup and recovery. 
---

= Protect VMware workloads with BlueXP backup and recovery overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Protect your VMware VMs, datastores, and applications on VMs with BlueXP backup and recovery. BlueXP backup and recovery provides fast, space-efficient, crash-consistent, and VM-consistent backup and restore operations. You can back up VMware workloads to Amazon Web Services S3, Microsoft Azure Blob, or StorageGRID and restore VMware workloads back to the the same or alternate on-premises VMware host. 

//BlueXP backup and recovery provides fast, space-efficient, crash-consistent, and VM-consistent backup and restore operations for VMs, datastores, and VMDKs. 


Use BlueXP backup and recovery to implement a 3-2-1 strategy, where you have 3 copies of your source data on 2 different storage systems along with 1 copy in the cloud. The benefits of the 3-2-1 approach include:

* Multiple data copies provide multi-layer protection against both internal (insider) and external cybersecurity threats.
* Multiple media types ensure failover viability in the case of physical or logical failure of one media type.
* The onsite copy facilitates quick restores, with the offsite copies available just in case the onsite copy is compromised.

====
*NOTE*   To switch to and from BlueXP backup and recovery UI versions, refer to link:br-start-switch-ui.html[Switch to the previous BlueXP backup and recovery UI].
====



You can use BlueXP backup and recovery to perform the following tasks related to VMware workloads:

* link:br-use-vmware-discovery.html[Discover VMware workloads]
* link:br-use-vmware-backup.html[Back up VMware workloads]
* link:br-use-vmware-restore.html[Restore VMware workloads]
//* link:br-use-vmware-clone.html[Clone VMware workloads]



