---
sidebar: sidebar
permalink: br-use-restore-kubernetes-applications.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter
summary: BlueXP backup and recovery enables you to manage your workload host information, database information, and instances information. You can view, edit, and delete protection settings for your inventory.  
---

= Restore Kubernetes applications 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP backup and recovery enables you to restore applications that you have protected with a protection policy. To restore an application, the application needs to have a protection status of "Protected" and it should have an associated protection policy. To restore an application, you need a restore point, which consists of the local snapshot, the secondary snapshot, and the backup to the object store. You can restore an application using the backup or either of the snapshots.

.Required BlueXP role

Organization admin or Folder or project admin. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html[Learn about BlueXP access roles for all services^].

.Steps

. In BlueXP backup and recovery, select *Inventory*.
. Choose a Kubernetes workload, and select *View* in the Hosts column for the workload.
. In the list of applications, choose an application you want to restore and select the associated Actions menu.
. Select *View and restore*.
+
The list of restore points appears. 
. Open the Actions menu for the restore point you want to use, and select *Restore*.
. Choose the source to restore from (local, secondary, or object store).
. Choose the destination cluster from the *Cluster* list.
. Choose the restore destination namespace (original or new).
+
Note that restores to a different cluster and the original namespace are not supported.
. Select *Next*.
. Choose whether you want to restore all resources associated with the application or use a filter to select specific resources to restore:
+
// begin tabbed block
[role="tabbed-block"]
====
.Restore all resources
--
.. Select *Restore all resources*.
.. Select *Next*.
--
.Restore specific resources
--
.. Select *Selective resources*.
.. Choose the behavior of the resource filter. If you choose *Include*, the resources you select are restored. If you choose *Exclude*, the resources you select are not restored.
.. Select *Add rules* to add rules that define filters for selecting resources. You need at least one rule to filter resources.
+
Each rule can filter on criteria such as the resource namespace, labels, group, version, and kind.
.. Select *Save* to save each rule.
.. When you have added all the rules you need, select *Search* to see the resources available in the backup archive that match your filter criteria.
.. When satisfied with the results, select *Next*.
--
====
//end-tabbed-block
. Choose to restore either to the default storage class or to a different storage class. 
. Optionally, if you chose to restore to a different storage class, select a destination storage class to match each source storage class. The destination storage class must be available on the destination cluster.
. Select *Restore*.


