---
sidebar: sidebar
permalink: br-use-kubernetes-protect-overview.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery
summary: You can protect Kubernetes applications and application data from on-premises ONTAP systems to Amazon Web Services, Microsoft Azure, Google Cloud Platform, and StorageGRID, ensuring that your data is protected. 
---

= Manage Kubernetes workloads overview 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Managing Kubernetes workloads in BlueXP backup and recovery enables you to manage and protect your Kubernetes clusters and applications all in one place. You can manage resources and applications hosted by your Kubernetes clusters. You can also manage the protection settings of your Kubernetes workloads.

NOTE: THIS DOCUMENTATION IS PROVIDED AS A TECHNOLOGY PREVIEW. During the preview, Kubernetes functionality is not recommended for production workloads. With this preview offering, NetApp reserves the right to modify offering details, contents, and timeline before General Availability.

You can accomplish the following tasks related to managing Kubernetes workloads:

// Link to discover workloads
//* link:br-start-discover.html#discover-kubernetes-workloads[Discover Kubernetes workloads].
//* link:br-use-manage-kubernetes-clusters.html[Manage Kubernetes clusters].
//* link:br-use-protect-kubernetes-applications.html[Add and protect Kubernetes applications].
//* link:br-use-manage-kubernetes-applications.html[Manage Kubernetes applications].
//* link:br-use-restore-kubernetes-applications.html[Restore Kubernetes applications].

 
