---
sidebar: sidebar
permalink: br-use-manage-kubernetes-applications.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter
summary: BlueXP backup and recovery enables you to manage your workload host information, database information, and instances information. You can view, edit, and delete protection settings for your inventory.  
---

= Manage Kubernetes applications 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP backup and recovery enables you to manage your Kubernetes applications and associated resources. You can view, edit, and delete protection settings of your Kubernetes applications.

== Add and protect a new Kubernetes application
The first step in protecting Kubernetes applications is to create an application within BlueXP backup and recovery. When you create an application, you make BlueXP aware of the running application on the Kubernetes cluster.

.Steps

. In BlueXP backup and recovery, select *Inventory* > *Applications*.
. Select *Create application*.
. Enter a name for the application.
. Choose any of the following fields to search for the resources you want to protect:
+
* Associated cluster
* Associated namespaces 
* Resource types
* Label selectors
. Optionally, select *Cluster Scoped Resources* to choose any resources that are scoped at the cluster level and not included in the application. If you include them, they are added to the application when you create it.
. Select *Search* to find the resources based on your search criteria.
. BlueXP displays a list of resources that match your search criteria.
. If the list contains the resources you want to protect, select *Next*.
. In the *Policy* area, choose an existing protection policy to protect the application or create a new policy.
. In the *Prescripts and postscripts* area, enable and configure any prescript or postscript execution hooks that you want to run before or after backup operations. You can configure the type of execution hook, the template it uses, arguments, and label selectors.
. Select *Create*.

.Result 
The application is created and appears in the list of applications in the *Applications* tab of the Kubernetes inventory. BlueXP enables protection for the application based on your settings, and you can monitor the progress in the *Monitoring* area of backup and recovery.

== Protect an existing Kubernetes application
Enable a protection policy on a Kubernetes application that you have already added. 

.Steps
. In BlueXP backup and recovery, select *Inventory* > *Applications*.
. In the list of applications, choose an application you want to protect and select the associated Actions menu.
. Select *Protect*.
. In the *Policy* area, choose an existing protection policy to protect the application or create a new policy.
. In the *Prescripts and postscripts* area, enable and configure any prescript or postscript execution hooks that you want to run before or after backup operations. You can configure the type of execution hook, the template it uses, arguments, and label selectors.
. Select *Done*.

.Result
BlueXP enables protection for the application based on your settings, and you can monitor the progress in the *Monitoring* area of backup and recovery.

== Back up a Kubernetes application now
Manually create a backup of a Kubernetes application to establish a baseline for future backups and snapshots, or to ensure the most recent data is protected.

.Steps
. In BlueXP backup and recovery, select *Inventory* > *Applications*.
. In the list of applications, choose an application you want to back up and select the associated Actions menu.
. Select *Backup now*.
. Ensure the correct application name is selected.
. Select a protection policy from the list of policies.
. Select *Back up*.

== Edit a Kubernetes application
You can modify the settings of an existing Kubernetes application if the resources associated with the application have changed.

.Steps
. In BlueXP backup and recovery, select *Inventory* > *Applications*.
. In the list of applications, choose an application you want to edit and select the associated Actions menu.
. Select *Edit*.
. Make any required changes to the application definition, such as the name or included resources.
. When finished, select *Next*.
. Make any required changes to the protection settings.
. When finished, select *Done*.

== Delete a Kubernetes application
You can delete an application if you no longer need it. When you delete an application, BlueXP backup and recovery stops protecting the application and, if you choose to do so, deletes all associated backups and snapshots.

.Steps
. In BlueXP backup and recovery, select *Inventory* > *Applications*.
. In the list of applications, choose an application you want to delete and select the associated Actions menu.
. Select *Delete*.
. Optionally, enable *Delete snapshots and backups* to remove all snapshots and backups of the application.
+
CAUTION: If you do this, you will no longer be able to restore the application using these snapshots and backups.
. Confirm the action and select *Delete*.