---
sidebar: sidebar
permalink: concept-start-prereq.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery
summary: Get started with BlueXP backup and recovery by verifying the readiness of your operational environment, BlueXP Connector, and BlueXP account. To use BlueXP backup and recovery, you'll need these prerequisites.
---

= BlueXP backup and recovery Preview 2025 prerequisites
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Get started with BlueXP backup and recovery by verifying the readiness of your operational environment, BlueXP Connector, and BlueXP account. To use BlueXP backup and recovery, you'll need these prerequisites.

== SnapCenter host version

SnapCenter host version 5.0 or greater is required if you are going to import your existing data from SnapCenter into BlueXP backup and recovery.

== Host requirements 

To use BlueXP backup and recovery, you need the following host system, space, and sizing prerequisites.

[cols=2*,options="header",cols="33,66a",width="90%"]
|===

| Item
| Requirements

| Operating systems
| Microsoft Windows
For the latest information about supported versions, see the https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome[NetApp Interoperability Matrix Tool^].

| Minimum RAM for the SnapCenter plug-in on the host
| 1 GB

| Minimum install and log space for the SnapCenter plug-in on the host
| 5 GB

Allocate sufficient disk space and monitor the storage consumption by the logs folder. The log space required varies depending on the number of backups performed and the frequency of data protection operations. If there is not sufficient space, the logs will not be created for the operations. 

|Required software packages if using SnapCenter 6.0 or greater
| * ASP.NET Core Runtime 8.0.12 Hosting Bundle (and all subsequent 8.0.x patches)

* Java 11 Oracle Java and OpenJDK

//* Java 11 Oracle Java and OpenJDK are required only for SAP HANA, IBM Db2, PostgreSQL, MySQL, NetApp supported plug-ins, and other custom applications that can be installed on Windows hosts.

* PowerShell Core 7.4.2

For the latest information about supported versions, see the https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome[NetApp Interoperability Matrix Tool^].

|Required software packages if using SnapCenter 5.0
| * Microsoft .NET Framework 4.7.2 or later

* Windows Management Framework (WMF) 4.0 or later

* PowerShell 4.0 or later


For the latest information about supported versions, see the https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome[NetApp Interoperability Matrix Tool^].



|===

== In BlueXP 


* A BlueXP user account with Organization Admin privileges for discovering resources.

* A BlueXP organization with at least one active BlueXP Connector connecting to on-premises ONTAP clusters or connecting to Cloud Volumes ONTAP in AWS or in Azure. 

* At least one BlueXP working environment with a NetApp on-premises ONTAP cluster or Cloud Volume ONTAP in AWS or Azure (using NAS or CIFS protocols).

* A BlueXP Connector

** ONTAP or Cloud Volume ONTAP clusters with ONTAP OS version 9.8 or greater are supported. 

** If your on-premises ONTAP clusters or Cloud Volume ONTAP in AWS or in Azure cloud are not already onboarded in BlueXP, then you'll need a BlueXP Connector. 
+
Refer to https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html[Learn how to configure a BlueXP Connector] and https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html[standard BlueXP requirements^].


//All source and working environments must be in the same BlueXP organization. 

=== Set up BlueXP
The next step is to set up BlueXP and the BlueXP backup and recovery service. 

Review https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html[standard BlueXP requirements^].


=== Create a BlueXP Connector

You should reach out to your NetApp Sales Rep to try out or use this service. Then, when you use the BlueXP Connector, it will include the appropriate capabilities for the service. 

To create a Connector in BlueXP before using the service, refer to the BlueXP documentation that describes https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html[how to create a BlueXP Connector^]. 




== In ONTAP 9.8 and later

An ONTAP One license must be enabled on the on-premises ONTAP instance.


//* To apply advanced protection configurations (such as enabling DataLock and others), BlueXP backup and recovery needs admin permissions on the ONTAP cluster. The ONTAP cluster should have been onboarded using ONTAP cluster admin user credentials only. 

//* If the ONTAP cluster is already onboarded in BlueXP using non-admin user credentials, then the non-admin user permissions must be updated with necessary permissions by logging into the ONTAP cluster, described on this page. 


== For backups to object storage

For backup targets to object storage, you need an account in NetApp StorageGRID, AWS S3, Microsoft Azure Blob, or Google Cloud Storage  and the access permissions set. 

Refer to the https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html[AWS, Azure, or S3 permissions list^] for details. 




//* An on-premises SnapCenter server must be accessible from the BlueXP Connector.

//== Update non-admin user permissions in an ONTAP working environment

//If you need to update non-admin user permissions for a particular working environment, complete these steps. 


//.  Log in to BlueXP and look for the working environment that needs its ONTAP user permissions updated. 

//. Double-click on the working environment to see details. 
//. Click *View additional information* that shows the user name. 
//. Log in to the ONTAP cluster CLI using the admin user. 
//. Display the existing roles for that user. Enter: 
//+
//----
//security login show -user-or-group-name <username>
//----

//. Change the role for the user. Enter: 
//+
//----
//security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
//----

//. Go to the BlueXP backup and recovery UI to use it. 