---
sidebar: sidebar
permalink: prev-vmware-protect-overview.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database
summary: Protect your VMware workloads with NetApp BlueXP backup and recovery. 
---

= Protect VMware datastores in BlueXP backup and recovery overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Protect your VMware workloads with BlueXP backup and recovery. BlueXP backup and recovery provides fast, space-efficient, crash-consistent, and VM-consistent backup and restore operations for VMs, datastores, and VMDKs. 

You can back up datastores to Amazon Web Services S3, Microsoft Azure Blob, Google Cloud Platform, and StorageGRID and restore virtual machines back to the on-premises SnapCenter Plug-in for VMware vSphere host. 


====
*NOTE*   To switch to and from BlueXP backup and recovery workloads, refer to link:br-start-switch-ui.html[Switch to different BlueXP backup and recovery workloads].
====


For instructions on using the previous BlueXP backup and recovery UI for VMware, see the following topics:

* link:prev-vmware-policy-create.html[Create a policy for VMware workloads]
* link:prev-vmware-backup-aws.html[Back up VMware datastores to Amazon Web Services]
* link:prev-vmware-backup-azure.html[Back up VMware datastores to Microsoft Azure]
* link:prev-vmware-backup-gcp.html[Back up VMware datastores to Google Cloud Platform]
* link:prev-vmware-backup-storagegrid.html[Back up VMware datastores to StorageGRID]
* link:prev-vmware-restore.html[Restore VMware workloads]    
* link:prev-vmware-manage-html[Manage protection for VMware workloads]
