settings:
  name: Cloud Backup
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  filter:
    label: Cloud provider
    default: All cloud providers
    options:
      - name: Amazon Web Services
        alias: AWS
        id: aws
      - name: Google Cloud
        alias: Google Cloud
        id: gcp
      - name: Microsoft Azure
        alias: Azure
        id: azure
sidebar:
  entries:
    - title: Cloud Backup docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about Cloud Backup
          url: /concept-backup-to-cloud.html
        - title: Set up licensing
          url: /task-licensing-cloud-backup.html
        - title: Monitor the status of backup and restore jobs
          url: /task-monitor-backup-jobs.html
    - title: Back up and restore ONTAP data
      entries:
        - title: Protect your ONTAP volume data
          url: /concept-ontap-backup-to-cloud.html
        - title: Back up Cloud Volumes ONTAP to Amazon S3
          flavor: aws
          url: /task-backup-to-s3.html
        - title: Back up Cloud Volumes ONTAP to Azure Blob
          flavor: azure
          url: /task-backup-to-azure.html
        - title: Back up Cloud Volumes ONTAP to Google Cloud
          flavor: gcp
          url: /task-backup-to-gcp.html
        - title: Back up on-premises ONTAP to Amazon S3
          flavor: aws
          url: /task-backup-onprem-to-aws.html
        - title: Back up on-premises ONTAP to Azure Blob
          flavor: azure
          url: /task-backup-onprem-to-azure.html
        - title: Back up on-premises ONTAP to Google Cloud
          flavor: gcp
          url: /task-backup-onprem-to-gcp.html
        - title: Back up on-premises ONTAP to StorageGRID
          url: /task-backup-onprem-private-cloud.html
        - title: Manage ONTAP backups
          url: /task-manage-backups-ontap.html
        - title: Manage cluster-level backup settings
          url: /task-manage-backup-settings-ontap.html
        - title: Restore from ONTAP backups
          url: /task-restore-backups-ontap.html
    - title: Back up and restore Kubernetes data
      entries:
        - title: Protect your Kubernetes data
          url: /concept-kubernetes-backup-to-cloud.html
        - title: Back up to Amazon S3
          flavor: aws
          url: /task-backup-kubernetes-to-s3.html
        - title: Back up to Azure Blob
          flavor: azure
          url: /task-backup-kubernetes-to-azure.html
        - title: Back up to Google Cloud
          flavor: gcp
          url: /task-backup-kubernetes-to-gcp.html
        - title: Manage Kubernetes backups
          url: /task-manage-backups-kubernetes.html
        - title: Restore from Kubernetes backups
          url: /task-restore-backups-kubernetes.html
    - title: Back up and restore on-premises applications data
      entries:
        - title: Protect your on-premises applications data
          url: /concept-protect-app-data-to-cloud.html
        - title: Register SnapCenter Server
          url: /task-register-snapcenter-server.html
        - title: Create a policy to back up applications
          url: /task-create-policies-apps.html
        - title: Back up on-premises applications data to Amazon Web Services
          flavor: aws
          url: /task-backup-app-data-to-aws.html
        - title: Back up on-premises applications data to Microsoft Azure
          flavor: azure
          url: /task-backup-app-data-to-azure.html
        - title: Back up on-premises applications data to Google Cloud
          flavor: gcp
          url: /task-backup-app-data-to-gcp.html
        - title: Back up on-premises applications data to StorageGRID
          url: /task-backup-app-data-to-storagegrid.html
        - title: Manage protection of applications
          url: /task-manage-app-backups.html
        - title: Restore on-premises applications data
          entries:
            - title: Restore Oracle database
              url: /task-restore-oracle-data.html
            - title: Restore SQL Server database
              url: /task-restore-sql-data.html
        - title: Mount application backups
          url: /task-mount-app-backup.html
    - title: Back up and restore cloud native applications data
      entries:
        - title: Protect your cloud native applications data
          url: /concept-protect-cloud-app-data-to-cloud.html
        - title: Back up cloud native Oracle database
          entries:
            - title: Quick start
              url: /task-quick-start-oracle.html
            - title: Configure FSx for ONTAP
              url: /reference-configure-fsx-for-ontap.html
            - title: Configure Cloud Volumes ONTAP
              url: /reference-configure-cloud-volumes-ontap.html
            - title: Configure Azure NetApp Files
              flavor: azure
              url: /reference-configure-azure-netapp-files.html
            - title: Deploy SnapCenter Plug-in for Oracle and add database hosts
              url: /task-add-host-discover-oracle-databases.html
            - title: Back up Oracle database
              url: /task-backup-cloud-native-oracle-data.html
        - title: Back up cloud native SAP HANA database
          entries:
            - title: Quick start
              flavor: azure
              url: /task-quick-start-hana.html
            - title: Configure Azure NetApp Files
              flavor: azure
              url: /reference-configure-azure-netapp-files.html
            - title: Deploy SnapCenter Plug-in for SAP HANA and add database hosts
              flavor: azure
              url: /task-deploy-snapcenter-plugin-for-sap-hana.html
            - title: Back up SAP HANA database
              flavor: azure
              url: /task-backup-cloud-native-sap-hana-data.html                    
        - title: Restore cloud native Oracle database
          url: /task-restore-cloud-native-oracle-data.html
        - title: Restore cloud native SAP HANA database
          flavor: azure
          url: /task-restore-cloud-native-sap-hana-data.html
        - title: Refresh SAP HANA target system
          url: /task-refresh-sap-hana-target-system.html
        - title: Clone cloud native Oracle database
          entries:
            - title: Clone concepts and requirements
              url: /concept-clone-cloud-native-oracle-concepts.html
            - title: Clone cloud native Oracle database
              url: /task-clone-cloud-native-oracle-data.html
        - title: Manage protection of cloud native application data
          url: /task-manage-cloud-native-app-data.html
    - title: Back up and restore Virtual Machines data
      entries:
        - title: Protect your Virtual Machines data
          url: /concept-protect-vm-data.html
        - title: Register SnapCenter Plug-in for VMware vSphere
          url: /task-register-snapCenter-plug-in-for-vmware-vsphere.html
        - title: Create a policy to back up virtual machines
          url: /task-create-policies-vms.html
        - title: Back up datastores to Amazon Web Services
          flavor: aws
          url: /task-backup-vm-data-to-aws.html
        - title: Back up datastores to Microsoft Azure
          flavor: azure
          url: /task-backup-vm-data-to-azure.html
        - title: Back up datastores to Google Cloud Platform
          flavor: gcp
          url: /task-backup-vm-data-to-gcp.html  
        - title: Back up datastores to StorageGRID
          url: /task-backup-vm-data-to-storagegrid.html
        - title: Manage protection of Virtual Machines
          url: /task-manage-vm-data-in-cloud.html
        - title: Restore Virtual Machines data
          url: /task-restore-vm-data.html
    - title: Automate with the REST API
      url: /api-backup-restore.html
    - title: Reference
      entries:
        - title: Cloud Backup policy settings
          url: /concept-cloud-backup-policies.html
        - title: Supported AWS archive storage tiers
          flavor: aws
          url: /reference-aws-backup-tiers.html
        - title: Supported Azure archive access tiers
          flavor: azure
          url: /reference-azure-backup-tiers.html
        - title: Supported Google archive storage tiers
          flavor: gcp
          url: /reference-google-backup-tiers.html
        - title: Back up the Cloud Backup database in a dark site
          url: /reference-backup-cbs-db-in-dark-site.html
        - title: Configure Backup for multi-account access in Azure
          flavor: azure
          url: /reference-backup-multi-account-azure.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: All BlueXP documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: Learn about Cloud Backup
          url: concept-backup-to-cloud.html
        - title: What's New
          url: whats-new.html
        - title: Set up licensing
          url: task-licensing-cloud-backup.html
        - title: Monitor the status of backup and restore jobs
          url: task-monitor-backup-jobs.html
    - title: Back up ONTAP data to the cloud
      links:
        - title: Cloud Volumes ONTAP to Amazon S3
          url: task-backup-to-s3.html
          flavor: aws
        - title: Cloud Volumes ONTAP to Azure Blob
          url: task-backup-to-azure.html
          flavor: azure
        - title: Cloud Volumes ONTAP to Google Cloud
          url: task-backup-to-gcp.html
          flavor: gcp
        - title: On-premises ONTAP to Amazon S3
          url: task-backup-onprem-to-aws.html
          flavor: aws
        - title: On-premises ONTAP to Azure Blob
          url: task-backup-onprem-to-azure.html
          flavor: azure
        - title: On-premises ONTAP to Google Cloud
          url: task-backup-onprem-to-gcp.html
          flavor: gcp
        - title: On-premises ONTAP to StorageGRID
          url: task-backup-onprem-private-cloud.html
    - title: Back up Kubernetes data to the cloud
      links:
        - title: Kubernetes cluster to Amazon S3
          url: task-backup-kubernetes-to-s3.html
          flavor: aws
        - title: Kubernetes cluster to Azure Blob
          url: task-backup-kubernetes-to-azure.html
          flavor: azure
        - title: Kubernetes cluster to Google Cloud
          url: task-backup-kubernetes-to-gcp.html
          flavor: gcp
    - title: Back up applications data to the cloud
      links:
        - title: Back up on-premises applications data to Amazon Web Services
          flavor: aws
          url: /task-backup-app-data-to-aws.html
        - title: Back up on-premises applications data to Microsoft Azure
          flavor: azure
          url: /task-backup-app-data-to-azure.html
        - title: Back up on-premises applications data to Google Cloud
          flavor: gcp
          url: /task-backup-app-data-to-gcp.html
        - title: Back up on-premises applications data to StorageGRID
          url: /task-backup-app-data-to-storagegrid.html
        - title: Back up cloud native Oracle database
          url: task-backup-cloud-native-oracle-data.html
        - title: Back up cloud native SAP HANA database
          url: task-backup-cloud-native-sap-hana-data.html
    - title: Back up and restore virtual machines data
      links:
        - title: Back up datastores to Amazon Web Services
          flavor: aws
          url: /task-backup-vm-data-to-aws.html
        - title: Back up datastores to Microsoft Azure
          flavor: azure
          url: /task-backup-vm-data-to-azure.html
        - title: Back up datastores to Google Cloud Platform
          flavor: gcp
          url: /task-backup-vm-data-to-gcp.html  
        - title: Back up datastores to StorageGRID
          url: /task-backup-vm-data-to-storagegrid.html
        - title: Restore virtual machines from the cloud
          url: task-restore-vm-data.html
    - title: Restore data from ONTAP backup files
      links:
        - title: Restore ONTAP volumes
          url: task-restore-backups-ontap.html
        - title: Restore files and folders from ONTAP volumes
          url: task-restore-backups-ontap.html
        - title: Restore Kubernetes volumes
          url: task-restore-backups-kubernetes.html
    - title: Manage ONTAP backup files
      links:
        - title: Enable and disable volume backups
          url: task-manage-backups-ontap.html#enabling-and-disabling-backups-of-volumes
        - title: Edit an existing backup policy
          url: task-manage-backups-ontap.html#editing-an-existing-backup-policy
        - title: Add a new backup policy
          url: task-manage-backups-ontap.html#adding-a-new-backup-policy
        - title: Change the policy assigned to existing volumes
          url: task-manage-backups-ontap.html#changing-the-policy-assigned-to-existing-volumes
        - title: Create a manual volume backup
          url: task-manage-backups-ontap.html#creating-a-manual-volume-backup-at-any-time
        - title: View the list of backups for each volume
          url: task-manage-backups-ontap.html#viewing-the-list-of-backups-for-each-volume
        - title: Delete backups
          url: task-manage-backups-ontap.html#deleting-backups
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Public-Cloud-Services/ct-p/CDS
        - title: Cloud Backup blogs
          url: https://bluexp.netapp.com/blog/topic/cloud-backup
        - title: Cloud Backup use cases
          url: https://bluexp.netapp.com/cloud-backup
        - title: Cloud webinars
          url: https://bluexp.netapp.com/events
