settings:
  name: BlueXP backup and recovery
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  filter:
    label: Cloud provider
    default: All cloud providers
    options:
      - name: Amazon Web Services
        alias: AWS
        id: aws
      - name: Google Cloud
        alias: Google Cloud
        id: gcp
      - name: Microsoft Azure
        alias: Azure
        id: azure
sidebar:
  entries:
    - title: BlueXP backup and recovery docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Known limitations for Microsoft SQL Server workloads
          url: /br-limitations.html
        - title: Known limitations for ONTAP volumes workloads
          url: /br-reference-limitations.html
    - title: Get started
      entries:
        - title: Learn about BlueXP backup and recovery
          url: /concept-backup-to-cloud.html
#        - title: Set up a BlueXP backup and recovery Preview version
#          url: /br-start-preview-setup.html
        - title: Prerequisites for BlueXP backup and recovery
          url: /concept-start-prereq.html  

        - title: Set up licensing for BlueXP backup and recovery
          url: /br-start-licensing.html
        - title: Set up backup destinations before you use BlueXP backup and recovery
          url: /br-start-setup.html
        - title: Log in to BlueXP backup and recovery
          url: /br-start-login.html
        - title: Discover backup targets
          url: /br-start-discover-backup-targets.html
        - title: Switch to different BlueXP backup and recovery workloads
          url: /br-start-switch-ui.html
        - title: Configure BlueXP backup and recovery general settings
          url: /br-start-configure.html
    - title: Use BlueXP backup and recovery
      entries:
        - title: View protection health in the Dashboard 
          url: /br-use-dashboard.html  
        - title: Create policies to govern backups and restores
          url: /br-use-policies-create.html
        - title: Protect ONTAP volume workloads (with SnapCenter)
          entries: 
            - title: Protect ONTAP volume workloads overview
              url: /prev-ontap-protect-overview.html
            - title: Plan your protection journey for ONTAP volumes
              url: /prev-ontap-protect-journey.html
            - title: Manage policies for ONTAP volumes 
              url: /prev-ontap-policy-manage.html
            - title: Backup-to-object policy options for ONTAP volumes
              url: /prev-ontap-policy-object-options.html
            - title: Manage backup-to-object policy Advanced Settings options
              url: /prev-ontap-policy-object-advanced-settings.html
            - title: Back up Cloud Volumes ONTAP to Amazon S3
              url: /prev-ontap-backup-cvo-aws.html
            - title: Back up Cloud Volumes ONTAP to Azure Blob 
              url: /prev-ontap-backup-cvo-azure.html
            - title: Back up Cloud Volumes ONTAP to Google Cloud
              url: /prev-ontap-backup-cvo-gcp.html
            - title: Back up on-premises ONTAP to Amazon S3 
              url: /prev-ontap-backup-onprem-aws.html
            - title: Back up on-premises ONTAP to Azure Blob
              url: /prev-ontap-backup-onprem-azure.html
            - title: Back up on-premises ONTAP to Google Cloud 
              url: /prev-ontap-backup-onprem-gcp.html
            - title: Back up on-premises ONTAP to ONTAP S3 
              url: /prev-ontap-backup-onprem-ontaps3.html
            - title: Back up on-premises ONTAP to StorageGRID
              url: /prev-ontap-backup-onprem-storagegrid.html
            - title: Migrate volumes using SnapMirror to Cloud Resync   
              url: /prev-ontap-migrate-resync.html
            - title: Manage ONTAP backups
              url: /prev-ontap-backup-manage.html
            - title: Restore from ONTAP backups 
              url: /prev-ontap-restore.html
        - title: Protect Microsoft SQL Server workloads (Preview)
          entries:
            - title: Protect Microsoft SQL Server workloads overview
              url: /br-use-mssql-protect-overview.html
            - title: Configure additional items if importing from SnapCenter
              url: /concept-start-prereq-snapcenter-import.html
            - title: Discover Microsoft SQL Server workloads
              url: /br-start-discover.html            
            - title: Back up Microsoft SQL Server workloads
              url: /br-use-mssql-backup.html
            - title: Restore Microsoft SQL Server workloads
              url: /br-use-mssql-restore.html              
            - title: Clone Microsoft SQL Server workloads
              url: /br-use-mssql-clone.html
            - title: Manage Microsoft SQL Server inventory 
              url: /br-use-manage-inventory.html 
            - title: Manage Microsoft SQL Server snapshots
              url: /br-use-manage-snapshots.html
            - title: Create Microsoft SQL Server reports 
              url: /br-use-reports.html
        - title: Protect VM workloads (Preview without SnapCenter Plug-in for VMware)
          entries:
            - title: Protect VMware workloads overview
              url: /br-use-vmware-protect-overview.html
            - title: Discover VMware workloads
              url: /br-use-vmware-discovery.html
            - title: Create and manage protection groups for VMware workloads
              url: /br-use-vmware-protection-groups.html
            - title: Back up VMware workloads
              url: /br-use-vmware-backup.html
            - title: Restore VMware workloads
              url: /br-use-vmware-restore.html
        - title: Protect VM workloads (with SnapCenter Plug-in for VMware)
          entries:  
            - title: Protect virtual machine workloads overview
              url: /prev-vmware-protect-overview.html
            - title: Prerequisites for protecting virtual machines workloads
              url: /prev-vmware-prereqs.html
            - title: Register SnapCenter Plug-in for VMware vSphere host
              url: /prev-vmware-register-snapcenter.html
            - title: Create a policy to back up virtual machine data
              url: /prev-vmware-policy-create.html         
            - title: Back up datastores to Amazon Web Services
              url: /prev-vmware-backup-aws.html
            - title: Back up datastores to Microsoft Azure
              url: /prev-vmware-backup-azure.html
            - title: Back up datastores to Google Cloud Platform
              url: /prev-vmware-backup-gcp.html
            - title: Back up datastores to StorageGRID
              url: /prev-vmware-backup-storagegrid.html 
            - title: Manage protection of datastores and virtual machines data
              url: /prev-vmware-manage.html
            - title: Restore virtual machine data and datastores
              url: /prev-vmware-restore.html
        - title: Protect Kubernetes workloads (Preview)
          entries:
            - title: Protect Kubernetes workloads overview
              url: /br-use-kubernetes-protect-overview.html
            - title: Discover Kubernetes workloads
              url: /br-start-discover-kubernetes.html
            - title: Add and protect Kubernetes applications 
              url: /br-use-protect-kubernetes-applications.html
            - title: Restore Kubernetes applications
              url: /br-use-restore-kubernetes-applications.html
            - title: Manage Kubernetes clusters
              url: /br-use-manage-kubernetes-clusters.html
            - title: Manage Kubernetes applications
              url: /br-use-manage-kubernetes-applications.html
            - title: Manage execution hook templates for Kubernetes workloads
              url: /br-use-manage-execution-hook-templates.html       
        - title: Monitor jobs
          url: /br-use-monitor-tasks.html
        - title: Restart BlueXP backup and recovery
          url: /reference-restart-backup.html
    - title: Automate with the REST API
      url: /br-api-backup-restore.html          
    - title: Reference 
      entries:
        - title: Policies in SnapCenter compared to BlueXP backup and recovery
          url: /reference-policy-differences-snapcenter.html
        - title: BlueXP backup and recovery roles and privileges
          url: /reference-roles.html
        - title: Restore BlueXP backup and recovery data in a dark site
          url: /reference-backup-cbs-db-in-dark-site.html
        - title: Supported AWS archive storage tiers
          url: /prev-reference-aws-archive-storage-tiers.html
        - title: Supported Azure archive storage tiers
          url: /prev-reference-azure-archive-storage-tiers.html
        - title: Supported Google Cloud archive storage tiers
          url: /prev-reference-gcp-archive-storage-tiers.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
