settings:
  name: BlueXP backup and recovery
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  filter:
    label: Cloud provider
    default: All cloud providers
    options:
      - name: Amazon Web Services
        alias: AWS
        id: aws
      - name: Google Cloud
        alias: Google Cloud
        id: gcp
      - name: Microsoft Azure
        alias: Azure
        id: azure
sidebar:
  entries:
    - title: BlueXP backup and recovery Preview 2025 docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about BlueXP backup and recovery Preview version
          url: /concept-backup-to-cloud.html
        - title: Prerequisites for BlueXP backup and recovery Preview version
          url: /concept-start-prereq.html  
        - title: Set up BlueXP backup and recovery Preview version
          url: /br-start-setup.html
        - title: Log in to BlueXP backup and recovery Preview version
          url: /br-start-login.html
        - title: Discover workloads 
          url: /br-start-discover.html
        - title: Configure BlueXP backup and recovery settings 
          url: /br-start-configure.html
        - title: Manage backup-to-object storage options in Advanced Settings
          url: /task-manage-backup-settings-ontap.html
        - title: FAQ
          url: /br-start-faq.html
    - title: Use BlueXP backup and recovery Preview version
      entries:
        - title: View protection health in the Dashboard 
          url: /br-use-dashboard.html
        - title: Create and manage policies to govern backups and restores
          url: /task-create-policies-ontap.html
        - title: Back up workloads 
          entries:
            - title: Back up workloads overview
              url: /br-use-backup-overview.html
            - title: Plan your protection journey
              url: /concept-protection-journey.html
            - title: Manage backup policies for ONTAP volumes
              url: /task-create-policies-ontap.html 
            - title: Backup-to-object policy options
              url: /concept-cloud-backup-policies.html               
            - title: Back up Microsoft SQL Server workloads
              url: /br-use-backup-mssql.html
        - title: Restore workloads
          entries:  
            - title: Restore workloads overview     
              url: /br-use-restore-overview.html
            - title: Restore Microsoft SQL Server workloads
              url: /br-use-restore-mssql.html
        - title: Manage inventory, snapshots, and policies       
          url: /br-use-manage-overview.html
        - title: Restart BlueXP backup and recovery
          url: /reference-restart-backup.html
        - title: Manage options in Advanced Settings
          url: /br-use-settings-advanced.html
    - title: OLD STUFF Back up and restore on-premises applications data
      entries:
        - title: Protect your on-premises applications data
          url: /concept-protect-app-data-to-cloud.html
        - title: Register SnapCenter Server
          url: /task-register-snapcenter-server.html
        - title: Create a policy to back up applications
          url: /task-create-policies-apps.html
        - title: Back up on-premises applications data to Amazon Web Services
          flavor: aws
          url: /task-backup-app-data-to-aws.html
        - title: Back up on-premises applications data to Microsoft Azure
          flavor: azure
          url: /task-backup-app-data-to-azure.html
        - title: Back up on-premises applications data to Google Cloud
          flavor: gcp
          url: /task-backup-app-data-to-gcp.html
        - title: Back up on-premises applications data to StorageGRID
          url: /task-backup-app-data-to-storagegrid.html
        - title: Manage protection of applications
          url: /task-manage-app-backups.html
        - title: Restore on-premises applications data
          entries:
            - title: Restore Oracle database
              url: /task-restore-oracle-data.html
            - title: Restore SQL Server database
              url: /task-restore-sql-data.html
            - title: Restore SAP HANA database
              url: /task-restore-hana-backup.html
            - title: Restore MongoDB, MySQL, and PostgreSQL databases
              url: /task-restore-customplugin-backup.html
    - title: Automate with the REST API
      url: /api-backup-restore.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
