settings:
  name: BlueXP backup and recovery
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  filter:
    label: Cloud provider
    default: All cloud providers
    options:
      - name: Amazon Web Services
        alias: AWS
        id: aws
      - name: Google Cloud
        alias: Google Cloud
        id: gcp
      - name: Microsoft Azure
        alias: Azure
        id: azure
sidebar:
  entries:
    - title: BlueXP backup and recovery Preview 2025 docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Known limitations
          url: /br-limitations.html
    - title: Get started
      entries:
        - title: Learn about BlueXP backup and recovery Preview version
          url: /concept-backup-to-cloud.html
        - title: Set up the BlueXP backup and recovery Preview version
          url: /br-start-preview-setup.html
        - title: Prerequisites for BlueXP backup and recovery Preview version
          url: /concept-start-prereq.html  
        - title: Configure additional items if importing from SnapCenter
          url: /concept-start-prereq-snapcenter-import.html
        - title: Set up backup destinations before you use BlueXP backup and recovery
          url: /br-start-setup.html
        - title: Log in to BlueXP backup and recovery
          url: /br-start-login.html
        - title: Discover workloads and optionally import SnapCenter resources
          url: /br-start-discover.html
        - title: Configure BlueXP backup and recovery settings 
          url: /br-start-configure.html
    - title: Use BlueXP backup and recovery
      entries:
        - title: View protection health in the Dashboard 
          url: /br-use-dashboard.html
        - title: Create and manage backup policies
          url: /br-use-manage-policies.html
        - title: Manage execution hooks
          url: /br-use-manage-execution-hooks.html          
        - title: Back up workloads 
          entries:
            - title: Back up workloads overview
              url: /br-use-backup-overview.html
            - title: Back up Microsoft SQL Server workloads
              url: /br-use-backup-mssql.html
            - title: Back up Kubernetes workloads
              url: /br-use-backup-kubernetes.html
        - title: Restore workloads
          entries:  
            - title: Restore workloads overview     
              url: /br-use-restore-overview.html
            - title: Restore database workloads
              url: /br-use-restore-database.html
            - title: Restore Kubernetes workloads
              url: /br-use-restore-kubernetes.html
        - title: Manage inventory, snapshots, and resources       
          entries:
            - title: Manage resources overview
              url: /br-use-manage-overview.html 
            - title: Manage inventory
              url: /br-use-manage-inventory.html 
            - title: Manage snapshots
              url: /br-use-manage-snapshots.html
            - title: Manage Kubernetes clusters
              url: /br-use-manage-kubernetes-clusters.html
            - title: Manage Kubernetes applications
              url: /br-use-manage-kubernetes-applications.html
        - title: Monitor protection tasks
          url: /br-use-monitor-tasks.html
        - title: Restart BlueXP backup and recovery
          url: /reference-restart-backup.html
    - title: Reference 
      entries:
        - title: Policies in SnapCenter compared to BlueXP backup and recovery
          url: /reference-policy-differences-snapcenter.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
