settings:
  name: Cloud Backup
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Back to Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: Cloud Backup docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about Cloud Backup
          url: /concept-backup-to-cloud.html
        - title: Back up Cloud Volumes ONTAP data
          entries:
            - title: Back up to Amazon S3
              url: /task-backup-to-s3.html
            - title: Back up to Azure Blob
              url: /task-backup-to-azure.html
            - title: Back up to Google Cloud
              url: /task-backup-to-gcp.html
        - title: Back up on-premises ONTAP data
          entries:
            - title: Back up to Amazon S3
              url: /task-backup-onprem-to-aws.html
            - title: Back up to Azure Blob
              url: /task-backup-onprem-to-azure.html
            - title: Back up to Google Cloud
              url: /task-backup-onprem-to-gcp.html
            - title: Back up to StorageGRID
              url: /task-backup-onprem-private-cloud.html
        - title: Back up Kubernetes cluster data
          entries:
            - title: Back up to Amazon S3
              url: /task-backup-kubernetes-to-s3.html
            - title: Back up to Azure Blob
              url: /task-backup-kubernetes-to-azure.html
            - title: Back up to Google Cloud
              url: /task-backup-kubernetes-to-gcp.html
    - title: Use Cloud Backup
      entries:
        - title: Set up licensing
          url: /task-licensing-cloud-backup.html
        - title: Manage backups
          url: /task-managing-backups.html
        - title: Restore from backups
          url: /task-restore-backups.html
        - title: Monitor the status of backup and restore jobs
          url: task-monitor-backup-jobs.html
        - title: Reference
          entries:
            - title: Supported AWS archive storage tiers
              url: /reference-aws-backup-tiers.html
            - title: Supported Azure archive access tiers
              url: /reference-azure-backup-tiers.html
            - title: Cross-account and cross-region configurations
              url: /reference-cross-account.html
              entries:
                - title: Configure Backup for multi-account access in AWS
                  url: /reference-backup-multi-account-aws.html
                - title: Configure Backup for multi-account access in Azure
                  url: /reference-backup-multi-account-azure.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
homepage:
  tiles:
    - title: Get started
      links:
        - title: title
          url: page.html
        - title: title
          url: page.html
        - title: title
          url: page.html
    - title: tile name
      links:
        - title: title
          url: page.html
        - title: title
          url: page.html
        - title: title
          url: page.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
