settings:
  name: BlueXP backup and recovery
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  filter:
    label: Cloud provider
    default: All cloud providers
    options:
      - name: Amazon Web Services
        alias: AWS
        id: aws
      - name: Google Cloud
        alias: Google Cloud
        id: gcp
      - name: Microsoft Azure
        alias: Azure
        id: azure
sidebar:
  entries:
    - title: BlueXP backup and recovery Preview 2025 docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about BlueXP backup and recovery Preview version
          url: /concept-backup-to-cloud.html
        - title: Prerequisites for BlueXP backup and recovery Preview version
          url: /concept-start-prereq.html  
        - title: Set up backup destinations before you use BlueXP backup and recovery
          url: /br-start-setup.html
        - title: Log in to BlueXP backup and recovery
          url: /br-start-login.html
        - title: Discover workloads and optionally import SnapCenter resources
          url: /br-start-discover.html
        - title: Configure BlueXP backup and recovery settings 
          url: /br-start-configure.html
        - title: FAQ
          url: /br-start-faq.html
    - title: Use BlueXP backup and recovery
      entries:
        - title: View protection health in the Dashboard 
          url: /br-use-dashboard.html
        - title: Create and manage policies to govern backups and restores
          url: /task-create-policies-ontap.html
        - title: Backup-to-object policy options
          url: /concept-cloud-backup-policies.html  
        - title: Back up workloads 
          entries:
            - title: Back up workloads overview
              url: /br-use-backup-overview.html
            - title: Plan your protection journey
              url: /concept-protection-journey.html       
            - title: Back up Microsoft SQL Server workloads
              url: /br-use-backup-mssql.html
        - title: Restore workloads
          entries:  
            - title: Restore workloads overview     
              url: /br-use-restore-overview.html
            - title: Restore workloads using Browse and Restore
              url: /br-use-restore-browse-and-restore.html
            - title: Restore workloads using Search and Restore
              url: /br-use-restore-search-and-restore.html
        - title: Manage inventory, snapshots, and policies       
          url: /br-use-manage-overview.html
        - title: Restart BlueXP backup and recovery
          url: /reference-restart-backup.html
        - title: Manage options in Advanced Settings
          url: /br-use-settings-advanced.html
    - title: Automate with the REST API
      url: /api-backup-restore.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
