settings:
  name: BlueXP backup and recovery
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  filter:
    label: Cloud provider
    default: All cloud providers
    options:
      - name: Amazon Web Services
        alias: AWS
        id: aws
      - name: Google Cloud
        alias: Google Cloud
        id: gcp
      - name: Microsoft Azure
        alias: Azure
        id: azure
sidebar:
  entries:
    - title: BlueXP backup and recovery docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Known limitations
          url: /br-limitations.html
    - title: Get started
      entries:
        - title: Learn about BlueXP backup and recovery
          url: /concept-backup-to-cloud.html
        - title: Set up a BlueXP backup and recovery Preview version
          url: /br-start-preview-setup.html
        - title: Prerequisites for BlueXP backup and recovery
          url: /concept-start-prereq.html  
        - title: Configure additional items if importing from SnapCenter
          url: /concept-start-prereq-snapcenter-import.html
        - title: Set up licensing for BlueXP backup and recovery
          url: /br-start-licensing.html
        - title: Set up backup destinations before you use BlueXP backup and recovery
          url: /br-start-setup.html
        - title: Log in to BlueXP backup and recovery
          url: /br-start-login.html
        - title: Start a free trial
          url: /br-start-trial.html
        - title: Discover workloads and optionally import SnapCenter resources
          url: /br-start-discover.html
        - title: Switch between BlueXP backup and recovery UIs 
          url: /br-start-switch-ui.html
        - title: Configure BlueXP backup and recovery settings 
          url: /br-start-configure.html
    - title: Use BlueXP backup and recovery
      entries:
        - title: View protection health in the Dashboard 
          url: /br-use-dashboard.html
        - title: Create and manage policies to govern backups and restores
          url: /br-use-policies-create.html
        - title: Protect Microsoft SQL workloads 
          entries:
            - title: Protect Microsoft SQL workloads overview
              url: /br-use-mssql-protect-overview.html
            - title: Back up Microsoft SQL workloads
              url: /br-use-mssql-backup.html
            - title: Restore Microsoft SQL workloads
              url: /br-use-mssql-restore.html              
            - title: Clone Microsoft SQL workloads
              url: /br-use-mssql-clone.html
        - title: Protect VMware workloads
          entries:  
            - title: Protect VMware workloads overview
              url: /br-use-vmware-protect-overview.html
            - title: Back up VMware workloads
              url: /br-use-vmware-backup.html
            - title: Restore VMware workloads
              url: /br-use-vmware-restore.html
        - title: Protect Kubernetes workloads
          entries:
            - title: Protect Kubernetes workloads overview
              url: /br-use-kubernetes-protect-overview.html
            - title: Discover a Kubernetes cluster
              url: /br-use-kubernetes-discover.html
            - title: Create Kubernetes applications
              url: /br-use-kubernetes-applications.html
            - title: Back up Kubernetes workloads
              url: /br-use-kubernetes-backup.html
            - title: Restore Kubernetes workloads
              url: /br-use-kubernetes-restore.html
        - title: Manage inventory, snapshots, and policies       
          entries:
            - title: Manage resources overview
              url: /br-use-manage-overview.html 
            - title: Manage inventory
              url: /br-use-manage-inventory.html 
            - title: Manage snapshots
              url: /br-use-manage-snapshots.html
        - title: Create reports 
          url: /br-use-reports.html
        - title: Restart BlueXP backup and recovery
          url: /reference-restart-backup.html
    - title: Use a previous version of BlueXP backup and recovery
      entries:
        - title: Use a previous version of BlueXP backup and recovery
          url: /br-use-previous-version.html 
        - title: Protect VMware workloads with a previous BlueXP backup and recovery version 
          entries:  
            - title: Protect VMware workloads overview
              url: /prev-vmware-protect-overview.html
            - title: Register SnapCenter Plug-in for VMware vSphere host
              url: /prev-vmware-register-snapcenter.htnl
            - title: Create a policy to back up datastores
              url: /prev-vmware-policy-create.html         
            - title: Back up datastores to Amazon Web Services
              url: /prev-vmware-backup-aws.html
            - title: Back up datastores to Microsoft Azure
              url: /prev-vmware-backup-azure.html
            - title: Back up datastores to Google Cloud Platform
              url: /prev-vmware-backup-gcp.html
            - title: Back up datasores to StorageGRID
              url: /prev-vmware-backup-storagegrid.html 
            - title: Manage protection of datastores and virtual machines data
              url: /prev-vmware-manage.html
            - title: Restore virtual machines datasores
              url: /prev-vmware-restore.html

    - title: Automate with the REST API
      url: /br-api-backup-restore.html          
    - title: Reference 
      entries:
        - title: Policies in SnapCenter compared to BlueXP backup and recovery
          url: /reference-policy-differences-snapcenter.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
