---
sidebar: sidebar
permalink: reference-configure-fsx-for-ontap.html
keywords: Cloud Manager, FSx for ONTAP, working environment, Connector, BlueXP
summary:  Create the FSx for ONTAP working environment and the Connector
---

= Configure FSx for ONTAP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Using BlueXP you should create an FSx for ONTAP working environment to add and manage volumes and additional data services. You should also create a Connector in AWS that enables BlueXP to manage resources and processes within your public cloud environment.

== Create FSx for ONTAP working environment

You should create the FSx for ONTAP working environments where your databases are hosted. For information, refer to link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/start/task-getting-started-fsx.html[Get started with Amazon FSx for ONTAP] and link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html[Create and manage an Amazon FSx for ONTAP working environment].

You can create the FSx for ONTAP working environment either using BlueXP or AWS. If you have created using AWS, then you should discover the FSx for ONTAP systems in BlueXP.

== Create a Connector

An Account Admin needs to create a Connector in AWS that enables BlueXP to manage resources and processes within your public cloud environment.

For information, refer to link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-aws.html[Creating a Connector in AWS from BlueXP].

* You should use the same connector to manage both FSx for ONTAP working environment and databases.
* If you have the FSx for ONTAP working environment and databases in the same virtual private cloud (VPC), you can deploy the connector in the same VPC.
* If you have the FSx for ONTAP working environment and  databases in different VPCs:
** If you have NAS (NFS) workloads configured on FSx for ONTAP, then you can create the connector on either of the VPCs.
** If you have only SAN workloads configured and not planning to use any NAS (NFS) workloads, then you should create the connector in the VPC where the FSx for ONTAP system is created.
+
NOTE: For using NAS (NFS) workloads, you should have transit gateway between the database VPC and Amazon VPC. The NFS IP address which is a floating IP address can be accessed from another VPC only through transit gateway. We cannot access the floating IP addresses by peering the VPCs.

After creating the Connector, click *Storage* > *Canvas* > *My Working Environments* > *Add Working Environment* and follow the prompts to add the working environment.
Ensure that there is connectivity from the Connector to the Oracle database hosts and FSx working environment. The Connector should be able to connect to the cluster management IP address of the FSx working environment.

* Add the working environment by clicking *Storage* > *Canvas* > *My Working Environments* > *Add Working Environment*.
+
Ensure that there is connectivity from the connector to the database hosts and FSx for ONTAP working environment. The connector should connect to the cluster management IP address of the FSx for ONTAP working environment.
* Copy the Connector ID by clicking *Connector > Manage Connectors* and selecting the Connector name.