---
sidebar: sidebar
permalink: reference-prereq-protect-cloud-native-app-data.html
keywords: Cloud Manager, FSx for ONTAP, working environment, Connector, AWS, deploy Oracle plug-in
summary:  Complete the prerequisites before creating backups.
---

= Prerequisites
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

You should have access to Cloud Manager, created a Cloud Manager account, created the working environment and a Connector, and deployed the SnapCenter Plug-in for Oracle.

== Access Cloud Manager

You should link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-signing-up.html[sign up to NetApp Cloud Central], link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html[log into Cloud Manager], and then set up a link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-setting-up-netapp-accounts.html[NetApp account].

== Create FSx for ONTAP working environment

You should create the Amazon FSx for ONTAP working environments where your databases are hosted. For information, refer to link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/start/task-getting-started-fsx.html[Get started with Amazon FSx for ONTAP] and link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html[Create and manage an Amazon FSx for ONTAP working environment].

You can create the NetApp FSx either using Cloud Manager or AWS. If you have created using AWS, then you should discover the FSx for ONTAP systems in Cloud Manager.

== Create a Connector

An Account Admin needs to deploy a Connector in AWS that enables Cloud Manager to manage resources and processes within your public cloud environment.

For information, refer to link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-aws.html[Creating a Connector in AWS from Cloud Manager].

* You should use the same connector to manage both FSx working environment and Oracle databases.
* If you have the FSx working environment and Oracle databases in the same VPC, you can deploy the connector in the same VPC.
* If you have the FSx working environment and Oracle databases in different VPCs:
** If you have NAS (NFS) workloads configured on FSx, then you can create the connector on either of the VPCs.
** If you have only SAN workloads configured and not planning to use any NAS (NFS) workloads, then you should create the connector in the VPC where the FSx system is created.
+
NOTE: For using NAS (NFS) workloads, you should have transit gateway between the Oracle database VPC and FSx VPC. The NFS IP address which is a floating IP address can be accessed from another VPC only through transit gateway. We cannot access the floating IP addresses by peering the VPCs.

After creating the connector, click *Canvas* > *Add Working Environment* and when prompted enter the ONTAP credentials.

Ensure that there is connectivity from the connector to the Oracle database hosts and FSx working environment. The connector should be able to connect to the cluster management IP address of the FSx working environment.

IMPORTANT: After creating the Connector, click *Connector > Manage Connectors*; select the Connector name and copy the Connector ID.

== Deploy SnapCenter Plug-in for Oracle

You should manually deploy the SnapCenter Plug-in for Oracle on each of the Oracle database hosts.

Depending on whether you have SSH key and scp on the Oracle host, you can follow one of the methods to deploy the plug-in.

NOTE: Ensure that JAVA 8 is installed on each of the Oracle database hosts and the JAVA_HOME variable is set appropriately.

=== Deploy plug-in when you have SSH key and scp

*Steps*

. Log into the Connector VM.
. Obtain the base mount path.
`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`
. Copy the certificate from _<base_mount_path>/client/certificate/certificate.p12_ to _/var/opt/snapcenter/spl/etc/_ on the plug-in host.
+
NOTE: The certificate name should be certificate.p12 and you should not chnage the name while copying.
+

.. Navigate to _/var/opt/snapcenter/spl/etc_ and execute the keytool command to import the certificate.
+
... `keytool -v -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore keystore.jks -deststoretype JKS -srcstorepass snapcenter -deststorepass snapcenter -srcalias agentcert -destalias agentcert -nopromp`
... Verify that the import was successful.
`keytool -keystore keystore.jks -list`
... Set *ENABLE_CLIENT_CERTIFICATE_AUTHENTICATION* to *true* in the _spl.properties_ file.
.. Restart SPL: `systemctl restart spl`
. Deploy the plug-in.
+
`sudo <base_mount_path>/scripts/oracle_plugin_copy_and_install.sh --host <host_name> --sshkey <ssh_key_file> --username <user_name> --port <ssh_port> --pluginport <plugin_port> --installdir <install_dir>`
+
* host_name is the name of the Oracle host and this is a mandatory parameter.
* ssh_key_file is SSH key used to connect to the Oracle host and this is a mandatory parameter.
* user_name: User with SSH privileges on the Oracle host and this is an optional parameter. Default value is ec2-user.
* ssh_port: SSH port on the Oracle host and this is an optional parameter. Default value is 22
* plugin_port: Port used by the plug-in and this is an optional parameter. Default value is 8145
* install_dir: Directory where the plug-in will be deployed and this is an optional parameter. Default value is /opt.


=== Deploy plug-in when you do not have SSH key

*Steps*

. Log into the Connector VM.
. Download the SnapCenter Linux host plug-in binary.
`sudo docker exec -it cloudmanager_scs_cloud curl -X GET 'http://127.0.0.1/deploy/downloadLinuxPlugin'`
. Obtain the binary path of the downloaded plug-in.
`sudo ls /var/lib/docker/volumes/cloudmanager_scs_cloud_volume/_data/$(sudo docker ps|grep -Po "cloudmanager_scs_cloud:.*? "|sed -e 's/ *$//'|cut -f2 -d":")/sc-linux-host-plugin/snapcenter_linux_host_plugin_scs.bin`
. Copy _snapcenter_linux_host_plugin_scs.bin_ to each of the Oracle database hosts either using scp or other alternate methods.
. On the Oracle database host, run the following command to enable execute permissions for the binary.
`chmod +x snapcenter_linux_host_plugin_scs.bin`
. Deploy the Oracle plug-in as a root user.
`./snapcenter_linux_host_plugin_scs.bin -i silent`
. Obtain the base mount path.
`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`
. Copy the certificate from _<base_mount_path>/client/certificate/certificate.p12_ to _/var/opt/snapcenter/spl/etc/_ on the plug-in host.
+
.. Navigate to _/var/opt/snapcenter/spl/etc_ and execute the keytool command
+
... `keytool -v -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore keystore.jks -deststoretype JKS -srcstorepass snapcenter -deststorepass snapcenter -srcalias agentcert -destalias agentcert -nopromp`
... Set *ENABLE_CLIENT_CERTIFICATE_AUTHENTICATION* to *true* in the _spl.properties_ file.
.. Restart SPL: `systemctl restart spl`

== Configure CA signed certificate

You can configure CA signed certificate if you want to include additional security to your environment.

=== Configure CA signed certificate for client certificate authentication

The connector uses a self-signed certificate to communicate with plug-in. The self-signed certificate is imported to the keystore by the installation script. You can perform the following steps to replace the self-signed certificate with CA signed certificate.

*Steps*

. Copy the certificate and key at _<base_mount_path>/client/certificate_.
+
The file name should be certificate.pem and key.pem.
. Create the PKCS12 format of the certificate with the name certificate.p12 and keep at the same location _<base_mount_path>/client/certificate_.
. Copy the PKCS12 file plug-in host at _/var/opt/snapcenter/spl/etc/_.
+
Copy the intermediate ca and root ca certificates also.
. Navigate to _/var/opt/snapcenter/spl/etc_ and run the keytool command.
`keytool -v -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore keystore.jks -deststoretype JKS -srcstorepass snapcenter -deststorepass snapcenter -srcalias agentcert -destalias agentcert -noprompt`
. Import the CA cert files.
`keytool -import -trustcacerts -keystore keystore.jks -storepass snapcenter -alias trustedca -file certificate.crt`
+
NOTE: The CA cert files is chain of intermediate and root ca certificates like NetAppCorpIssuingCA1.crt and NetAppCorpRootCA.crt.

=== Configure CA signed certificate for server certificate of plug-in

The CA certificate should have the exact name of the Oracle plug-in host with which the agent communicates.

*Steps*

. Navigate to the folder containing the SPL’s keystore _/var/opt/snapcenter/spl/etc_.
. Locate the file 'keystore.jks'.
. List the added certificates in the keystore: `keytool -list -v -keystore keystore.jks`
. Add the CA certificate having both private and public key.
`keytool -importkeystore -srckeystore <CertificatePathToImport> -srcstoretype pkcs12 -destkeystore keystore.jks -deststoretype JKS`
. List the added certificates in the keystore.
`keytool -list -v -keystore keystore.jks`
. Verify that the keystore contains the alias corresponding to the new CA certificate, which was added to the keystore.
. Change the added private key password for CA certificate to the keystore password.
+
Default SPL keystore password is the value of the key _SPL_KEYSTORE_PASS_ in _spl.properties_ file.
`keytool -keypasswd -alias "<aliasNameOfAddedCertInKeystore>" -keystore keystore.jks`
. If the alias name in the CA certificate is long and contains space or special characters ("*",","), change the alias name to a simple name:
`keytool -changealias -alias "<OrignalAliasName>" -destalias "<NewAliasName>" -keystore keystore.jks`
. Configure the alias name from the keystore located in spl.properties file.
+
Update this value against the key SPL_CERTIFICATE_ALIAS.
. Restart the service after configuring the CA signed key pair to SPL trust-store.
. Copy the entire chain of CA certificates to the persistent volume located at _<base_mount_path>/server_.
. Connect to the cloudmanager_scs_cloud and modify the *enableCACert* in _config.yml_ to *true*.
`sudo docker exec -t cloudmanager_scs_cloud sed -i 's/enableCACert: false/enableCACert: true/g' /opt/netapp/cloudmanager-scs-cloud/config/config.yml`
. Restart cloudmanager_scs_cloud docker.
`sudo docker restart cloudmanager_scs_cloud`.
