---
sidebar: sidebar
permalink: reference-backup-cbs-db-in-dark-site.html
keywords: backup database, recover database
summary: When using BlueXP backup and recovery in a site without internet access, you'll want to back up critical BlueXP backup and recovery files periodically in case you have an issue with the BlueXP Connector host system. This will enable you to deploy a new Connector and restore the critical BlueXP backup and recovery data.
---

= Back up and restore BlueXP backup and recovery data in a dark site
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When using BlueXP backup and recovery in a site without internet access, you'll want to back up critical BlueXP backup and recovery files periodically in case you have an issue with the BlueXP Connector host system. This will enable you to deploy a new Connector and restore the critical BlueXP backup and recovery data.

When you use BlueXP backup and recovery in a SaaS environment where the BlueXP Connector is deployed at your cloud provider, or on your own host system that has internet access, all the important BlueXP backup and recovery configuration data is backed up and stored in the cloud. When you're using BlueXP backup and recovery in a site with no internet access, known as "restricted mode' or a "dark site", this BlueXP backup and recovery information is stored only on the local Connector system.

We'll describe how to back up critical BlueXP backup and recovery data to your connected StorageGRID system, and how to restore the data onto a new Connector when necessary.

== Back up critical BlueXP backup and recovery data

There are 2 types of data that you need to back up:

* BlueXP backup and recovery database
* Indexed Catalog files (used for Search & Restore functionality)

NOTE: You should plan to back up this BlueXP backup and recovery data periodically so you'll always have access to the most recent data.

Note that no volume data is ever included in the BlueXP backup and recovery database or Indexed Catalog files.

=== Back up the BlueXP backup and recovery database

The BlueXP backup and recovery database contains a listing of all the volumes, backup files, backup policies, and configuration information.

.Steps

. Log into the Connector host system using the appropriate credentials.

. Enter the MySQL container shell by entering the following command:
+
[source,cli]
docker exec -it ds_mysql_1 sh

. In the container shell, deploy the "env".

. You'll need the MySQL DB password, so copy the value of the key "MYSQL_ROOT_PASSWORD".

. Back up the BlueXP backup and recovery MySQL DB by entering the following command:
+
[source,cli]
mysqldump --user root --password -p cloud_backup --result-file=mysql.dump.cloud_backup.sql

. Copy the MySQL DB backup from the MySQL docker container by entering the following command:
+
[source,cli]
docker cp ds_mysql_1:/mysql.dump.cloud_backup.sql .

. Copy the backups to a secure location in your network. You can use a local StorageGRID system if you are creating ONTAP volume backups to that location.

=== Back up the Indexed Catalog files

The Indexed Catalog is used for Search & Restore functionality. It contains information about every volume and every backup file - making your searches very quick and efficient when looking for volume data that you want to restore.

. On the Connector host system, change the directory to "/opt/application/netapp/cbs".

. Locate the Index Catalog folder. It starts with the string *catalog*.

. Zip the "catalog<_xxxxxx_>" folder by entering the following command:
+
[source,cli]
zip -r catalogxxxxxx.zip catalogxxxxxx

. Copy the zipped backup to a secure location in your network.

== Restore BlueXP backup and recovery data to a new Connector

If your on-premises Connector has a catastrophic failure, you'll need to install a new Connector, and then restore the BlueXP backup and recovery data to the new Connector.

There are 4 tasks you'll need to perform to return your BlueXP backup and recovery system to a working state:

* Install a new BlueXP Connector
* Restore the BlueXP backup and recovery database
* Restore the Indexed Catalog files
* Rediscover all of your on-prem ONTAP systems and StorageGRID systems to the BlueXP UI

Once you verify that your system is back in a working order, we recommend that you create new backup files.

=== Install a new Connector on a new on-premises Linux host

When installing a new BlueXP Connector, make sure you download the same release of software as you had installed on the original Connector. Periodic changes to the BlueXP backup and recovery database structure may make newer software releases incompatible with the original database backups. You can https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-managing-connectors.html#upgrade-the-connector-on-prem-without-internet-access[upgrade the Connector software to the most current version after restoring the Backup database^].

. https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-private-mode.html[Install the BlueXP Connector on a new on-premises Linux host^]

. Log into BlueXP using the admin user credentials that you just created.

=== Restore the BlueXP backup and recovery database

. Copy the MySQL backups from the secure location to the new Connector host.

. Copy the backup into the MySQL docker container using the following command:
+
[source,cli]
docker cp mysql.dump.cloud_backup.sql ds_mysql_1:/.

. Enter the MySQL container shell using the following command:
+
[source,cli]
docker exec -it ds_mysql_1 sh

. In the container shell, deploy the "env".

. You'll need the MySQL DB password, so copy the value of the key "MYSQL_ROOT_PASSWORD".

. Restore the BlueXP backup and recovery MySQL DB using the following command:
+
[source,cli]
mysql -u root -p cloud_backup < mysql.dump.cloud_backup.sql

. Verify that the BlueXP backup and recovery MySQL DB has been restored correctly using the following SQL commands:
+
[source,cli]
# mysql -u root -p cloud_backup
+
Enter the password.
+
[source,cli]
mysql> show tables;
mysql> select * from volume; 
+
Check if the volumes that are shown are the same as those that existed in your original environment.

=== Restore the Indexed Catalog files

. Copy the Indexed Catalog backup zip file from the secure location to the new Connector host in the "/opt/application/netapp/cbs" folder.

. Unzip the "catalogxxxxxx.zip" file using the following command:
+
[source,cli]
unzip catalogxxxxxx.zip

. Run the *ls* command to make sure that the folder "catalogxxxxxx" has been created with the subfolders "changes" and "snapshots" underneath.

=== Discover your ONTAP clusters and StorageGRID systems

. https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html#discover-clusters-using-a-connector[Discover all the on-prem ONTAP working environments^] that were available in your previous environment.

. https://docs.netapp.com/us-en/cloud-manager-storagegrid/task-discover-storagegrid.html[Discover your StorageGRID systems^]. 

=== Set up the StorageGRID environment details

Add the details of the StorageGRID system associated with your ONTAP working environments as they were set up on the original Connector setup using the https://docs.netapp.com/us-en/cloud-manager-automation/index.html[BlueXP APIs^].

You'll need to perform these steps for each ONTAP system that is backing up data to StorageGRID.

. Extract the authorization token using the following oauth/token API.
+
[source,http]
curl 'http://10.193.192.202/oauth/token' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100101 Firefox/108.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -d '{"username":admin@netapp.com,"password":"Netapp@123","grant_type":"password"}
> '
+
This API will return a response like the following. You can retrieve the authorization token as shown below.
+
[source,text]
{"expires_in":21600,"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzM2MDIzLCJleHAiOjE2NzI3NTc2MjMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9CJtRpRDY23PokyLg1if67bmgnMcYxdCvBOY-ZUYWzhrWbbY_hqUH4T-114v_pNDsPyNDyWqHaKizThdjjHYHxm56vTz_Vdn4NqjaBDPwN9KAnC6Z88WA1cJ4WRQqj5ykODNDmrv5At_f9HHp0-xVMyHqywZ4nNFalMvAh4xESc5jfoKOZc-IOQdWm4F4LHpMzs4qFzCYthTuSKLYtqSTUrZB81-o-ipvrOqSo1iwIeHXZJJV-UsWun9daNgiYd_wX-4WWJViGEnDzzwOKfUoUoe1Fg3ch--7JFkFl-rrXDOjk1sUMumN3WHV9usp1PgBE5HAcJPrEBm0ValSZcUbiA"}

. Extract the Working Environment ID and the X-Agent-Id using the tenancy/external/resource API.
+
[source,http]
curl -X GET http://10.193.192.202/tenancy/external/resource?account=account-DARKSITE1 -H 'accept: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw'
+
This API will return a response like the following. The value under the "resourceIdentifier" denotes the _WorkingEnvironment Id_ and the value under "agentId" denotes _x-agent-id_.
+
[source,text]
[{"resourceIdentifier":"OnPremWorkingEnvironment-pMtZND0M","resourceType":"ON_PREM","agentId":"vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients","resourceClass":"ON_PREM","name":"CBSFAS8300-01-02","metadata":"{\"clusterUuid\": \"2cb6cb4b-dc07-11ec-9114-d039ea931e09\"}","workspaceIds":["workspace2wKYjTy9"],"agentIds":["vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients"]}]

. Update the BlueXP backup and recovery database with the details of the StorageGRID system associated with the Working Environments. Make sure to enter the Fully Qualified Domain Name of the StorageGRID, as well as the Access-Key and Storage-Key as shown below:
+
[source,http]
curl -X POST 'http://10.193.192.202/account/account-DARKSITE1/providers/cloudmanager_cbs/api/v1/sg/credentials/working-environment/OnPremWorkingEnvironment-pMtZND0M' \
> --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw' \
> --header 'x-agent-id: vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients' \
> -d '
> { "storage-server" : "sr630ip15.rtp.eng.netapp.com:10443", "access-key": "2ZMYOAVAS5E70MCNH9", "secret-password": "uk/6ikd4LjlXQOFnzSzP/T0zR4ZQlG0w1xgWsB" }'

=== Verify BlueXP backup and recovery settings

. Select each ONTAP working environment and click *View Backups* next to the Backup and recovery service in the right-panel.
+
You should be able to see all the backups that have been created for your volumes.

. From the Restore Dashboard, under the Search & Restore section, click *Indexing Settings*.
+
Make sure that the working environments which had Indexed Cataloging enabled previously remain enabled.

. From the Search & Restore page, run a few catalog searches to confirm that the Indexed Catalog restore has been completed successfully.