---
sidebar: sidebar
permalink: reference-backup-cbs-db-in-dark-site.html
keywords: backup database, recover database
summary: When using Cloud Backup in a site without internet access, you'll want to back up critical Cloud Backup files periodically in case you have an issue with the BlueXP Connector host system. This will enable you to deploy a new Connector and restore the critical Cloud Backup data.
---

= Back up and restore Cloud Backup data in a dark site
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When using Cloud Backup in a site without internet access, you'll want to back up critical Cloud Backup files periodically in case you have an issue with the BlueXP Connector host system. This will enable you to deploy a new Connector and restore the critical Cloud Backup data.

When you use Cloud Backup in a SaaS environment where the BlueXP Connector is deployed at your cloud provider, or on your own host system that has internet access, all the important Cloud Backup configuration data is backed up and stored in the cloud. When you're using Cloud Backup in a site with no internet access, also known as a "dark site", this Cloud Backup information is stored only on the local Connector system.

This topic describes how to back up critical Cloud Backup data to your connected StorageGRID system. It also describes how to restore the data onto a new Connector when necessary.

NOTE: You should plan to back up this Cloud Backup data periodically so you'll always have access to the most recent data.

== Back up critical Cloud Backup data

There are 2 types of data that you need to back up:

* Cloud Backup database
* Indexed Catalog files (used for Search & Restore functionality)

No volume data is ever included in the Cloud Backup database or Indexed Catalog files.

=== Back up the Cloud Backup database

The Cloud Backup database contains a listing of all the volumes, backup files, backup policies, and configuration information.

.Steps

. Log into the Connector host system using the appropriate credentials.

. Enter the MySQL container shell by entering the following command:
+
[source,cli]
docker exec -it ds_mysql_1 sh

. In the container shell, deploy the "env".

. You'll need the MySQL DB password, so copy the value of the key "MYSQL_ROOT_PASSWORD".

. Back up the Cloud Backup MySQL DB entering the following command:
+
[source,cli]
mysqldump --user root --password -p cloud_backup --result-file=mysql.dump.cloud_backup.sql

. Copy the MySQL DB backup from the MySQL docker container by entering the following command:
+
[source,cli]
docker cp ds_mysql_1:/mysql.dump.cloud_backup.sql .

. Copy the backup to a secure location in your network. You can use a local StorageGRID system if you are creating ONTAP volume backups to that location.

=== Back up the Indexed Catalog files

The Indexed Catalog is used for Search & Restore functionality. It contains information about every volume and every backup file - making your searches very quick and efficient when restoring volume data.

. On the Connector host system, change the directory to "/tmp".

. Locate the Index Catalog folder. It starts with the string *catalog*.

. Zip the "catalog<_xxxxxx_>" folder by entering the following command:
+
[source,cli]
zip -r catalogxxxxxx.zip catalogxxxxxx

. Copy the zipped backup to a secure location in your network.

== Restore Cloud Backup data to a new Connector

If your on-premises Connector has a catastrophic failure, you'll need to install a new Connector, and then restore the Cloud Backup data to the new Connector.

There are 4 tasks you'll need to perform to return your Cloud Backup system to a working state:

* https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-onprem-no-internet.html[Install a new Connector on a new on-premises Linux host^]
* Restore the Cloud Backup database
* Restore the Indexed Catalog files
* Rediscover all of your on-prem ONTAP systems to the BlueXP UI

Once you verify that your system is back in a working order, we recommend that you create new backup files.

=== Restore the Cloud Backup database

. After installing the new Connector, log into the Connector host system using the appropriate credentials.

. Copy the MySQL backup from the secure location to the new Connector host.

. Copy the backup into the MySQL docker container using the following command:
+
[source,cli]
docker cp mysql.dump.cloud_backup.sql ds_mysql_1:/.

. Enter the MySQL container shell using the following command:
+
[source,cli]
docker exec -it ds_mysql_1 sh

. In the container shell, deploy the "env".

. You'll need the MySQL DB password, so copy the value of the key "MYSQL_ROOT_PASSWORD".

. Restore the Cloud Backup MySQL DB using the following command:
[source,cli]
mysql -u root -p cloud_backup < mysql.dump.cloud_backup.sql

. Verify that the Cloud Backup MySQL DB has been restored correctly using the following SQL commands:
+
[source,cli]
# mysql -u root -p cloud_backup
+
Enter the password.
+
[source,cli]
mysql> show tables;
mysql> select * from volume; 
+
Check if the volumes that are shown are the same as those that existed in your original environment.

=== Restore the Indexed Catalog files

. Copy the Indexed Catalog backup zip file from the secure location to the new Connector host in the "/tmp" folder.

. Unzip the "catalogxxxxxx.zip" file using the following command:
[source,cli]
unzip catalogxxxxxx.zip

. Run the *ls* command to make sure that the folder "catalogxxxxxx" has been created with the subfolders "changes" and "snapshots" underneath.

=== Discover your clusters and verify Cloud Backup settings

. https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html#discovering-clusters-from-the-canvas-page[Discover all the on-prem ONTAP working environments^] that were available in your previous environment.

. Optionally, https://docs.netapp.com/us-en/cloud-manager-storagegrid/task-discover-storagegrid.html[Discover your StorageGRID systems^]. 

. Select each ONTAP working environment and click *View Backups* next to the Backup and recovery service in the right-panel.
+
You should be able to see all the backups that have been created for your volumes.

. From the Restore Dashboard, under the Search & Restore section, click *Indexing Settings*.
+
Make sure that the working environments which had Indexed Cataloging enabled in previously remain enabled.

. From the Search & Restore page, run a few catalog searches to confirm that the Indexed Catalog restore has been completed successfully.
