---
sidebar: sidebar
permalink: reference-limitations.html
keywords: limitations, backup, restore, backup and recovery
summary: Known limitations identify functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.
---

= Known limitations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known limitations identify functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

== Backup and restore limitations for ONTAP volumes

=== Replication limitations

* You can select only one FlexGroup volume at a time for replication. You'll need to activate backups separately for each FlexGroup volume.
+
There is no limitation for FlexVol volumes - you can select all FlexVol volumes in your working environment and assign the same backup policies.

* The following functionality is supported in the https://docs.netapp.com/us-en/bluexp-replication/index.html[BlueXP replication service], but not when using the replication feature of BlueXP backup and recovery:

** There is no support for a cascade configuration where replication occurs from volume A to volume B and from volume B to volume C. Support includes replication from volume A to volume B.
** There is no support for replicating data to and from FSx for ONTAP systems.
** There is no support for creating a one-time replication of a volume.
//, and replication from volume A to multiple destinations

* When creating replications from on-premises ONTAP systems, if the ONTAP version on the target Cloud Volumes ONTAP system is 9.8, 9.9, or 9.11, only mirror-vault policies are allowed.

=== Backup-to-object limitations

* When you create or edit a backup policy when no volumes are assigned to the policy, the number of retained backups can be a maximum of 1018. After you assign volumes to the policy, you can edit the policy to create up to 4000 backups.

* When backing up data protection (DP) volumes:
** Relationships with the SnapMirror labels `app_consistent` and `all_source_snapshot` won't be backed up to cloud.
** If you create local copies of Snapshots on the SnapMirror destination volume (irrespective of the SnapMirror labels used) these Snapshots will not be moved to the cloud as backups. At this time you'll need to create a Snapshot policy with the desired labels to the source DP volume in order for BlueXP backup and recovery to back them up.

* FlexGroup volume backups can't be moved to archival storage.

* FlexGroup volume backups can use DataLock and Ransomware protection if the cluster is running ONTAP 9.13.1 or greater.
//can't use DataLock and Ransomware protection.

* SVM-DR volume backup is supported with the following restrictions:
** Backups are supported from the ONTAP secondary only.
** The Snapshot policy applied to the volume must be one of the policies recognized by BlueXP backup and recovery, including daily, weekly, monthly, etc. The default "sm_created" policy (used for *Mirror All Snapshots*) is not recognized and the DP volume will not be shown in the list of volumes that can be backed up.

//* MetroCluster (MCC) backup is supported from ONTAP secondary only: MCC > SnapMirror > ONTAP > Cloud Backup > object storage.
* MetroCluster support:
** When you use ONTAP 9.12.1 GA or greater, backup is supported when connected to the primary system. The entire backup configuration is transferred to the secondary system so that backups to the cloud continue automatically after switchover. You don't need to set up backup on the secondary system (in fact, you are restricted from doing so).
** When you use ONTAP 9.12.0 and earlier, backup is supported only from the ONTAP secondary system.
** Backups of FlexGroup volumes are not supported at this time.

* Ad-hoc volume backup using the *Backup Now* button isn't supported on data protection volumes.

* SM-BC configurations are not supported.

* ONTAP doesn't support fan-out of SnapMirror relationships from a single volume to multiple object stores; therefore, this configuration is not supported by BlueXP backup and recovery.

* WORM/Compliance mode on an object store is supported on Amazon S3, Azure, and StorageGRID at this time. This is known as the DataLock feature, and it must be managed by using BlueXP backup and recovery settings, not by using the cloud provider interface.

=== Restore limitations

These limitations apply to both the Search & Restore and the Browse & Restore methods of restoring files and folders; unless called out specifically.

* Browse & Restore can restore up to 100 individual files at a time.

* Search & Restore can restore 1 file at a time.

* When using ONTAP 9.13.0 or greater, Browse & Restore and Search & Restore can restore a folder along with all files and sub-folders within it.
+
When using a version of ONTAP greater than 9.11.1 but before 9.13.0, the restore operation can restore only the selected folder and the files in that folder - no sub-folders, or files in sub-folders, are restored.
+
When using a version of ONTAP before 9.11.1, folder restore is not supported.

* Directory/folder restore is supported for data that resides in archival storage only when the cluster is running ONTAP 9.13.1 and greater. 

* Directory/folder restore is supported for data that is protected using DataLock only when the cluster is running ONTAP 9.13.1 and greater. 

* Directory/folder restore is not currently supported on FlexGroup volume backups. 

* Directory/folder restore is not currently supported from replications and/or local snapshots.

* Restoring from FlexGroup volumes to FlexVol volumes, or FlexVol volumes to FlexGroup volumes is not supported.

* The file being restored must be using the same language as the language on the destination volume. You will receive an error message if the languages are not the same.

* The _High_ restore priority is not supported when restoring data from Azure archival storage to StorageGRID systems.

* Quick restore limitations:
** The destination location must be a Cloud Volumes ONTAP system using ONTAP 9.13.0 or greater.
** It is not supported with backups located in archived storage.
** FlexGroup volumes are supported only if the source system from which the cloud backup was created was running ONTAP 9.12.1 or greater. 
** SnapLock volumes are supported only if the source system from which the cloud backup was created was running ONTAP 9.11.0 or greater. 

=== Limitations when using RHEL 8+ with Podman

==== Single-file restore is not supported

The Browse & Restore functionality for single-file restore and directory restore is not supported when using Podman. All other types of restore operations are supported when using Podman, so you can restore your data using these other methods until this issue is resolved:

* Restore the files or folders from a replicated volume, if a replicated volume exists.
* Restore the files or folders from a cloud backup using the Search & Restore feature.
* Restore the volume from a cloud backup using Browse & Restore and then access the files or folders that you need.
 
==== Ransomware scanning of your cloud backups is not supported
 
Scanning cloud backups for ransomware is not supported when using the Podman engine. If you are using the DataLock & Ransomware feature for your cloud backups, you'll need to disable ransomware scans. link:task-manage-backup-settings-ontap.html#enable-or-disable-ransomware-scans[See how to disable ransomware scanning].

