---
sidebar: sidebar
permalink: task-add-host-discover-oracle-databases.html
keywords: Cloud Manager, BlueXP, SnapCenter Plug-in for Oracle, Oracle, database, host, deploy, add host, discover
summary:  Deploy the SnapCenter Plug-in for Oracle on each of the Oracle database hosts.
---

= Add host and discover Oracle databases
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should add the host and discover the databases on the host to assign policies and create backups. You can either add the host manually when you have already deployed the plug-in or add the host using SSH.

== Prerequisites

Before adding the host, you should ensure that the prerequisites are met.

* You should have created the working environment and the Connector.
* Ensure that the Connector has connectivity to the working environment and Oracle database hosts.
* Ensure that the BlueXP user has the “Account Admin” role.
* Ensure that JAVA 11 is installed on each of the Oracle database hosts and the JAVA_HOME variable is set appropriately.
* You should have created the non-root user. For information, refer to <<Create a non-root user>>.
* If SSH key based authentication is not enabled on the Oracle host and you want to add the host manually, you should manually deploy the plug-in. For information, refer to <<Manual deployment of SnapCenter Plug-in for Oracle>>.

=== Create a non-root user

You should create a non-root user to deploy the plug-in.

*Steps*

. Create the user account, private key pair, and assign the permissions. For information, refer to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/managing-users.html#create-user-account[Create a user account^].
. Add the following lines to the _/etc/sudoers_ file by using the visudo Linux utility.
+
[subs=+quotes]
----
Cmnd_Alias HPPLCMD = sha224:mRCkEJ15odTGtW3PH9YlRbTkZghwPko8M1WcYQ== /home/_SUDO_USER_/.sc_netapp/snapcenter_linux_host_plugin_scs.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:ir9Km4ctOavgJ60Fbbmmpx7a6dJ68FiQIXHdyw== /home/_SUDO_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:HQukzZNynG+nugzScFnHuccouOL75sZ1RRDaNg== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:GHupVXP5krvae06pNNxjvhZcM5VfRkOvc86Ibw== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR = sha224:LZCipEIopaFpW92j+rvubQJlhX6ousO7Jf5Sxg== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_SUDO_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD, /usr/bin/sed, /usr/bin/cp, /usr/bin/systemctl, /usr/bin/keytool, /usr/bin/sh, /tmp/snapcenter_linux_host_plugin_scs.bin, /tmp/oracle_plugin_install.sh, /usr/bin/nohup
Defaults:_SUDO_USER_ !visiblepw
Defaults:_SUDO_USER_ !requiretty
----
+
_SUDO_USER_ is the name of the non-root user that you created.

=== Manual deployment of SnapCenter Plug-in for Oracle

You should deploy the SnapCenter Plug-in for Oracle on each of the Oracle database hosts.

NOTE: Ensure that JAVA 11 is installed on each of the Oracle database hosts and the JAVA_HOME variable is set appropriately.

*Steps*

. Log into the Connector VM.
. Download the SnapCenter Linux host plug-in binary.
`sudo docker exec -it cloudmanager_scs_cloud curl -X GET 'http://127.0.0.1/deploy/downloadLinuxPlugin'`
. Obtain the base mount path.
`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`
. Obtain the binary path of the downloaded plug-in.
`sudo ls <base_mount_path> $(sudo docker ps|grep -Po "cloudmanager_scs_cloud:.*? "|sed -e 's/ *$//'|cut -f2 -d":")/sc-linux-host-plugin/snapcenter_linux_host_plugin_scs.bin`
. Copy _snapcenter_linux_host_plugin_scs.bin_ to each of the Oracle database hosts either using scp or other alternate methods.
. On the Oracle database host, run the following command to enable execute permissions for the binary.
`chmod +x snapcenter_linux_host_plugin_scs.bin`
. Deploy the Oracle plug-in as a sudo non-root user.
`./snapcenter_linux_host_plugin_scs.bin -i silent`
. Copy _certificate.p12_ from _<base_mount_path>/client/certificate/_ path of the Connector VM to _/var/opt/snapcenter/spl/etc/_ on the plug-in host.
+
.. Navigate to _/var/opt/snapcenter/spl/etc_ and execute the keytool command to import the certificate.
`keytool -v -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore keystore.jks -deststoretype JKS -srcstorepass snapcenter -deststorepass snapcenter -srcalias agentcert -destalias agentcert -noprompt`
.. Restart SPL: `systemctl restart spl`

== Add host

You should add the host and discover the Oracle databases.

*Steps*

. In the BlueXP UI, click *Protection* > *Backup and recovery* > *Applications*.
. Click Discover Applications.
. Select *Cloud Native* and click *Next*.
+
A service account with _SnapCenter System_ role is created to perform scheduled data protection operations for all the users in this account.
+
* Click *Account* > *Manage Account* > *Members* to view the service account.
+
NOTE: The service account (_SnapCenter-account-<accountid>_) is used for running the scheduled backup operations. You should never delete the service account.

. In the Add Host page, perform one of the following:
+
|===
| If you... | Do this...

a|
Have manually deployed the plug-in

a|
. Select *Manual*.
. Specify the  FQDN or IP address of the host where the plug-in is deployed.
. Specify the plug-in port.
+
Default port is 8145.
. Select the Connector.
. Select the check box to confirm that the plug-in is installed on the host
. Click *Discover Applications*.
a|
Want to deploy the plug-in using SSH
a|
. Select *Using SSH*.
. Specify the  FQDN or IP address of the host where you want to install the plug-in.
. Specify the username (sudo non-root user) using which the plug-in package will be copied to the host.
. Specify the SSH and plug-in port.
+
Default SSH port is 22 and the plug-in port is 8145.
+
You can close the SSH port on the application host after installing the plug-in. The SSH port is not required for any other plug-in operations.
. Select the Connector.
. (Optional) If key less authentication is not enabled between the Connector and the host, you should specify the SSH private key that will be used to communicate with the host.
+
NOTE: The SSH private key is not stored any where in the application and will not used for any other operations.
. Click *Next*.
|===
+
* Displays all the databases on the host. If OS authentication is disabled for the database, you should configure database authentication by clicking *Configure*. For more information, refer to <<Configure Oracle database credentials>>.
+
* Click *Settings* and select *Hosts* to view all the database hosts. Click *Remove* to remove a database host.
+
* Click *Settings* and select *Policies* to view the pre-canned policies. Review the pre-canned policies and if you want you can either edit them to meet your requirement or create a new policy.

== Configure Oracle database credentials

You should configure credentials that are used to perform data protection operations on Oracle databases.

*Steps*

. If OS authentication is disabled for the database, you should configure database authentication by clicking *Configure*.
. Specify the username, password, and the port details either in the Database Settings or ASM Settings section.
+
The Oracle user should have sysdba privileges and ASM user should have sysasm privileges.
. Click *Configure*.