---
sidebar: sidebar
permalink: task-register-snapCenter-plug-in-for-vmware-vsphere.html
keywords: register, registration, SnapCenter Plug-in for VMware vSphere
summary: Register SnapCenter Plug-in for VMware vSphere host in BlueXP.
---

= Register SnapCenter Plug-in for VMware vSphere host
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should register the SnapCenter Plug-in for VMware vSphere host in BlueXP for the datastores and virtual machines to be displayed. Only a user with administrative access can register the SnapCenter Plug-in for VMware vSphere host.

NOTE: You can register multiple SnapCenter Plug-in for VMware vSphere hosts in BlueXP. However, once registered, you cannot remove the SnapCenter Plug-in for VMware vSphere host.

.Steps

. In BlueXP UI, click *Protection* > *Backup and recovery* > *Virtual Machines*.
. From the *Settings* drop-down, click *SnapCenter Plug-in for VMware vSphere*.
. Click *Register SnapCenter Plug-in for VMware vSphere*.
. Specify the following details:
.. In the SnapCenter Plug-in for VMware vSphere field, specify the FQDN or IP address of the SnapCenter Plug-in for VMware vSphere host.
.. In the Port field, specify the port number on which the SnapCenter Plug-in for VMware vSphere host is running.
+
You should ensure that communication is open between on-premises SnapCenter Plug-in for VMware vSphere host which is running on the default 8144 port and BlueXP Connector instance which could be either running in any cloud providers (Amazon Web Services, Microsoft Azure, Google Cloud Platform) or on-premises.
.. In the Username and Password field, specify the credentials of the user with the administrator role.
. Click *Register*.

*After you finish*

Click *Backup and recovery* > *Virtual Machines* to view all the datastores and virtual machines that are protected using the registered SnapCenter Plug-in for VMware vSphere host.
