---
sidebar: sidebar
permalink: task-deploy-snapcenter-plugin-for-sap-hana.html
keywords: Cloud Manager, BlueXP, SnapCenter Plug-in for SAP HANA, SAP HANA, database, host, deploy
summary:  Deploy the SnapCenter Plug-in for SAP HNAN on each of the SAP HANA database hosts.
---

= Deploy SnapCenter Plug-in for SAP HANA
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should deploy the SnapCenter Plug-in for SAP HANA on each of the SAP HANA database hosts. Depending on whether the SAP HANA host has an SSH key based authentication enabled, you can follow one of the methods to deploy the plug-in.

NOTE: Ensure that either Java 11 (64-bit) Oracle Java or OpenJDK is installed on each of the SAP HANA database hosts.

== Configure a non-root user

You should create a non-root user to deploy the plug-in.

*Steps*

. Log into the Connector VM.
. Download the Linux host plug-in binary.
`sudo docker exec -it cloudmanager_scs_cloud curl -X GET 'http://127.0.0.1/deploy/downloadLinuxPlugin'``
. Obtain the base mount path.
`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`
. Copy lines 1 to 16 from the `oracle_checksum_scs.txt`` file located at `base_mount_path/version/sc-linux-host-plugin/`
. Log into the SAP HANA database host and perform the following steps:
.. Create the non-root user account, private key pair, and assign the permissions.
.. Paste the lines that you copied in step 4 to the `/etc/sudoers` file by using the visudo Linux utility.
+
In the above lines, replace the <LINUXUSER> with the non-root user that you created and save in the visuod utility.

== Deploy the plug-in using SSH key based authentication

If SSH key based authentication is enabled on the HANA host, you can perform the following steps to deploy the plug-in. Before performing the steps, ensure that the SSH connection to the Connector is enabled.

*Steps*

. Log into the Connector VM.

. Obtain the base mount path.
`# sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`

. Deploy the plug-in.
`# sudo <base_mount_path>/scripts/hana_plugin_copy_and_install.sh --host <host_name> --sshkey <ssh_key_file> --username <user_name> --port <ssh_port> --pluginport <plugin_port> --installdir <install_dir>`

* host_name is the name of the HANA host, and this is a mandatory parameter.
* ssh_key_file is the SSH key used to connect to the HANA host, and this is a mandatory parameter.
* user_name: User with SSH privileges on the HANA host, and this is an optional parameter. Default value is azureuser.
* ssh_port: SSH port on the HANA host, and this is an optional parameter. Default value is 22.
* plugin_port: Port used by the plug-in, and this is an optional parameter. Default value is 8145.
* install_dir: Directory where the plug-in will be deployed, and this is an optional parameter. Default value is /opt.

== Deploy the plug-in manually

If SSH key based authentication is not enabled on the HANA host, you should perform the following manual steps to deploy the plug-in.

*Steps*

. Log into the Connector VM.

. Download the Linux host plug-in binary.
`# sudo docker exec -it cloudmanager_scs_cloud curl -X GET 'http://127.0.0.1/deploy/downloadLinuxPlugin'`

. Obtain the base mount path.
`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`

. Obtain the binary path of the downloaded plug-in.
`sudo ls <base_mount_path> $(sudo docker ps|grep -Po "cloudmanager_scs_cloud:.*? "|sed -e 's/ *$//'|cut -f2 -d":")/sc-linux-host-plugin/snapcenter_linux_host_plugin_scs.bin`

. Copy `snapcenter_linux_host_plugin_scs.bin` to each of the SAP HANA database hosts either using scp or other alternate methods.

. On the SAP HANA database host, run the following command to enable execute permissions for the binary.
`chmod +x snapcenter_linux_host_plugin_scs.bin`

. Deploy the SAP HANA plug-in as a sudo non-root user.
`./snapcenter_linux_host_plugin_scs.bin -i silent -DSPL_USER=<non-root-user>`

. Copy `certificate.p12` from `<base_mount_path>/client/certificate/` path of the Connector VM to `/var/opt/snapcenter/spl/etc/` on the plug-in host.

.. Navigate to `/var/opt/snapcenter/spl/etc` and execute the keytool command to import the certificate.
`keytool -v -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore keystore.jks -deststoretype JKS -srcstorepass snapcenter -deststorepass snapcenter -srcalias agentcert -destalias agentcert -noprompt`
.. Restart SPL: `systemctl restart spl`