---
sidebar: sidebar
permalink: task-register-snapCenter-plug-in-for-vmware-vsphere.html
keywords: register, registration, SnapCenter Plug-in for VMware vSphere
summary: Register SnapCenter Plug-in for VMware vSphere in BlueXP.
---

= Register SnapCenter Plug-in for VMware vSphere
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should register the SnapCenter Plug-in for VMware vSphere in BlueXP for the datastores and virtual machines to be displayed in BlueXP. Only a user with administrative access can register the SnapCenter Plug-in for VMware vSphere.

NOTE: You can register multiple SnapCenter Plug-in for VMware vSphere. However, once registered, you cannot remove the SnapCenter Plug-in for VMware vSphere.

.Steps

. In BlueXP UI, click *Protection* > *Backup and recovery* > *Virtual Machines*.
. From the *Settings* drop-down, click *SnapCenter Plug-in for VMware vSphere*.
. Click *Register SnapCenter Plug-in for VMware vSphere*.
. Specify the following details:
.. In the SnapCenter Plug-in for VMware vSphere field, specify the FQDN or IP address of the SnapCenter Plug-in for VMware vSphere.
.. In the Port field, specify the port number on which the SnapCenter Plug-in for VMware vSphere is running.
+
You should ensure that the port is open for communication to happen between SnapCenter Plug-in for VMware vSphere and Cloud Backup for Virtual Machines.
.. In the Username and Password field, specify the credentials of the user with the administrator role.
. Click *Register*.

*After you finish*

Click *Backup & Restore > Virtual Machines* to view all the datastores and virtual machines that are eligible for protection using the registered SnapCenter Plug-in for VMware vSphere.
