---
sidebar: sidebar
permalink: task-add-host-discover-oracle-databases.html
keywords: Cloud Manager, BlueXP, SnapCenter Plug-in for Oracle, Oracle, database, host, deploy, add host, discover
summary:  Deploy the SnapCenter Plug-in for Oracle on each of the Oracle database hosts.
---

= Deploy SnapCenter Plug-in for Oracle and add database hosts
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should deploy the SnapCenter Plug-in for Oracle on each of the Oracle database hosts, add the database hosts, and discover the databases on the host to assign policies and create backups.

* If SSH is enabled for the database host, you can deploy the plug-in using one of the methods:
** Deploy the plug-in and add host the UI using SSH option. <<Deploy the plug-in and add host from UI using SSH option, Learn more>>.
** Deploy the plug-in using script and add host from the UI using manual option. <<Deploy the plug-in using script and add host from UI using manual option, Learn more>>.
* If SSH is disabled, deploy the plug-in manually and add host from the UI using manual option. <<Deploy the plug-in manually and add host from UI using manual option, Learn more>>.

== Prerequisites

Before adding the host, you should ensure that the prerequisites are met.

* You should have created the working environment and the Connector.
* Ensure that the Connector has connectivity to the working environment and Oracle database hosts.
* Ensure that the BlueXP user has the “Account Admin” role.
* Ensure that either Java 11 (64-bit) Oracle Java or OpenJDK is installed on each of the Oracle database hosts and the JAVA_HOME variable is set appropriately.
* Ensure that the Connector has the communication enabled to the SSH port (default: 22) if SSH based deployment is used.
* Ensure that the Connector has the communication enabled to plug-in port (default: 8145) for the operations to work.

NOTE: If the connectivity from BlueXP Connector host to application host fails, refer https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Cloud_Backup_Application_Failed_to_validate_connectivity_from_BlueXP_connector_host_to_application_database_host[knowledge base article^] for information.

== Deploy the plug-in and add host from UI using SSH option

. In the BlueXP UI, click *Protection* > *Backup and recovery* > *Applications*.
. Click *Discover Applications*.
. Select *Cloud Native* and click *Next*.
+
A service account with _SnapCenter System_ role is created to perform scheduled data protection operations for all the users in this account.
+
* Click *Account* > *Manage Account* > *Members* to view the service account.
+
NOTE: The service account (_SnapCenter-account-<accountid>_) is used for running the scheduled backup operations. You should never delete the service account.
. Select Oracle as the application type.
. In the Host details page, perform the following:
.. Select *Using SSH*.
.. Specify the  FQDN or IP address of the host where you want to install the plug-in.
.. Specify the sudo SnapCenter user using which the plug-in package will be copied to the host.
.. Specify the SSH and plug-in port.
+
Default SSH port is 22 and the plug-in port is 8145.
+
You can close the SSH port on the application host after installing the plug-in. The SSH port is not required for any other plug-in operations.
.. Select the Connector.
.. (Optional) If key less authentication is not enabled between the Connector and the host, you should specify the SSH private key that will be used to communicate with the host.
+
NOTE: The SSH private key is not stored anywhere in the application and will not be used for any other operations.
.. Click *Next*.
. In the Configuration page, perform the following:
.. Configure sudo for the SnapCenter user by copying the text to the _/etc/sudoer.d/snapcenter_ file by using the visudo Linux utility.
.. Select the checkbox and click *Next*.
. Review the details and click *Discover Applications*.
+
* Displays all the databases on the host. If OS authentication is disabled for the database, you should configure database authentication by clicking *Configure*. For more information, refer to <<Configure Oracle database credentials>>.
+
* Click *Settings* and select *Hosts* to view all the hosts. Click *Remove* to remove a database host.
+
NOTE: The filter to view a specific host does not work. When you specify a host name in the filter, all the hosts are displayed.
+
* Click *Settings* and select *Policies* to view the pre-canned policies. Review the pre-canned policies and if you want you can either edit them to meet your requirement or create a new policy.

== Deploy the plug-in using script and add host from UI using manual option

If SSH key based authentication is enabled on the Oracle host for the SnapCenter user, you can perform the following steps to deploy the plug-in. Before performing the steps, ensure that the SSH connection to the Connector is enabled.

*Steps*

. Log into the Connector VM.
. Obtain the base mount path.
`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`
. Deploy the plug-in using the script provided in the Connector.
`linux_plugin_copy_and_install.sh --host <plugin_host> --username <host_user_name> --sshkey <host_ssh_key> --pluginport <plugin_port> --installdir <plugin_install_path> --sshport <host_ssh_port>`

* plugin_host is the name of the Oracle host and this is a mandatory parameter.
* host_user_name: SnapCenter user with SSH privileges on the Oracle host.
* host_ssh_key is the SSH key of the SnapCenter user and used to connect to the Oracle host. This is a mandatory parameter.
* plugin_port: Port used by the plug-in and this is an optional parameter. Default value is 8145
* plugin_install_path: Directory where the plug-in will be deployed and this is an optional parameter. Default value is /opt.
* host_ssh_port: SSH port on the Oracle host and this is an optional parameter. Default value is 22
+
For example:
`sudo /var/lib/docker/volumes/service-manager-2_cloudmanager_scs_cloud_volume/_data/scripts/oracle_plugin_copy_and_install.sh --host xxx.xx.x.x --sshkey /keys/netapp-ssh.ppk`
. In the BlueXP UI, click *Protection* > *Backup and recovery* > *Applications*.
. Click *Discover Applications*.
. Select *Cloud Native* and click *Next*.
+
A service account with _SnapCenter System_ role is created to perform scheduled data protection operations for all the users in this account.
+
* Click *Account* > *Manage Account* > *Members* to view the service account.
+
NOTE: The service account (_SnapCenter-account-<accountid>_) is used for running the scheduled backup operations. You should never delete the service account.

. Select Oracle as the application type.
. In the Host details page, perform the following:
.. Select *Manual*.
.. Specify the  FQDN or IP address of the host where the plug-in is deployed.
+
Ensure that using the FQDN or IP address, the Connector can communicate with the database host.
.. Specify the plug-in port.
+
Default port is 8145.
.. Specify the sudo SnapCenter user using which the plug-in package will be copied to the host.
.. Select the Connector.
.. Select the check box to confirm that the plug-in is installed on the host.
.. Click *Next*.
. In the Configuration page, perform the following:
.. Configure sudo for the SnapCenter user by copying the text to the _/etc/sudoer.d/snapcenter_ file by using the visudo Linux utility.
.. Select the checkbox and click *Next*.
. Review the details and click *Discover Applications*.
+
* Displays all the databases on the host. If OS authentication is disabled for the database, you should configure database authentication by clicking *Configure*. For more information, refer to <<Configure Oracle database credentials>>.
+
* Click *Settings* and select *Hosts* to view all the hosts. Click *Remove* to remove a database host.
+
NOTE: The filter to view a specific host does not work. When you specify a host name in the filter, all the hosts are displayed.
+
* Click *Settings* and select *Policies* to view the pre-canned policies. Review the pre-canned policies and if you want you can either edit them to meet your requirement or create a new policy.

== Deploy the plug-in manually and add host from UI using manual option

If SSH key based authentication is not enabled on the Oracle database host, you should perform the following manual steps to deploy the plug-in and then add the host from UI using manual option.

*Steps*

. Log into the Connector VM.
. Download the SnapCenter Linux host plug-in binary.
`sudo docker exec -it cloudmanager_scs_cloud curl -X GET 'http://127.0.0.1/deploy/downloadLinuxPlugin'`
. Obtain the base mount path.
`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`
. Obtain the binary path of the downloaded plug-in.
`sudo ls <base_mount_path> $(sudo docker ps|grep -Po "cloudmanager_scs_cloud:.*? "|sed -e 's/ *$//'|cut -f2 -d":")/sc-linux-host-plugin/snapcenter_linux_host_plugin_scs.bin`
. Copy _snapcenter_linux_host_plugin_scs.bin_ to each of the Oracle database hosts either using scp or other alternate methods.
+
The _snapcenter_linux_host_plugin_scs.bin_ should be copied to a location that is accessible by the SnapCenter user.
. Log into the Oracle database host using the SnapCenter user account and run the following command to enable execute permissions for the binary.
`chmod +x snapcenter_linux_host_plugin_scs.bin`
. Deploy the Oracle plug-in as a sudo SnapCenter user.
`./snapcenter_linux_host_plugin_scs.bin -i silent -DSPL_USER=<snapcenter-user>`
. Copy _certificate.p12_ from _<base_mount_path>/client/certificate/_ path of the Connector VM to _/var/opt/snapcenter/spl/etc/_ on the plug-in host.
. Navigate to _/var/opt/snapcenter/spl/etc_ and execute the keytool command to import the certificate.
`keytool -v -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore keystore.jks -deststoretype JKS -srcstorepass snapcenter -deststorepass snapcenter -srcalias agentcert -destalias agentcert -noprompt`
. Restart SPL: `systemctl restart spl`
. Validate that the plug-in is reachable from the Connector by running the below command from the Connector.
`docker exec -it cloudmanager_scs_cloud curl -ik \https://<FQDN or IP of the plug-in host>:<plug-in port>/getVersion --cert /config/client/certificate/certificate.pem --key /config/client/certificate/key.pem`
. In the BlueXP UI, click *Protection* > *Backup and recovery* > *Applications*.
. Click *Discover Applications*.
. Select *Cloud Native* and click *Next*.
+
A service account with _SnapCenter System_ role is created to perform scheduled data protection operations for all the users in this account.
+
* Click *Account* > *Manage Account* > *Members* to view the service account.
+
NOTE: The service account (_SnapCenter-account-<accountid>_) is used for running the scheduled backup operations. You should never delete the service account.

. Select Oracle as the application type.
. In the Host details page, perform the following:
.. Select *Manual*.
.. Specify the  FQDN or IP address of the host where the plug-in is deployed.
+
Ensure that using the FQDN or IP address, the Connector can communicate with the database host.
.. Specify the plug-in port.
+
Default port is 8145.
.. Specify the sudo SnapCenter user using which the plug-in package will be copied to the host.
.. Select the Connector.
.. Select the check box to confirm that the plug-in is installed on the host
.. Click *Next*.
. In the Configuration page, perform the following:
.. Configure sudo for the SnapCenter user by copying the text to the _/etc/sudoer.d/snapcenter_ file by using the visudo Linux utility.
.. Select the checkbox and click *Next*.
. Review the details and click *Discover Applications*.
+
* Displays all the databases on the host. If OS authentication is disabled for the database, you should configure database authentication by clicking *Configure*. For more information, refer to <<Configure Oracle database credentials>>.
+
* Click *Settings* and select *Hosts* to view all the hosts. Click *Remove* to remove a database host.
+
NOTE: The filter to view a specific host does not work. When you specify a host name in the filter, all the hosts are displayed.
+
* Click *Settings* and select *Policies* to view the pre-canned policies. Review the pre-canned policies and if you want you can either edit them to meet your requirement or create a new policy.

== Configure Oracle database credentials

You should configure credentials that are used to perform data protection operations on Oracle databases.

*Steps*

. If OS authentication is disabled for the database, you should configure database authentication by clicking *Configure*.
. Specify the username, password, and the port details.
+
If the database is residing on ASM, you should also configure the ASM settings.
+
The Oracle user should have sysdba privileges and ASM user should have sysasm privileges.
. Click *Configure*.