---
sidebar: sidebar
permalink: task-deploy-snapcenter-plugin-for-oracle.html
keywords: Cloud Manager, BlueXP, SnapCenter Plug-in for Oracle, Oracle, database, host, deploy
summary:  Deploy the SnapCenter Plug-in for Oracle on each of the Oracle database hosts.
---

= Deploy SnapCenter Plug-in for Oracle
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should deploy the SnapCenter Plug-in for Oracle on each of the Oracle database hosts. Depending on whether the Oracle host has SSH key based authentication enabled, you can follow one of the methods to deploy the plug-in.

NOTE: Ensure that JAVA 11 is installed on each of the Oracle database hosts and the JAVA_HOME variable is set appropriately.

== Plug-in deployment using SSH key based authentication

If SSH key based authentication is enabled on the Oracle host, you can perform the following steps to deploy the plug-in. Before performing the steps, ensure that the SSH connection to the Connector is enabled.

. Log into the Connector VM as non root user.
. Obtain the base mount path.
`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`
. Deploy the plug-in.
+
`sudo <base_mount_path>/scripts/oracle_plugin_copy_and_install.sh --host <host_name> --sshkey <ssh_key_file> --username <user_name> --port <ssh_port> --pluginport <plugin_port> --installdir <install_dir>`

* host_name is the name of the Oracle host and this is a mandatory parameter.
* ssh_key_file is SSH key used to connect to the Oracle host and this is a mandatory parameter.
* user_name: User with SSH privileges on the Oracle host and this is an optional parameter. Default value is ec2-user.
* ssh_port: SSH port on the Oracle host and this is an optional parameter. Default value is 22
* plugin_port: Port used by the plug-in and this is an optional parameter. Default value is 8145
* install_dir: Directory where the plug-in will be deployed and this is an optional parameter. Default value is /opt.

For example: `sudo /var/lib/docker/volumes/service-manager-2_cloudmanager_scs_cloud_volume/_data/scripts/oracle_plugin_copy_and_install.sh --host xxx.xx.x.x  --sshkey /keys/netapp-ssh.ppk`

== Manual deployment of the plug-in

If SSH key based authentication is not enabled on the Oracle host, you should perform the following manual steps to deploy the plug-in.

. Log into the Connector VM.
. Download the SnapCenter Linux host plug-in binary.
`sudo docker exec -it cloudmanager_scs_cloud curl -X GET 'http://127.0.0.1/deploy/downloadLinuxPlugin'`
. Obtain the base mount path.
`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`
. Obtain the binary path of the downloaded plug-in.
`sudo ls <base_mount_path> $(sudo docker ps|grep -Po "cloudmanager_scs_cloud:.*? "|sed -e 's/ *$//'|cut -f2 -d":")/sc-linux-host-plugin/snapcenter_linux_host_plugin_scs.bin`
. Copy _snapcenter_linux_host_plugin_scs.bin_ to each of the Oracle database hosts either using scp or other alternate methods.
. On the Oracle database host, run the following command to enable execute permissions for the binary.
`chmod +x snapcenter_linux_host_plugin_scs.bin`
. Deploy the Oracle plug-in as a root user.
`./snapcenter_linux_host_plugin_scs.bin -i silent`
. Copy _certificate.p12_ from _<base_mount_path>/client/certificate/_ path of the Connector VM to _/var/opt/snapcenter/spl/etc/_ on the plug-in host.
+
.. Navigate to _/var/opt/snapcenter/spl/etc_ and execute the keytool command to import the certificate.
`keytool -v -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore keystore.jks -deststoretype JKS -srcstorepass snapcenter -deststorepass snapcenter -srcalias agentcert -destalias agentcert -noprompt`
.. Restart SPL: `systemctl restart spl`