---
sidebar: sidebar
permalink: task-register-snapcenter-server.html
keywords: SnapCenter Server, register
summary: Complete a few steps to register the SnapCenter Server.
---

= Register SnapCenter Server
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

Only a user with SnapCenterAdmin role can register the host on which SnapCenter Server 4.6 or later is running. You can register multiple SnapCenter Server hosts in BlueXP.

*Steps*

. In BlueXP UI, click *Protection* > *Backup and recovery* > *Applications*.
. From the *Settings* drop-down, click *SnapCenter Servers*.
. Click *Register SnapCenter Server*.
. Specify the following details:
.. In the SnapCenter Server field, specify the FQDN or IP address of the SnapCenter Server host.
.. In the Port field, specify the port number on which the SnapCenter Server host is running.
+
You should ensure that the port is open for communication to happen between SnapCenter Server and BlueXP.
.. In the Tags field, specify a site name, city name, or any custom name with which you want to tag the SnapCenter Server.
+
The tags are comma separated.
.. In the Username and Password field, specify the credentials of the user with SnapCenterAdmin role.
. Select the Connector from the *Connector* drop-down.
. Click *Register*.

*After you finish*

Click *Backup & Restore* > *Applications* to view all the applications that are protected using the registered SnapCenter Server host. By default, the applications are automatically discovered every day midnight.

IMPORTANT: If SVMs are added to SnapCenter using FQDN or IP address, applications running on these SVMs cannot be protected. BlueXP backup and recovery for Applications recognizes only the SVMs that are added by name or the SVMs discovered by SnapCenter that were added as part of the ONTAP cluster.

The supported applications and their configurations are:

*	Oracle database:
** Full backups (data + log) created with at least one daily, weekly, or monthly schedules
** SAN, NFS, VMDK-SAN, VMDK-NFS, and RDM
* Microsoft SQL Server database:
** Standalone, failover cluster instances, and availability groups
** Full backups created with at least one daily, weekly, or monthly schedules
** SAN, VMDK-SAN, VMDK-NFS, and RDM
* SAP HANA database:
** Single Container 1.x
** Multiple Database Container 2.x
** HANA System Replication (HSR)
+
You should have at least one backup on both primary and secondary sites. You can decide to do a pro-active failure or a deferred failover to the secondary.

** Non-data Volumes (NDV) resources such as HANA binaries, HANA archive log volume, HANA shared volume, and so on

The following databases are not displayed:

* Databases that have no backups
* Databases that have only on-demand or hourly policy
* Oracle databases residing on NVMe
