---
sidebar: sidebar
permalink: task-discover-applications.html
keywords: discover, admin role, service account, pre-canned policies
summary:  Discover the applications to assign policies and create backups.
---

= Discover the applications
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

You should discover the databases on the host to assign policies and create backups.

*What you will need*

* You should have created the FSx for ONTAP working environment and the Connector.
* Ensure that the Connector has connectivity to the FSx for ONTAP working environment and Oracle database hosts.
* Ensure that the Cloud Manager user has the “Account Admin” role.
* You should have deployed the SnapCenter Plug-in for Oracle. link:reference-prereq-protect-cloud-native-app-data.html#deploy-snapcenter-plug-in-for-oracle[Learn more].

*Steps*

. In the Cloud Manager UI, click *Backup & Restore* > *Applications*.
. Click Discover Applications.
. Select *Cloud Native* and click *Next*.
+
A service account with _SnapCenter System_ role is created to perform scheduled data protection operations for all the users in this account.
+
* Click *Account* > *Manage Account* > *Members* to view the service account.
+
NOTE: The service account (_SnapCenter-account-<accountid>_) is used for running the scheduled backup operations. You should never delete the service account.

. In the Specify Host Details page, enter the details of the Oracle database host, select the check box to confirm that the plug-in is installed on the host, and click *Discover*.
+
* Displays all the databases on the host. If OS authentication is disabled for the database, you should configure database authentication by clicking *Configure*. For more information, refer to <<Configure Oracle database credentials>>.
+
* Click *Manage Application*, select *Add* to add a new host, *Refresh* to discover new databases, or *Remove* to remove a database host.
+
* Click *Settings* and select *Policies* to view the pre-canned policies. Review the pre-canned policies and if you want you can either edit them to meet your requirement or create a new policy.

== Configure Oracle database credentials

You should configure credentials that are used to perform data protection operations on Oracle databases.

*Steps*

. If OS authentication is disabled for the database, you should configure database authentication by clicking *Configure*.
. Specify the username, password, and the port details either in the Database Settings or ASM Settings section.
+
The Oracle user should have sysdba privileges and ASM user should have sysasm privileges.
. Click *Configure*.

== Create policy

You can create policies if you do not want to edit the pre-canned policies.

*Steps*

. In the Applications page, from the Settings drop-down list, select *Policies*.
. Click *Create policy*.
. Specify a policy name.
. (Optional) Edit the format of the backup name.
. Specify the schedule and retention details.
. Click *Create*.
