---
sidebar: sidebar
permalink: task-deploy-snapcenter-plugin-for-sap-hana.html
keywords: Cloud Manager, BlueXP, SnapCenter Plug-in for SAP HANA, SAP HANA, database, host, deploy
summary:  Deploy the SnapCenter Plug-in for SAP HNAN on each of the SAP HANA database hosts.
---

= Deploy SnapCenter Plug-in for SAP HANA
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should deploy the SnapCenter Plug-in for SAP HANA on each of the SAP HANA database hosts. Depending on whether the SAP HANA host has an SSH key based authentication enabled, you can follow one of the methods to deploy the plug-in.

NOTE: Ensure that JAVA 11 is installed on each of the SAP-HANA database hosts.

== Plug-in for SAP HANA deployment using SSH key based authentication

If SSH key based authentication is enabled on the HANA host, you can perform the following steps to deploy the plug-in. Before performing the steps, ensure that the SSH connection to the Connector is enabled.

*Steps*

. Log into the Connector VM.

. Obtain the base mount path.
`# sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`

. Deploy the plug-in.
`# sudo <base_mount_path>/scripts/hana_plugin_copy_and_install.sh --host <host_name> --sshkey <ssh_key_file> --username <user_name> --port <ssh_port> --pluginport <plugin_port> --installdir <install_dir>`

* host_name is the name of the HANA host and this is a mandatory parameter.
* ssh_key_file is the SSH key used to connect to the HANA host and this is a mandatory parameter.
* user_name: User with SSH privileges on the HANA host and this is an optional parameter. Default value is azureuser.
* ssh_port: SSH port on the HANA host and this is an optional parameter. Default value is 22.
* plugin_port: Port used by the plug-in and this is an optional parameter. Default value is 8145.
* install_dir: Directory where the plug-in will be deployed and this is an optional parameter. Default value is /opt.

For example:
`# sudo /var/lib/docker/volumes/service-manager-2_cloudmanager_scs_cloud_volume/_data/scripts/hana_plugin_copy_and_install.sh --host xxx.xx.x.x --sshkey /keys/netapp-ssh.ppk`

== Manual deployment of the plug-in for SAP HANA

If SSH key based authentication is not enabled on the HANA host, you should perform the following manual steps to deploy the plug-in.

*Steps*

. Log into the Connector VM.

. Run the following command in the Connector VM to download the SnapCenter Linux host plug-in binary.
`# sudo docker exec -it cloudmanager_scs_cloud curl -X GET 'http://127.0.0.1/deploy/downloadLinuxPlugin'``

. Obtain the package directory path.
`$ base_mount_path=`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint | awk '{ print $2 }' | cut -f 2 -d '"'```
`$ package_dir_path=`echo $base_mount_path/$(sudo docker ps|grep -Po "cloudmanager_scs_cloud:.*? "|sed -e 's/ *$//'|cut -f2 -d":")/sc-linux-host-plugin/```

. Run the following command to obtain the binary path of the downloaded plug-in.
`$ sudo ls $package_dir_path/snapcenter_linux_host_plugin_scs.bin``

. (Optional) Obtain the public key.
`$ sudo openssl x509 -pubkey -noout -in $package_dir_path/prod-SnapCenter-Services-Plugin.pem > /tmp/SnapCenter-Services-Plugin-public.pub`
. (Optional) Verify the package signature. 
+
You should see "Verified OK" as the output.
`$ sudo openssl dgst -sha256 -verify /tmp/SnapCenter-Services-Plugin-public.pub -signature $package_dir_path/snapcenter_linux_host_plugin_scs.bin.sig $package_dir_path/snapcenter_linux_host_plugin_scs.bin`
. On the Linux host, create a non-root user (say: scuser), login as non-root user, scp the package and obtain SHA224 checksum.
+
For example, 
`$ scp <cmuser>@<connectorip>:/home/cmuser/snapcenter_linux_host_plugin_scs.bin`
`$ chmod +x ./snapcenter_linux_host_plugin_scs.bin`
`$ openssl dgst -sha224  -binary ./snapcenter_linux_host_plugin_scs.bin | openssl base64`
`mRCkEJ15odTGtW3PH9YlRbTkZghwPko8M1WcYQ==`
+
Similarly, verify sha224 checksum post product installation.
. As a root user run the visudo and update the below paragraph for CBA plug-in side operations.
`Cmnd_Alias HPPLCMD = sha224:mRCkEJ15odTGtW3PH9YlRbTkZghwPko8M1WcYQ== /home/scuser/snapcenter_linux_host_plugin_scs.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias CONFIGCHECKCMD = sha224:HQukzZNynG+nugzScFnHuccouOL75sZ1RRDaNg== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:GHupVXP5krvae06pNNxjvhZcM5VfRkOvc86Ibw== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR = sha224:LZCipEIopaFpW92j+rvubQJlhX6ousO7Jf5Sxg== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
scuser ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults:scuser !visiblepw
Defaults:scuser !requiretty`
. Install the HANA plug-in package by specifying the port and the non-root user as shown below.
`[scuser@scspa2622265001 ~]$ sudo ./snapcenter_linux_host_plugin_scs.bin -i silent -DPORT=8145 -DSPL_USER=scuser`
. Copy the certificate file.
For example,
.. Run the following command: `$ base_mount_path/client/certificate/certificate.p12 to /var/opt/snapcenter/spl/etc/``
.. Navigate to `/var/opt/snapcenter/spl/etc`` 
.. Execute the keytool command to import the certificate.
 `[scuser@scspa2622265001 ~]$ keytool -v -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore keystore.jks -deststoretype JKS -srcstorepass snapcenter -deststorepass snapcenter -srcalias agentcert -destalias agentcert -noprompt``
 .. Restart SPL.
`[scuser@scspa2622265001 ~]$ sudo /opt/NetApp/snapcenter/spl/bin/spl restart``