---
sidebar: sidebar
permalink: task-create-policies-apps.html
keywords: policy, create, pre-canned polices, custom policies, protection policies
summary:  Create your own policies to protect the application.
---

= Create a policy to back up applications with BlueXP backup and recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should create a policy to back up the application data to cloud with BlueXP backup and recovery.

.Before you begin

* If you want to move backups from object store to archival storage, ensure that you are using the required ONTAP version.
** If you are using Amazon Web Services, you should be using ONTAP 9.10.1 or later 
** If you are using Microsoft Azure, you should be using ONTAP 9.10.1 or later 
** If you are using Google Cloud, you should be using ONTAP 9.12.1 or later 
** If you are using StorageGrid, you should be using ONTAP 9.12.1 or later
* You should configure the archive access tier for each cloud provider.

.Steps

. In BlueXP UI, click *Protection* > *Backup and recovery* > *Applications*.
. From the Settings drop-down, click *Policies* > *Create Policy*.
. In the Policy Details section, specify the policy name.
. In the Retention section, select one of the retention type and specify the number of backups to retain.
. Select Primary or Secondary as the backup storage source.
. (Optional) If you want to move backups from object store to archival storage after a certain number of days for cost optimization, select the *Tier Backups to Archival* checkbox.
. Click *Create*.
+
NOTE: You cannot edit or delete a policy, which is associated with an application.
