---
sidebar: sidebar
permalink: task-restore-customplugin-backup.html
keywords: restore, mount application backups, MongoDB, MySQL, PostgreSQL
summary: You can restore SAP HANA database from the cloud to the on-premises SnapCenter Server.
---

= Restore MongoDB, MySQL, and PostgreSQL databases with BlueXP backup and recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can restore MongoDB, MySQL, and PostgreSQL databases to any host with BlueXP backup and recovery.

*Steps*

. In BlueXP UI, click *Protection* > *Backup and recovery* > *Applications*.
. In the *Filter By* field, select the filter *Type* and from the drop-down select *MongoDB*, *MySQL*, or *PostgreSQL*.
. Click *View Details* corresponding to the database that you want to restore and click *Restore*.
. In the Restore options page, specify one of the following:
.. For NAS environment, specify the FQDN or IP address of the host to which the volumes restored from object store are to be exported.
.. For SAN environment, specify the initiators of the host to which LUNs of the volumes restored from object store are to be mapped.
. If the snapshot is in archival storage, select the priority to restore your data from the archival storage.
. If there is not enough space on the source storage or the source storage is down, select *Change storage location*.
+
If you select *Change storage location*, you can append a suffix to the destination volume. If you have not selected the checkbox, then by default *_restore* is appended to the destination volume.
. Click *Next*.
. In the Storage mapping page, specify the alternate storage location details where the data restored from the object store will be stored.
. Click *Next*.
. Review the details and click *Restore*.

This operation does only the storage export of the selected backup on the given host. You should manually mount the filesystem and bring up the database. After utilizing the volume, the storage Administrator can delete the volume from the ONTAP cluster.

NOTE: If the restore operation does not complete, do not try the restore process again until the Job Monitor shows that the restore operation has failed. If you try the restore process again before the Job Monitor shows that the restore operation has failed, the restore operation will fail again. When you see the Job Monitor status as "Failed," you can try the restore process again. 