---
sidebar: sidebar
permalink: task-restore-sql-data.html
keywords: restore, Azure, Amazon Web services, Microsoft SQL Server database
summary: You can restore SQL Server database from the cloud to the on-premises SnapCenter Server.
---

= Restore SQL Server database
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can restore SQL Server database either to the original location or to the alternate location.

NOTE: Single File Restore (SFR), Recovery of log backups, and reseed of availability groups are not supported.

.Steps

. In BlueXP UI, click *Protection* > *Backup and recovery* > *Applications*.
. In the *Filter By* field, select the filter *Type* and from the drop-down select *SQL*.
. Click *View Details* to view all the available backups.
. Select the backup and click *Restore*.
. In the Restore options page, specify the location where you want to restore the database files.
+
|===
| If you... | Do this...

a| 
Want to restore to the original location
a|
. Select *Restore to original location*.
. If the snapshot is in archival storage, select the priority to restore your data from the archival storage.
. Click *Next*.

a|
Want to temporarily restore to another storage and then copy the restored files to the original location
a|
. Select *Restore to original location*.
. If the snapshot is in archival storage, select the priority to restore your data from the archival storage.
. Select *Change storage location*.
+
If you select *Change storage location*, you can append a suffix to the destination volume. If you have not selected the checkbox, then by default *_restore* is appended to the destination volume.
. Click *Next*.
. In the Storage mapping page, specify the alternate storage location details where the data restored from the object store will be stored temporarily.
. Click *Next*.
a|
Want to restore to an alternate location
a|
. Select *Restore to alternate location*.
. If the snapshot is in archival storage, select the priority to restore your data from the archival storage.
. Click *Next*.
. In the Destination host page, select a host name, provide a database name (optional), select an instance, and specify the restore paths.
+
NOTE: The file extension provided in the alternate path must be same as the file extension of the original database file.
. Click *Next*.

a|
Want to temporarily restore to another storage and then copy the restored files to the alternate location
a|
. Select *Restore to alternate location*.
. If the snapshot is in archival storage, select the priority to restore your data from the archival storage.
. Select *Change storage location*.
+
If you select *Change storage location*, you can append a suffix to the destination volume. If you have not selected the checkbox, then by default *_restore* is appended to the destination volume.
. Click *Next*.
. In the Storage mapping page, specify the alternate storage location details where the data restored from the object store will be stored temporarily.
. Click *Next*.
. In the Destination host page, select a host name, provide a database name (optional), select an instance, and specify the restore paths.
+
NOTE: The file extension provided in the alternate path must be same as the file extension of the original database file.
. Click *Next*.
|===

. In the *Pre-operations* select, select one of the following options:
** Select *Overwrite the database with same name during restore* to restore the database with the same name.
** Select *Retain SQL database replication settings* to restore the database and retain the existing replication settings.

. In the *Post-operations* section, to specify the database state for restoring additional transactional logs, select one of the following options:
** Select *Operational, but unavailable* if you are restoring all of the necessary backups now.
+
This is the default behavior, which leaves the database ready for use by rolling back the uncommitted transactions. You cannot restore additional transaction logs until you create a backup.

** Select *Non-operational, but available* to leave the database non-operational without rolling back the uncommitted transactions.
+
Additional transaction logs can be restored. You cannot use the database until it is recovered.

** Select *Read-only mode, and available* to leave the database in read-only mode.
+
This option undoes uncommitted transactions, but saves the undone actions in a standby file so that recovery effects can be reverted.
+
If the Undo directory option is enabled, more transaction logs are restored. If the restore operation for the transaction log is unsuccessful, the changes can be rolled back. The SQL Server documentation contains more information.

. Click *Next*.
. Review the details and click *Restore*.
