---
sidebar: sidebar
permalink: task-restore-oracle-data.html
keywords: restore, Azure, Amazon Web services, Oracle database
summary: You can restore Oracle database from the cloud to the on-premises SnapCenter Server.
---

= Restore Oracle database
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can restore SQL Server database either to the same host or to the alternate host. For a RAC database, the data is restored to the on-premises node where the backup was created.

Only full database with control file restore is supported. If the archive logs are not present in the AFS, you should specify the location that contains the archive logs required for recovery.

IMPORTANT: Single File Restore (SFR) is not supported.

*Steps*

. In BlueXP UI, click *Protection* > *Backup and recovery* > *Applications*.
. In the *Filter By* field, select the filter *Type* and from the drop-down select *Oracle*.
. Click *View Details* corresponding to the database that you want to restore and click *Restore*.
. In the Restore options page, specify the location where you want to restore the database files.
+
|===
| If you... | Do this...

a| 
Want to restore to the original location
a|
. Select *Restore to original location*.
. If the snapshot is in archival storage, select the priority to restore your data from the archival storage.
+
NOTE: Only if you are using Amazon Web Services or Microsoft Azure as the cloud provider, you need to specify the priority.
. Click *Next*.

a|
Want to temporarily restore to another storage and then copy the restored files to the original location
a|
. Select *Restore to original location*.
. If the snapshot is in archival storage, select the priority to restore your data from the archival storage.
+
NOTE: Only if you are using Amazon Web Services or Microsoft Azure as the cloud provider, you need to specify the priority.
. Select *Change storage location*.
. Click *Next*.
. In the Storage mapping page, specify the alternate storage location details where the data restored from the object store will be stored temporarily.
. Click *Next*.
a|
Want to restore to an alternate location
a|
. Select *Restore to alternate location*.
. If the snapshot is in archival storage, select the priority to restore your data from the archival storage.
+
NOTE: Only if you are using Amazon Web Services or Microsoft Azure as the cloud provider, you need to specify the priority.
. Click *Next*.
. In the Destination host page, select the host and specify the FQDN or IP address of the host on which the database will be mounted.
.. For NAS environment, specify the FQDN or IP address of the host to which the volumes restored from object store are to be exported.
.. For SAN environment, specify the initiators of the host to which LUNs of the volumes restored from object store are to be mapped.
. Click *Next*.

a|
Want to temporarily restore to another storage and then copy the restored files to the alternate location
a|
. Select *Restore to alternate location*.
. If the snapshot is in archival storage, select the priority to restore your data from the archival storage.
+
NOTE: Only if you are using Amazon Web Services or Microsoft Azure as the cloud provider, you need to specify the priority.
. Select *Change storage location*.
. Click *Next*.
. In the Storage mapping page, specify the alternate storage location details where the data restored from the object store will be stored temporarily.
. Click *Next*.
. In the Destination host page, select the host and specify the FQDN or IP address of the host on which the database will be mounted.
.. For NAS environment, specify the FQDN or IP address of the host to which the volumes restored from object store are to be exported.
.. For SAN environment, specify the initiators of the host to which LUNs of the volumes restored from object store are to be mapped.
. Click *Next*.
|===

. On the Recovery settings page, perform the following actions:
.. Select *Database State* if you want to change the state of the database to the state required to perform restore and recovery operations.
+
The various states of a database from higher to lower are open, mounted, started, and shutdown. 
+
* If the database is in a higher state but the state must be changed to a lower state to perform a restore operation, you must select this check box.
* If the database is in a lower state but the state must be changed to a higher state to perform the restore operation, the database state is changed automatically even if you do not select the check box.
* If a database is in the open state, and for restore the database needs to be in the mounted state, then the database state is changed only if you select this check box.
. Select the recovery scope.
+
|===
| If you... | Do this...

a|
Want to recover to the last transaction
a|
Select *All Logs*.
a|
Want to recover to a specific System Change Number (SCN)
a|
Select *Until SCN (System Change Number)*.
a|
Want to recover to a specific data and time
a|
Select *Date and Time*.

You must specify the date and time of the database host's time zone.
a|
Do not want to recover
a|
Select *No recovery*.
a|
Want to specify any external archive log locations
a|
If the archive logs are not present in the active file system, you should specify the location that contains the archive logs required for recovery.
|===
.. Select the check box if you want to open the database after recovery.
+
In a RAC setup, only the RAC instance that is used for recovery is opened after recovery.
. Click *Next*.
. Review the details and click *Restore*.

The *Restore to alternate location* option mounts only the storage on the given host. You should manually mount the filesystem and bring up the database. After utilizing the volume, the storage Administrator can delete the volume from the ONTAP cluster.

* For information on how to bring up the Oracle database see, https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/How_to_bring_up_Oracle_Database_in_another_NFS_host_after_mounting_storage_from_backup_in_Cloud_Backup_for_Applications[Knowledge base article].
