---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore, bluexp, bluexp backup and recovery
summary: Learn what's new in BlueXP backup and recovery.
---
= What's new in BlueXP backup and recovery Preview 2025
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in BlueXP backup and recovery Preview 2025 version.

// tag::whats-new[]

== 05 February 2025

This BlueXP backup and recovery release includes the following updates.
//v3.0.9

include::_whatsnew/2025-02-05.adoc[]    


== 22 November 2024
This BlueXP backup and recovery release includes the following updates.
//v3.0.8

include::_whatsnew/2024-11-22.adoc[]

== 27 September 2024
This BlueXP backup and recovery release includes the following updates.
//v3.0.7 

include::_whatsnew/2024-09-27.adoc[]

== 22 July 2024 

include::_whatsnew/2024-07-22.adoc[]

// end::whats-new[] 

== 17 May 2024

=== Limitations when using RHEL 8 and RHEL 9 for your on-premises Connector

BlueXP Connector version 3.9.40 supports certain versions of Red Hat Enterprise Linux versions 8 and 9 for any manual installation of the Connector software on a RHEL 8 or 9 host, regardless of the location in addition to the operating systems mentioned in the https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements[host requirements^]. These newer RHEL versions require the Podman engine instead of the Docker engine. At this time, BlueXP backup and recovery has two limitations when using the Podman engine. 

See https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-limitations.html[Backup and Restore limitations] for details. 


The following procedures include new Podman instructions:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-restart-backup.html[Restart BlueXP backup and recovery]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html[Restore BlueXP backup and recovery data in a dark site]

//* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-restart-backup.html[Restart BlueXP backup and recovery]
//* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html[Restore BlueXP backup and recovery data in a dark site]




== 30 April 2024 

=== Ability to enable or disable scheduled ransomware scans 

Previously, you could enable or disable ransomware scans, but could not do this for scheduled scans. 

With this release, you can now enable or disable scheduled ransomware scans on the latest Snapshot copy by using the option on the Advanced Settings page. If you enable it, scans are performed weekly by default. You can change that schedule to days or weeks or disable it, saving costs.  

Refer to the following information for details: 

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html[Manage backup settings]

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html[Manage policies for ONTAP volumes]

* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html[Backup-to-object policy settings]


== 04 April 2024

=== Ability to enable or disable ransomware scans 

Previously, when you enabled ransomware detection in a backup policy, scans occurred automatically when the first backup was created and when you restored a backup. Previously, the service scanned all Snapshot copies and you could not disable the scans. 

With this release, you can now enable or disable ransomware scans on the latest Snapshot copy by using the option on the Advanced Settings page. If you enable it, scans are performed weekly by default. 

//You can change that schedule to days or weeks or disable it, saving costs.  

Refer to the following information for details: 

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html[Manage backup settings]

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html[Manage policies for ONTAP volumes]

* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html[Backup-to-object policy settings]



//=== Red Hat Enterprise Linux versions 8.8 and 9.3

//The BlueXP Connector now supports Red Hat Enterprise Linux versions 8.8 and 9.3 for on-premises installations in addition to the operating systems mentioned in https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements[Prepare for deployment^].

//Red Hat Enterprise Linux versions 8 and 9 require that you use the Podman engine instead of the Docker engine. At this time, BlueXP backup and recovery is not compatible with the Podman engine, so if you plan to use BlueXP backup and recovery with your other BlueXP services, continue to use the other supported operating systems when installing your Connector.


//This next is for when BR can do Podman. Previously, BlueXP supported Red Hat Enterprise Linux versions 9.0, 9.1, and 9.2. 

//BlueXP now supports versions 8.8 and 9.3, which require Podman, rather than Docker Engine. This impacts how to restart the service and restore data in a dark site. 

//Refer to changes in the following procedures: 

//* link:reference-restart-backup.html[Restart the BlueXP backup and recovery service]
//* link:reference-backup-cbs-db-in-dark-site.html[Restore BlueXP backup and recovery data in a dark site]

//* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-restart-backup.html[Restart the BlueXP backup and recovery service]
//* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html[Restore BlueXP backup and recovery data in a dark site]

//=== Ability to back up data from Cloud Volumes ONTAP systems in secure regions

//Now you can back up data from Cloud Volumes ONTAP systems installed in AWS C2S/SC2S and Azure IL6 secure regions to Amazon S3 or Azure Blob. This requires that you install the Connector in "private mode" on a Linux host in the secure region, and that you deploy the Cloud Volumes ONTAP system there as well. 

ifdef::aws[]
See https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html[Backing up Cloud Volumes ONTAP data to Amazon S3] and https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html[Backing up Cloud Volumes ONTAP data to Azure Blob].
endif::aws[]

== 12 March 2024

=== Ability to do "Quick Restores" from cloud backups to on-premises ONTAP volumes

Now you can perform a _quick restore_ of a volume from cloud storage to an on-premises ONTAP destination volume. Previously you could perform a quick restore only to a Cloud Volumes ONTAP system. The quick restore is ideal for disaster recovery situations where you need to provide access to a volume as soon as possible. A quick restore is much faster than full volume restore; it restores the metadata from a cloud snapshot to an ONTAP destination volume. The source could be from AWS S3, Azure Blob, Google Cloud Services, or NetApp StorageGRID.
 
The on-premises ONTAP destination system must be running ONTAP version 9.14.1 or greater. 

You can do this using the Browse and restore process, not the Search and restore process. 

For details, see https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html[Restore ONTAP data from backup files].



=== Ability to restore files and folders from Snapshot and Replication copies

Previously, you could restore files and folders only from backup copies in AWS, Azure, and Google Cloud Services. Now, you can restore files and folders from local Snapshot copies and from replication copies. 

You can perform this feature by using the Search and restore process, not by using the Browse and restore process. 


== 01 February 2024 

=== Enhancements to BlueXP backup and recovery for Virtual Machines

* Support restoring virtual machines to an alternate location
* Support for unprotecting datastores



== 15 December 2023 

=== Reports available for local Snapshot and replication Snapshot copies

Previously, you could generate reports on backup copies only. Now, you can create reports on local Snapshot copies and replication Snapshot copies as well. 

With these reports, you can do the following: 

* Ensure that critical data is protected according to your organizational policy.
* Ensure that backups ran smoothly for a group of volumes.
* Provide proof of protection on your production data. 

Refer to https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html[Report on data protection coverage]. 

=== Custom tagging available on volumes for sorting and filtering

You can now add custom tags to volumes starting in ONTAP 9.13.1 so that you can group volumes together within and across working environments. Doing this enables you to sort volumes in the BlueXP backup and recovery UI pages and filter in reports. 

=== Catalog backups retained for 30 days

Previously, Catalog.zip backups were retained for 7 days. Now, they are retained for 30 days. 

Refer to https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html[Restore BlueXP backup and recovery data in dark sites]. 

== 23 October 2023 

=== 3-2-1 backup policy creation during backup activation

Previously, custom policies had to be created before you initiated a Snapshot, replication, or backup. Now you can create a policy during the backup activation process using the BlueXP backup and recovery UI.  

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html[Learn more about policies].

=== Support for on-demand quick restore of ONTAP volumes

BlueXP backup and recovery now provides the ability to perform a "quick restore" of a volume from cloud storage to a Cloud Volumes ONTAP system. The quick restore is ideal for disaster recovery situations where you need to provide access to a volume as soon as possible. A quick restore restores the metadata from the backup file to a volume instead of restoring the entire backup file.

The Cloud Volumes ONTAP destination system must be running ONTAP version 9.13.0 or greater. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html[Learn more about restoring data].

The BlueXP backup and recovery Job Monitor also shows information about the progress of quick restore jobs. 

=== Support for scheduled jobs in the Job Monitor   

The BlueXP backup and recovery Job Monitor previously monitored scheduled volume-to-object-store backup and restore jobs but not local Snapshot, replication, backup, and restore jobs that were scheduled via the UI or API. 

The BlueXP backup and recovery Job Monitor now includes scheduled jobs for local Snapshots, replications, and backups to object storage. 

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html[Learn more about the updated Job Monitor].




== 13 October 2023

=== Enhancements to BlueXP backup and recovery for applications (cloud-native)

* Microsoft SQL Server database
** Supports backup, restore, and recovery of Microsoft SQL Server databases residing on Amazon FSx for NetApp ONTAP
** All the operations are supported only through REST APIs.

* SAP HANA systems
** During system refresh, the auto mount and unmount of the volumes are performed using workflows instead of scripts
** Supports addition, removal, edit, delete, maintain, and upgrade of the plug-in host using UI

=== Enhancements to BlueXP backup and recovery for applications (hybrid)

* Supports data lock and ransomware protection
* Supports moving backups from StorageGrid to archival tier
* Supports backing up of MongoDB, MySQL, and PostgreSQL applications data from on-premises ONTAP systems to Amazon Web Services, Microsoft Azure, Google Cloud Platform, and StorageGRID. You can restore the data when required.

=== Enhancements to BlueXP backup and recovery for Virtual Machines

* Support for connector proxy deployment model



== 11 September 2023

=== New policies management for ONTAP data
This release includes the ability within the UI to create custom Snapshot policies, replication policies, and policies for backups to object storage for ONTAP data. 

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html[Learn more about policies].

=== Support for restoring files and folder from volumes in ONTAP S3 object storage

Previously, you couldn't restore files and folders using the “Browse & Restore” feature when volumes were backed up to ONTAP S3 object storage. This release removes that restriction.  

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html[Learn more about restoring data].

=== Ability to archive backup data immediately instead of first writing to standard storage

Now you can send your backup files immediately to archive storage instead of writing the data to standard cloud storage. This can be especially helpful for users who rarely need to access data from cloud backups or users who are replacing a backup to tape environment.

=== Additional support for backing up and restoring SnapLock volumes
Backup and recovery now can back up both FlexVol and FlexGroup volumes that are configured using SnapLock Enterprise protection mode. Your clusters must be running ONTAP 9.14 or greater for this support. Backing up FlexVol volumes using SnapLock Enterprise mode has been supported since ONTAP version 9.11.1. Earlier ONTAP releases provide no support for backing up SnapLock protection volumes.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html[Learn more about protecting ONTAP data].


== 1 August 2023 

[IMPORTANT]
====
* Because of an important security enhancement, your Connector now requires outbound internet access to an additional endpoint in order to manage backup and recovery resources within your public cloud environment. If this endpoint has not been added to the "allowed" list in your firewall you'll see an error in the UI about "Service Unavailable" or "Failed to determine service status":
+
\https://netapp-cloud-account.auth0.com
* A Backup and recovery PAYGO subscription is now required when you are using the "CVO Professional" package that enables you to bundle Cloud Volumes ONTAP and BlueXP backup and recovery. This was not required in the past. No charges will be incurred on the Backup and recovery subscription for eligible Cloud Volumes ONTAP systems, but it is required when configuring backup on any new volumes. 
====

=== Support has been added to back up volumes to buckets on S3-configured ONTAP systems

Now you can use an ONTAP system which has been configured for the Simple Storage Service (S3) to back up volumes to object storage. This is supported for both on-premises ONTAP systems and Cloud Volumes ONTAP systems. This configuration is supported in cloud deployments and in on-premises locations without internet access (a "private" mode deployment).

ifdef::aws[]
https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html[Learn more]. 
endif::aws[]

=== Now you can include existing Snapshots from a protected volume in your backup files

In the past you've had the ability to include existing Snapshot copies from read-write volumes in your initial backup file to object storage (instead of starting with the most recent Snapshot copy). Existing Snapshot copies from read-only volumes (data protection volumes) were not included in the backup file. Now you can choose to include older Snapshot copies in the backup file for "DP" volumes.
//
//*Note:* This is supported if the source volume is "RW".

The backup wizard displays a prompt at the end of the backup steps where you can select these "existing Snapshots".  

=== BlueXP backup and recovery no longer supports auto backup of volumes added in the future

Previously you could check a box in the backup wizard to apply the selected backup policy to all future volumes added to the cluster. This feature has been removed based on user feedback and lack of usage of this feature. You'll need to manually enable backups for any new volumes added to the cluster.

=== The Job Monitoring page has been updated with new features

The Job Monitoring page now provides more information related to the 3-2-1 backup strategy. The service also provides additional alert notifications related to the backup strategy. 

The "Backup lifecycle" Type filter has been renamed to "Retention". Use this filter to track the backup lifecycle and to identify the expiration of all backup copies. The "Retention" job type captures all Snapshot deletion jobs initiated on a volume that is protected by BlueXP backup and recovery.  

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html[Learn more about the updated Job Monitor].


== 6 July 2023

=== BlueXP backup and recovery now includes the ability to schedule and create Snapshot copies and replicated volumes

BlueXP backup and recovery now enables you to implement a 3-2-1 strategy where you can have 3 copies of your source data on 2 different storage systems along with 1 copy in the cloud. After activation, you'll have a:

* Snapshot copy of the volume on the source system
* Replicated volume on a different storage system
* Backup of the volume in object storage

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html[Learn more about the new full spectrum backup and restore capabilities].

This new functionality also applies to recovery operations. You can perform restore operations from a Snapshot copy, from a replicated volume, or from a backup file in the cloud. This gives you the flexibility to choose the backup file that meets your recovery requirements, including cost and speed of recovery.

Note that this new functionality and user interface is supported only for clusters running ONTAP 9.8 or greater. If your cluster has an earlier version of software, you can continue using the previous version of BlueXP backup and recovery. However, we recommend that you upgrade to a supported version of ONTAP to get the newest features and functionality. To continue using the older version of the software, follow these steps:

. From the *Volumes* tab, select *Backup Settings*.

. From the _Backup Settings_ page, click the radio button for *Display the previous BlueXP backup and recovery version*.
+
Then you can manage your older clusters using the previous version of software.

=== Ability to create your storage container for backup to object storage

When you create backup files in object storage, by default, the backup and recovery service will create the buckets in object storage for you. You can create the buckets yourself if you want to use a certain name or assign special properties. If you want to create your own bucket, you must create it before starting the activation wizard. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container[Learn how to create your object storage buckets].

This functionality is not currently supported when creating backup files to StorageGRID systems.

== 04 July 2023

=== Enhancements to BlueXP backup and recovery for applications (cloud-native)

* SAP HANA systems
** Supports connect and copy restore of Non-Data Volumes and Global Non-Data volumes having Azure NetApp Files secondary protection

* Oracle databases
** Supports restore of Oracle databases on Azure NetApp Files to alternate location
** Supports Oracle Recovery Manager (RMAN) cataloging of backups of Oracle databases on Azure NetApp Files
** Allows you to put the database host to maintenance mode to perform maintenance tasks

=== Enhancements to BlueXP backup and recovery for applications (hybrid)

* Supports restore to alternate location 
* Allows you to mount Oracle database backups
* Supports moving backups from GCP to archival tier

=== Enhancements to BlueXP backup and recovery for virtual machines (hybrid)

* Supports protection of NFS and VMFS type of datastores
* Allows you to unregister the SnapCenter Plug-in for VMware vSphere host
* Supports refresh and discovery of latest datastores and backups

== 5 June 2023

=== FlexGroup volumes can be backed up and protected using DataLock and Ransomware protection

Backup policies for FlexGroup volumes now can use DataLock and Ransomware protection when the cluster is running ONTAP 9.13.1 or greater.

=== New reporting features

There is now a Reports tab where you can generate a Backup Inventory report, which includes all backups for a specific account, working environment, or SVM inventory. You can also create a Data Protection Job Activity report, which provides information about Snapshot, backup, clone, and restore operations that can help you with service level agreement monitoring. Refer to https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html[Report on data protection coverage]. 

===	Job Monitor enhancements

You can now review _backup lifecycle_ as a Job Type on the Job Monitor page, helping you to track the entire backup lifecycle. You can also see details of all operations on the BlueXP Timeline. Refer to https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html[Monitor the status of backup and restore jobs]. 

=== Additional notification alert for unmatched policy labels

A new backup alert has been added: "Backup files were not created because Snapshot policy labels do not match". If the _label_ defined in a Backup policy does not have a matching _label_ in the Snapshot policy, then no backup file will be created. You'll need to use System Manager or the ONTAP CLI to add the missing label to the volume Snapshot policy.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center[Review all of the alerts that BlueXP backup and recovery can send].

=== Automatic back up of critical BlueXP backup and recovery files in dark sites

When you're using BlueXP backup and recovery in a site with no internet access, known as a "private mode" deployment, the BlueXP backup and recovery information is stored only on the local Connector system. This new functionality automatically backs up critical BlueXP backup and recovery data to a bucket on your connected StorageGRID system so that you can restore this data onto a new Connector if necessary. https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html[Learn more]



== 8 May 2023

=== Folder-level restore operations are now supported from archival storage and from locked backups

If a backup file has been configured with DataLock & Ransomware protection, or if the backup file resides in archival storage, now folder-level restore operations are supported if the cluster is running ONTAP 9.13.1 or greater.

=== Cross-region and cross-project customer-managed keys are supported when backing up volumes to Google Cloud

Now you can choose a bucket that's in a different project than the project of your customer-managed encryption keys (CMEK). 
ifdef::gcp[]
https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups[Learn more about setting up your own customer-managed encryption keys].
endif::gcp[]

=== AWS China regions are now supported for backup files

The AWS China Beijing (cn-north-1) and Ningxia (cn-northwest-1) regions are now supported as destinations for your backup files if the cluster is running ONTAP 9.12.1 or greater.

Note that the IAM policies assigned to the BlueXP Connector need to change the AWS Resource Name "arn" under all _Resource_ sections from "aws" to "aws-cn"; for example "arn:aws-cn:s3:::netapp-backup-*". 

ifdef::aws[]
See https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html[Back up Cloud Volumes ONTAP data to Amazon S3] and https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html[Back up on-prem ONTAP data to Amazon S3] for details.
endif::aws[]

=== Enhancements to the Job Monitor

System-initiated jobs, such ongoing backup operations, are now available in the *Job Monitoring* tab for on-premises ONTAP systems running ONTAP 9.13.1 or greater. Earlier ONTAP versions will display only user-initiated jobs.

== 14 April 2023

=== Enhancements to BlueXP backup and recovery for applications (cloud-native)

* SAP HANA databases
** Supports script based system refresh
** Supports Single-File-Snapshot-Restore if Azure NetApp Files backup is configured
** Supports plug-in upgrade
* Oracle databases
** Enhancements to plug-in deployment by simplifying non-root sudo user configuration
** Supports plug-in upgrade
** Supports auto-discovery and policy driven protection of Oracle databases on Azure NetApp Files
** Supports restore of Oracle database to original location with granular recovery

=== Enhancements to BlueXP backup and recovery for applications (hybrid)

* BlueXP backup and recovery for applications (hybrid) is driven from the SaaS control plane
* Modified the hybrid REST APIs to align with cloud-native APIs.
* Supports email notification

== 4 April 2023

=== Ability to back up data to the cloud from Cloud Volumes ONTAP systems in "Restricted" mode

Now you can back up data from Cloud Volumes ONTAP systems installed in AWS, Azure, and GCP commercial regions in "restricted mode". This requires that you first install the Connector in the "restricted" commercial region. https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html[Learn more about BlueXP deployment modes^]. 

ifdef::aws[]
See https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html[Backing up Cloud Volumes ONTAP data to Amazon S3]
endif::aws[]

ifdef::azure[]
See https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html[Backing up Cloud Volumes ONTAP data to Azure Blob].
endif::azure[]

=== Ability to back up your on-premises ONTAP volumes to ONTAP S3 using the API

New functionality in the APIs enable you to back up your volume snapshots to ONTAP S3 using BlueXP backup and recovery. This functionality is available only for On-Premises ONTAP systems at this time. For detailed instructions, see the Blog https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-April-23-Updates/ba-p/443075#toc-hId--846533830[Integration with ONTAP S3 as a destination^].

=== Ability to change the zone-redundancy aspect of your Azure storage account from LRS to ZRS

When creating backups from Cloud Volumes ONTAP systems to Azure storage, by default, BlueXP backup and recovery provisions the Blob container with Local redundancy (LRS) for cost optimization. You can change this setting to Zone redundancy (ZRS) if you want your data to be replicated between different zones. See the Microsoft instructions for https://learn.microsoft.com/en-us/azure/storage/common/redundancy-migration?tabs=portal[changing how your storage account is replicated^].

=== Enhancements to the Job Monitor

* Both user-initiated backup and restore operations initiated from the BlueXP backup and recovery UI and API, and system-initiated jobs, such ongoing backup operations, are now available in the *Job Monitoring* tab for Cloud Volumes ONTAP systems running ONTAP 9.13.0 or greater. Earlier ONTAP versions will display only user-initiated jobs.
* In addition to being able to download a CSV file for reporting on all jobs, now you can download a JSON file for a single job and see its details. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report[Learn more].
* Two new backup job alerts have been added: "Scheduled job failure" and "Restore job completes but with warnings". https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center[Review all of the alerts that BlueXP backup and recovery can send].

== 9 March 2023

=== Folder-level restore operations now include all sub-folders and files

In the past when you restored a folder, only files from that folder were restored - no sub-folders, or files in sub-folders, were restored. Now, if you are using ONTAP 9.13.0 or greater, all the sub-folders and files in the selected folder are restored. This can save a great deal of time and money in cases where you have multiple nested folders in a top-level folder.

=== Ability to back up data from Cloud Volumes ONTAP systems in sites with limited outbound connectivity

Now you can back up data from Cloud Volumes ONTAP systems installed in AWS and Azure commercial regions to Amazon S3 or Azure Blob. This requires that you install the Connector in "restricted mode" on a Linux host in the commercial region, and that you deploy the Cloud Volumes ONTAP system there as well. 

ifdef::aws[]
See https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html[Backing up Cloud Volumes ONTAP data to Amazon S3].
endif::aws[]

ifdef::azure[]
See https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html[Backing up Cloud Volumes ONTAP data to Azure Blob].
endif::azure[]

=== Multiple enhancements to the Job Monitor

* The Job Monitoring page has added advanced filtering so you can search for backup and restore jobs by time, workload (volumes, applications, or virtual machines), job type, status, working environment, and storage VM. You can also enter free text to search for any resource, for example, "application_3".  https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#searching-and-filtering-the-list-of-jobs[See how to use the advanced filters].

* Both user-initiated backup and restore operations initiated from the BlueXP backup and recovery UI and API, and system-initiated jobs, such ongoing backup operations, are now available in the *Job Monitoring* tab for Cloud Volumes ONTAP systems running ONTAP 9.13.0 or greater. Earlier versions of Cloud Volumes ONTAP systems, and on-premises ONTAP systems, will display only user-initiated jobs at this time.

== 6 February 2023

=== Ability to move older backup files to Azure archival storage from StorageGRID systems

Now you can tier older backup files from StorageGRID systems to archival storage in Azure. This enables you to free up space on your StorageGRID systems, and save money by using an inexpensive storage class for old backup files.

This functionality is available if your on-prem cluster is using ONTAP 9.12.1 or greater and your StorageGRID system is using 11.4 or greater. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage[Learn more here^].

=== DataLock and Ransomware protection can be configured for backup files in Azure Blob

DataLock and Ransomware Protection is now supported for backup files stored in Azure Blob. If your Cloud Volumes ONTAP or on-prem ONTAP system are running ONTAP 9.12.1 or greater, now you can lock your backup files and scan them to detect possible ransomware. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection[Learn more about how you can protect your backups by using DataLock and Ransomware protection^].

=== Backup and restore FlexGroup volume enhancements

* Now you can choose multiple aggregates when restoring a FlexGroup volume. In the last release you could only select a single aggregate.
* FlexGroup volume restore is now supported on Cloud Volumes ONTAP systems. In the last release you could only restore to on-prem ONTAP systems.

=== Cloud Volumes ONTAP systems can move older backups to Google Archival storage

Backup files are initially created in the Google Standard storage class. Now you can use BlueXP backup and recovery to tier older backups to Google Archive storage for further cost optimization. The last release only supported this functionality with on-prem ONTAP clusters - now Cloud Volumes ONTAP systems deployed in Google Cloud are supported.

=== Volume Restore operations now enable you to select the SVM where you want to restore volume data

Now you restore volume data to different storage VMs in your ONTAP clusters. In the past there was no ability to choose the storage VM.

=== Enhanced support for volumes in MetroCluster configurations

When using ONTAP 9.12.1 GA or greater, backup is now supported when connected to the primary system in a MetroCluster configuration. The entire backup configuration is transferred to the secondary system so that backups to the cloud continue automatically after switchover.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#backup-limitations[See Backup limitations for more information]. 

== 9 January 2023

=== Ability to move older backup files to AWS S3 archival storage from StorageGRID systems

Now you can tier older backup files from StorageGRID systems to archival storage in AWS S3. This enables you to free up space on your StorageGRID systems, and save money by using an inexpensive storage class for old backup files. You can choose to tier backups to AWS S3 Glacier or S3 Glacier Deep Archive storage.

This functionality is available if your on-prem cluster is using ONTAP 9.12.1 or greater, and your StorageGRID system is using 11.3 or greater. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage[Learn more here].

=== Ability to select your own customer-managed keys for data encryption on Google Cloud

When backing up data from your ONTAP systems to Google Cloud Storage, now you can select your own customer-managed keys for data encryption in the activation wizard instead of using the default Google-managed encryption keys. Just set up your customer-managed encryption keys in Google first, and then enter the details when activating BlueXP backup and recovery.

=== "Storage Admin" role no longer needed for the service account to create backups in Google Cloud Storage

In earlier releases, the "Storage Admin" role was required for the service account that enables BlueXP backup and recovery to access Google Cloud Storage buckets. Now you can create a custom role with a reduced set of permissions to be assigned to the service account. 

ifdef::gcp[]
https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups[See how to prepare your Google Cloud Storage for backups].
endif::gcp[]

=== Support has been added to restore data using Search & Restore in sites without internet access

If you are backing up data from an on-prem ONTAP cluster to StorageGRID in a site with no internet access, also known as a dark site or offline site, now you can use the Search & Restore option to restore data when necessary. This functionality requires that the BlueXP Connector (version 3.9.25 or greater) is deployed in the offline site.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore[See how to restore ONTAP data using Search & Restore].
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html[See how to install the Connector in your offline site].

=== Ability to download the Job Monitoring results page as a .csv report

After you filter the Job Monitoring page to display the jobs and actions you are interested in, now you can generate and download a .csv file of that data. Then you can analyze the information, or send the report to other people in your organization. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report[See how to generate a Job Monitoring report].

== 19 December 2022

=== Enhancements to Cloud Backup for Applications

* SAP HANA databases
** Supports policy-based backup and restore of SAP HANA databases residing on Azure NetApp Files
** Supports custom policies
* Oracle databases
** Add hosts and deploy plug-in automatically
** Supports custom policies
** Supports policy-based backup, restore, and clone of Oracle databases residing on Cloud Volumes ONTAP
** Supports policy-based backup and restore of Oracle databases residing on Amazon FSx for NetApp ONTAP
** Supports restore of Oracle databases using connect-and-copy method
** Supports Oracle 21c
** Supports cloning of cloud-native Oracle database

=== Enhancements to Cloud Backup for Virtual Machines

* Virtual machines
** Back up virtual machines from on-premises secondary storage
** Supports custom policies
** Supports Google Cloud Platform (GCP) to back up one or more datastores
** Supports low cost cloud storage like Glacier, Deep Glacier, and Azure Archive

== 6 December 2022

=== Required Connector outbound internet access endpoint changes

Because of a change in Cloud Backup, you need to change the following Connector endpoints for successful Cloud Backup operation:

[cols=2*,options="header",cols="50,50",width="80%"]
|===

| Old endpoint
| New endpoint

| \https://cloudmanager.cloud.netapp.com
| \https://api.bluexp.netapp.com
| \https://*.cloudmanager.cloud.netapp.com
| \https://*.api.bluexp.netapp.com

|===

See the full list of endpoints for your https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access[AWS^], https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access[Google Cloud^], or https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access[Azure^] cloud environment.

=== Support for selecting the Google Archival storage class in the UI

Backup files are initially created in the Google Standard storage class. Now you can use the Cloud Backup UI to tier older backups to Google Archive storage after a certain number of days for further cost optimization. 

This functionality is currently supported for on-prem ONTAP clusters using ONTAP 9.12.1 or greater. It is not currently available for Cloud Volumes ONTAP systems.

=== Support for FlexGroup volumes

Cloud Backup now supports backing up and restoring FlexGroup volumes. When using ONTAP 9.12.1 or greater, you can back up FlexGroup volumes to public and private cloud storage. If you have working environments that include FlexVol and FlexGroup volumes, once you update your ONTAP software, you can back up any of the FlexGroup volumes on those systems.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#supported-volumes[See the full list of supported volume types].

=== Ability to restore data from backups to a specific aggregate on Cloud Volumes ONTAP systems

In earlier releases you could select the aggregate only when restoring data to on-prem ONTAP systems. This functionality now works when restoring data to Cloud Volumes ONTAP systems.

== 2 November 2022

=== Ability to export older Snapshot copies into your baseline backup files

If there are any local Snapshot copies for volumes in your working environment that match your backup schedule labels (for example, daily, weekly, etc.), you can export those historic snapshots to object storage as backup files. This enables you to initialize your backups in the cloud by moving older snapshot copies into the baseline backup copy.

This option is available when activating Cloud Backup for your working environments. You can also change this setting later in the https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html[Advanced Settings page].

=== Cloud Backup can now be used for archiving volumes that you no longer need on the source system

Now you can delete the backup relationship for a volume. This provides you with an archiving mechanism if you want to stop the creation of new backup files and delete the source volume, but retain all the existing backup files. This gives you the ability to restore the volume from the backup file in the future, if needed, while clearing space from your source storage system. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backups-ontap.html#deleting-volume-backup-relationships[Learn how].

=== Support has been added to receive Cloud Backup alerts in email and in the Notification Center

Cloud Backup has been integrated into the BlueXP Notification service. You can display Cloud Backup notifications by clicking the notification bell in the BlueXP menu bar. You can also configure BlueXP to send notifications by email as alerts so you can be informed of important system activity even when you're not logged into the system. The email can be sent to any recipients who need to be aware of backup and restore activity. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#use-the-job-monitor-to-view-backup-and-restore-job-status[Learn how].

=== New Advanced Settings page enables you to change cluster-level backup settings

This new page enables you to change many cluster-level backup settings that you set when activating Cloud Backup for each ONTAP system. You can also modify some settings that are applied as "default" backup settings. The full set of backup settings that you can change includes:

* The storage keys that give your ONTAP system permission to access object storage
* The network bandwidth allocated to upload backups to object storage
* The automatic backup setting (and policy) for future volumes
* The archival storage class (AWS only)
* Whether historical Snapshot copies are included in your initial baseline backup files
* Whether "yearly" snapshots are removed from the source system
* The ONTAP IPspace that is connected to object storage (in case of incorrect selection during activation)

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html[Learn more about managing cluster-level backup settings].

=== Now you can restore backup files using Search & Restore when using an on-premises Connector

In the previous release, support was added for creating backup files to the public cloud when the Connector is deployed in your premises. In this release, support has been continued to allow using Search & Restore to restore backups from Amazon S3 or Azure Blob when the Connector is deployed in your premises. Search & Restore also supports restoring backups from StorageGRID systems to on-premises ONTAP systems now.

At this time, the Connector must be deployed in the Google Cloud Platform when using Search & Restore to restore backups from Google Cloud Storage.

=== Job Monitoring page has been updated 

The following updates have been made to the https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html[Job Monitoring page]: 

* A column for "Workload" is available so you can filter the page to view jobs for the following Backup services: Volumes, Applications, and Virtual Machines.
* You can add new columns for "User Name" and "Job Type" if you want to view these details for a specific backup job.
* The Job Details page displays all the sub-jobs that are running to complete the main job.
* The page automatically refreshes every 15 minutes so that you'll always see the most recent job status results. And you can click the *Refresh* button to update the page immediately.

=== AWS cross-account backup enhancements

If you want to use a different AWS account for your Cloud Volumes ONTAP backups than you're using for the source volumes, you must add the destination AWS account credentials in BlueXP, and you must add the permissions "s3:PutBucketPolicy" and "s3:PutBucketOwnershipControls" to the IAM role that provides BlueXP with permissions. In the past you needed to configure many settings in the AWS Console - you don't need to do that anymore.

== 28 September 2022

=== Enhancements to Cloud Backup for Applications

* Supports Google Cloud Platform (GCP) and StorageGRID to back up application consistent snapshots
* Create custom policies
* Supports archival storage
* Back up SAP HANA applications
* Back up Oracle and SQL applications that are on VMware environment
* Back up applications from on-premises secondary storage
* Deactivate backups
* Unregister SnapCenter Server

=== Enhancements to Cloud Backup for Virtual Machines

* Supports StorageGRID to back up one or more datastores
* Create custom policies

== 19 September 2022

=== DataLock and Ransomware protection can be configured for backup files in StorageGRID systems

The last release introduced _DataLock and Ransomware Protection_ for backups stored in Amazon S3 buckets. This release expands support to backup files stored in StorageGRID systems. If your cluster is using ONTAP 9.11.1 or greater, and your StorageGRID system is running version 11.6.0.3 or greater, this new backup policy option is available. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection[Learn more about how you can use DataLock and Ransomware protection to protect your backups^].

Note that you'll need to be running a Connector with version 3.9.22 or greater software. The Connector must be installed in your premises, and it can be installed in a site with or without internet access.

=== Folder-level restore is now available from your backup files

Now you can restore a folder from a backup file if you need access to all the files in that folder (directory or share). Restoring a folder is much more efficient than restoring an entire volume. This functionality is available for restore operations using both the Browse & Restore method and the Search & Restore method when using ONTAP 9.11.1 or greater. At this time you can can select and restore only a single folder, and only files from that folder are restored - no sub-folders, or files in sub-folders, are restored.

=== File-level restore is now available from backups that have been moved to archival storage

In the past you could only restore volumes from backup files that had been moved to archival storage (AWS and Azure only). Now you can restore individual files from these archived backup files. This functionality is available for restore operations using both the Browse & Restore method and the Search & Restore method when using ONTAP 9.11.1 or greater.

=== File-level restore now provides the option to overwrite the original source file

In the past, a file restored to the original volume was always restored as a new file with the prefix "Restore_<file_name>". Now you can choose to overwrite the original source file when restoring the file to the original location on the volume. This functionality is available for restore operations using both the Browse & Restore method and the Search & Restore method.

=== Drag and drop to enable Cloud Backup to StorageGRID systems

If the https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html[StorageGRID^] destination for your backups exists as a working environment on the Canvas, you can drag your on-prem ONTAP working environment onto the destination to initiate the Cloud Backup setup wizard.
