---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore
summary: Learn what's new in Cloud Backup.
---

= What's new with Cloud Backup
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in Cloud Backup.

// tag::whats-new[]
== 5 January 2023

=== Enhanced support for volumes in MetroCluster configurations

When using ONTAP 9.12.1 or greater, backup is now supported when connected to the primary system in a MetroCluster configuration. The entire backup configuration is transferred to the secondary system so that backups to the cloud continue automatically after switchover.

https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-ontap-backup-to-cloud.html#backup-limitations[See Backup limitations for more information]. 

=== Ability to move older backup files to AWS S3 archival storage from StorageGRID systems

Now you can tier older backup files from StorageGRID systems to archival storage in AWS S3. This enables you to free up space on your StorageGRID systems, and save money by using an inexpensive storage class for old backup files. You can choose to tier backups to AWS S3 Glacier or S3 Glacier Deep Archive storage.

This functionality is available if your cluster is using ONTAP 9.12.1 or greater, and your StorageGRID system is using 11.3 or greater. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-private-cloud.html#preparing-to-tier-older-backup-files-to-public-cloud-storage[Learn more here].

=== Ability to select your own customer-managed keys for data encryption on Google Cloud

When backing up data from your ONTAP systems to Google Cloud Storage, now you can select your own customer-managed keys for data encryption in the activation wizard instead of using the default Google-managed encryption keys. Just set up your customer-managed encryption keys first, and then enter the details when activating Cloud Backup.

=== "Storage Admin" role no longer needed for the service account to create backups in Google Cloud Storage

In earlier releases, the "Storage Admin" role was required for the service account that enables Cloud Backup to access Google Cloud Storage buckets. Now you can create a custom role with a reduced set of permissions to be assigned to the service account. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups[See how to prepare your Google Cloud Storage for backups].

=== Ability to download the Job Monitoring results page as a .csv report

After you filter the Job Monitoring page to display the jobs and actions you are interested in, now you can generate and download a .csv file of that data. Then you can analyze the information, or send the report to other people in your organization. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report[See how to generate a Job Monitoring report].

== 19 December 2022

=== Enhancements to Cloud Backup for Applications

* SAP HANA databases
** Supports policy-based backup and restore of SAP HANA databases residing on Azure NetApp Files (ANF) 
** Supports custom policies
* Oracle databases
** Add hosts and deploy plug-in automatically
** Supports custom policies
** Supports policy-based backup, restore, and clone of Oracle databases residing on Cloud Volumes ONTAP
** Supports policy-based backup and restore of Oracle databases residing on Amazon FSx for NetApp ONTAP
** Supports restore of Oracle databases using connect-and-copy method
** Supports Oracle 21c
** Supports cloning of cloud native Oracle database

=== Enhancements to Cloud Backup for Virtual Machines

* Virtual machines
** Back up virtual machines from on-premises secondary storage
** Supports custom policies
** Supports Google Cloud Platform (GCP) to back up one or more datastores
** Supports low cost cloud storage like Glacier, Deep Glacier, and Azure Archive

== 6 December 2022

=== Required Connector outbound internet access endpoint changes

Because of a change in Cloud Backup, you need to change the following Connector endpoints for successful Cloud Backup operation:

[cols=2*,options="header",cols="50,50",width="80%"]
|===

| Old endpoint
| New endpoint

| \https://cloudmanager.cloud.netapp.com
| \https://api.bluexp.netapp.com
| \https://*.cloudmanager.cloud.netapp.com
| \https://*.api.bluexp.netapp.com

|===

See the full list of endpoints for your https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-aws.html#outbound-internet-access[AWS^], https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-gcp.html#outbound-internet-access[Google Cloud^], or https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html#outbound-internet-access[Azure^] cloud environment.

=== Support for selecting the Google Archival storage class in the UI

Backup files are initially created in the Google Standard storage class. Now you can use the Cloud Backup UI to tier older backups to Google Archive storage after a certain number of days for further cost optimization. 

This functionality is currently supported for on-prem ONTAP clusters using ONTAP 9.12.1 or greater. It is not currently available for Cloud Volumes ONTAP systems.

=== Support for FlexGroup volumes

Cloud Backup now supports backing up and restoring FlexGroup volumes. When using ONTAP 9.12.1 or greater, you can back up FlexGroup volumes to public and private cloud storage. If you have working environments that include FlexVol and FlexGroup volumes, once you update your ONTAP software, you can back up any of the FlexGroup volumes on those systems.

https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-ontap-backup-to-cloud.html#supported-volumes[See the full list of supported volume types].

=== Ability to restore data from backups to a specific aggregate on Cloud Volumes ONTAP systems

In earlier releases you could select the aggregate only when restoring data to on-prem ONTAP systems. This functionality now works when restoring data to Cloud Volumes ONTAP systems.

== 2 November 2022

=== Ability to export older Snapshot copies into your baseline backup files

If there are any local Snapshot copies for volumes in your working environment that match your backup schedule labels (for example, daily, weekly, etc.), you can export those historic snapshots to object storage as backup files. This enables you to initialize your backups in the cloud by moving older snapshot copies into the baseline backup copy.

This option is available when activating Cloud Backup for your working environments. You can also change this setting later in the https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backup-settings-ontap.html[Advanced Settings page].

=== Cloud Backup can now be used for archiving volumes that you no longer need on the source system

Now you can delete the backup relationship for a volume. This provides you with an archiving mechanism if you want to stop the creation of new backup files and delete the source volume, but retain all the existing backup files. This gives you the ability to restore the volume from the backup file in the future, if needed, while clearing space from your source storage system. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backups-ontap.html#deleting-volume-backup-relationships[Learn how].

=== Support has been added to receive Cloud Backup alerts in email and in the Notification Center

Cloud Backup has been integrated into the BlueXP Notification service. You can display Cloud Backup notifications by clicking the notification bell in the BlueXP menu bar. You can also configure BlueXP to send notifications by email as alerts so you can be informed of important system activity even when you're not logged into the system. The email can be sent to any recipients who need to be aware of backup and restore activity. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-monitor-backup-jobs.html#use-the-job-monitor-to-view-backup-and-restore-job-status[Learn how].

=== New Advanced Settings page enables you to change cluster-level backup settings

This new page enables you to change many cluster-level backup settings that you set when activating Cloud Backup for each ONTAP system. You can also modify some settings that are applied as "default" backup settings. The full set of backup settings that you can change includes:

* The storage keys that give your ONTAP system permission to access object storage
* The network bandwidth allocated to upload backups to object storage
* The automatic backup setting (and policy) for future volumes
* The archival storage class (AWS only)
* Whether historical Snapshot copies are included in your initial baseline backup files
* Whether "yearly" snapshots are removed from the source system
* The ONTAP IPspace that is connected to object storage (in case of incorrect selection during activation)

https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backup-settings-ontap.html[Learn more about managing cluster-level backup settings].

=== Now you can restore backup files using Search & Restore when using an on-premises Connector

In the previous release, support was added for creating backup files to the public cloud when the Connector is deployed in your premises. In this release, support has been continued to allow using Search & Restore to restore backups from Amazon S3 or Azure Blob when the Connector is deployed in your premises. Search & Restore also supports restoring backups from StorageGRID systems to on-premises ONTAP systems now.

At this time, the Connector must be deployed in the Google Cloud Platform when using Search & Restore to restore backups from Google Cloud Storage.

=== Job Monitoring page has been updated 

The following updates have been made to the https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-monitor-backup-jobs.html[Job Monitoring page]: 

* A column for "Workload" is available so you can filter the page to view jobs for the following Backup services: Volumes, Applications, Virtual Machines, and Kubernetes.
* You can add new columns for "User Name" and "Job Type" if you want to view these details for a specific backup job.
* The Job Details page displays all the sub-jobs that are running to complete the main job.
* The page automatically refreshes every 15 minutes so that you’ll always see the most recent job status results. And you can click the *Refresh* button to update the page immediately.

=== AWS cross-account backup enhancements

If you want to use a different AWS account for your Cloud Volumes ONTAP backups than you're using for the source volumes, you must add the destination AWS account credentials in BlueXP, and you must add the permissions "s3:PutBucketPolicy" and "s3:PutBucketOwnershipControls" to the IAM role that provides BlueXP with permissions. In the past you needed to configure many settings in the AWS Console - you don't need to do that anymore.

== 28 September 2022

=== Enhancements to Cloud Backup for Applications

* Supports Google Cloud Platform (GCP) and StorageGRID to back up application consistent snapshots
* Create custom policies
* Supports archival storage
* Back up SAP HANA applications
* Back up Oracle and SQL applications that are on VMware environment
* Back up applications from on-premises secondary storage
* Deactivate backups
* Unregister SnapCenter Server

=== Enhancements to Cloud Backup for Virtual Machines

* Supports StorageGRID to back up one or more datastores
* Create custom policies
// end::whats-new[]

== 19 September 2022

=== DataLock and Ransomware protection can be configured for backup files in StorageGRID systems

The last release introduced _DataLock and Ransomware Protection_ for backups stored in Amazon S3 buckets. This release expands support to backup files stored in StorageGRID systems. If your cluster is using ONTAP 9.11.1 or greater, and your StorageGRID system is running version 11.6.0.3 or greater, this new backup policy option is available. https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-cloud-backup-policies.html#datalock-and-ransomware-protection[Learn more about how you can use DataLock and Ransomware protection to protect your backups^].

Note that you'll need to be running a Connector with version 3.9.22 or greater software. The Connector must be installed in your premises, and it can be installed in a site with or without internet access.

=== Folder-level restore is now available from your backup files

Now you can restore a folder from a backup file if you need access to all the files in that folder (directory or share). Restoring a folder is much more efficient than restoring an entire volume. This functionality is available for restore operations using both the Browse & Restore method and the Search & Restore method when using ONTAP 9.11.1 or greater. At this time you can can select and restore only a single folder, and only files from that folder are restored - no sub-folders, or files in sub-folders, are restored.

=== File-level restore is now available from backups that have been moved to archival storage

In the past you could only restore volumes from backup files that had been moved to archival storage (AWS and Azure only). Now you can restore individual files from these archived backup files. This functionality is available for restore operations using both the Browse & Restore method and the Search & Restore method when using ONTAP 9.11.1 or greater.

=== File-level restore now provides the option to overwrite the original source file

In the past, a file restored to the original volume was always restored as a new file with the prefix "Restore_<file_name>". Now you can choose to overwrite the original source file when restoring the file to the original location on the volume. This functionality is available for restore operations using both the Browse & Restore method and the Search & Restore method.

=== Drag and drop to enable Cloud Backup to StorageGRID systems

If the https://docs.netapp.com/us-en/cloud-manager-storagegrid/task-discover-storagegrid.html[StorageGRID^] destination for your backups exists as a working environment on the Canvas, you can drag your on-prem ONTAP working environment onto the destination to initiate the Cloud Backup setup wizard.

== 18 August 2022

=== Support has been added to protect cloud native applications data

Cloud Backup for Applications is a SaaS based service that provides data protection capabilities for applications running on NetApp Cloud Storage. Cloud Backup for Applications enabled within BlueXP offers efficient, application consistent, policy-based backup and restore of Oracle databases residing on Amazon FSx for NetApp ONTAP.
https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-cloud-app-data-to-cloud.html[Learn more^].

=== Search & Restore is now supported with backup files in Azure Blob

The Search & Restore method of restoring volumes and files is now available for users who store their backup files in Azure Blob storage. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#prerequisites-2[See how to restore your volumes and files using Search & Restore^].

Note that additional permissions are needed in the Connector role to use this functionality. A Connector deployed using version 3.9.21 software (August 2022) includes these permissions. You'll need to manually add the permissions if you deployed the Connector using an earlier release. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-azure.html#verify-or-add-permissions-to-the-connector[See how to add these permissions, if necessary^].

=== We've added the ability to protect your backup files from deletion and ransomware attacks

Cloud Backup now has object lock support for ransomware-safe backups. If your cluster is using ONTAP 9.11.1 or greater, and your backup destination is Amazon S3, a new backup policy option called _DataLock and Ransomware Protection_ is now available. DataLock protects your backup files from being modified or deleted, and Ransomware protection scans your backup files to look for evidence of a ransomware attack on your backup files. https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-cloud-backup-policies.html#datalock-and-ransomware-protection[Learn more about how you can use DataLock and Ransomware protection to protect your backups^].

Note that additional permissions are needed in the Connector role to use this functionality. A Connector deployed using version 3.9.21 software includes these permissions. You'll need to manually add the permissions if you deployed the Connector using an earlier release. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-aws.html#set-up-s3-permissions[See how to add these permissions, if necessary^].

=== Cloud Backup now supports policies created using custom SnapMirror labels

Previously, Cloud Backup supported only pre-defined SnapMirror labels like hourly, daily, weekly, hourly, and yearly. Now Cloud Backup can discover SnapMirror policies that have custom SnapMirror labels that you created using System Manager or the CLI. These new labels are exposed in the Cloud Backup UI - allowing you to back up volumes with the SnapMirror label of your choice to the cloud.

=== Additional backup policy improvements for ONTAP systems

Some of the Backup Policy pages have been redesigned to make it easier to view all the backup policies that are available for volumes in each ONTAP cluster. This makes it easier to see the details of available policies so you can apply the best policies on your volumes.

=== Drag and drop to enable Cloud Backup to Azure Blob and Google Cloud Storage

If the https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-viewing-azure-blob.html[Azure Blob^] or https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-viewing-gcp-storage.html[Google Cloud Storage^] destination for your backups exists as a working environment on the Canvas, you can drag your on-prem ONTAP or Cloud Volumes ONTAP working environment (installed in Azure or GCP) onto the destination to initiate the Backup setup wizard.

This functionality already exists for Amazon S3 buckets.

== 13 July 2022

=== Support has been added to back up SnapLock Enterprise volumes

Now you can use Cloud Backup to back up SnapLock Enterprise volumes to public and private clouds. This feature requires that your ONTAP system is running ONTAP 9.11.1 or later. SnapLock Compliance volumes, however, aren’t currently supported.

=== Now you can create backup files in the public cloud when using an on-premises Connector

In the past you needed to deploy the Connector in the same cloud provider as where you were creating backup files. Now you can use a Connector deployed in your premises to create backup files from on-prem ONTAP systems to Amazon S3, Azure Blob, and Google Cloud Storage. (An on-prem Connector was always required when creating backup files on StorageGRID systems.)

=== Additional features are available when creating backup policies for ONTAP systems

* Backup on a yearly schedule is now available. The default retention value is 1 for yearly backups, but you can change this value if you want to have access to many previous years' backup files.
* You can name your backup policies so you can identify your policies with more descriptive text.

== 14 June 2022

=== Support has been added to back up on-premises ONTAP cluster data in sites without internet access

If your on-prem ONTAP cluster resides in a site with no internet access, also known as a dark site or offline site, now you can use Cloud Backup to back up volume data to a NetApp StorageGRID system that resides in the same site. This functionality requires that the BlueXP Connector (version 3.9.19 or greater) is also deployed in the offline site.

https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-onprem-no-internet.html[See how to install the Connector in your offline site].
https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-private-cloud.html[See how to back up ONTAP data to StorageGRID in your offline site].

=== Cloud Backup for Virtual Machines 1.1.0 is now GA

You can protect data on your virtual machines by integrating the SnapCenter Plug-in for VMware vSphere with BlueXP. You can back up datastores to the cloud and restore virtual machines back to the on-premises SnapCenter Plug-in for VMware vSphere with ease.

https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-vm-data.html[Learn more about protecting virtual machines to cloud].

=== Cloud Restore instance is not needed for ONTAP Browse & Restore functionality

A separate Cloud Restore instance/virtual machine used to be required for file-level Browse & Restore operations from S3 and Blob storage. This instance shut down when not in use -- but it still added some time and cost when restoring files. This functionality has been replaced with a no-cost container that gets deployed on the Connector when needed. It provides the following advantages:

* No added cost for file-level restore operations
* Faster file-level restore operations
* Support for Browse & Restore operations for files from the cloud when the Connector is installed on your premises

Note that the Cloud Restore instance/VM will be removed automatically if you were previously using it. A Cloud Backup process will run once a day to delete all old Cloud Restore instances. This change is completely transparent -- there is no effect on your data, and you won't notice any changes to your backup or restore jobs.

=== Browse & Restore support for files from Google Cloud and StorageGRID storage

With the addition of the container for Browse & Restore operations (as described above), file restore operations now can be performed from backup files stored in Google Cloud and StorageGRID systems. Now Browse & Restore can be used to restore files across all public cloud providers and from StorageGRID. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#restoring-ontap-data-using-browse-restore[See how to use Browse & Restore to restore volumes and files from your ONTAP backups].

=== Drag and drop to enable Cloud Backup to S3 storage

If the Amazon S3 destination for your backups exists as a working environment on the Canvas, you can drag your on-prem ONTAP cluster or Cloud Volumes ONTAP system (installed in AWS) onto the Amazon S3 working environment to initiate the setup wizard.

=== Automatically apply a backup policy to newly created volumes in Kubernetes clusters

If you added new persistent volumes to your Kubernetes clusters after Cloud Backup was activated, in the past you needed to remember to configure backups for those volumes. Now you can select a policy that will be applied automatically to newly created volumes https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backups-kubernetes.html#setting-a-backup-policy-to-be-assigned-to-new-volumes[from the _Backup Settings_ page] for clusters that have already activated Cloud Backup.

=== Cloud Backup APIs are now available for managing backup and restore operations

The APIs are available at https://docs.netapp.com/us-en/cloud-manager-automation/cbs/overview.html. See link:api-backup-restore.html[this page] for an overview of the APIs.

== 2 May 2022

=== Search & Restore is now supported with backup files in Google Cloud Storage

The Search & Restore method of restoring volumes and files was introduced in April for users who store their backup files in AWS. Now the capability is available for users who store their backup files in Google Cloud Storage. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#prerequisites-2[See how to restore your volumes and files using Search & Restore].

=== Configure a backup policy to be applied automatically to newly created volumes in Kubernetes clusters

If you added new persistent volumes to your Kubernetes clusters after Cloud Backup was activated, in the past you needed to remember to configure backups for those volumes. Now you can select a policy that will be applied automatically to newly created volumes. This option is available in the setup wizard when activating Cloud Backup for a new Kubernetes cluster.

=== Cloud Backup now requires a license before being activated on a working environment

There are a few changes to how licensing is implemented with Cloud Backup:

* You must sign up for a PAYGO Marketplace subscription from your cloud provider, or purchase a BYOL license from NetApp, before you can activate Cloud Backup.
* The 30-day Free Trial is available only when using a PAYGO subscription from your cloud provider - it is not available when using the BYOL license.
* The Free Trial starts the day the Marketplace subscription starts. For example, if you activate the Free Trial after you have been using a Marketplace subscription for 30 days for a Cloud Volumes ONTAP system, the Cloud Backup Trial will not be available.

https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-licensing-cloud-backup.html[Learn more about the available licensing models].

== 4 April 2022

=== Cloud Backup for Applications 1.1.0 (powered by SnapCenter) is now GA

The new Cloud Backup for Applications capability enables you to offload existing application consistent Snapshots (backups) for Oracle and Microsoft SQL from on-premises primary storage to cloud object storage in Amazon S3 or Azure Blob.

When required, you can restore this data from cloud to on-premises.

link:concept-protect-app-data-to-cloud.html[Learn more about protecting on-premises applications data to the cloud].

=== New Search & Restore feature to search for volumes or files across all ONTAP backup files

Now you can search for a volume or file across *all ONTAP backup files* by partial or full volume name, partial or full file name, size range, and additional search filters. This is a great new way to find the data you want to restore if you are not sure which cluster or volume was the source for the data. link:task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore[Learn how to use Search & Restore].

== 3 March 2022

=== Ability to back up persistent volumes from your GKE Kubernetes clusters to Google Cloud storage

If your GKE cluster has NetApp Astra Trident installed, and it's using Cloud Volumes ONTAP for GCP as backend storage for the cluster, then you can back up and restore your persistent volumes to and from Google Cloud storage. link:task-backup-kubernetes-to-gcp.html[Go here for details].

=== The Beta capability to use Cloud Data Sense to scan your Cloud Backup files has been discontinued in this release

== 14 February 2022

=== Now you can assign backup policies to individual volumes in a single cluster

In the past you could assign only a single backup policy to all volumes in a cluster. Now you can create multiple backup policies for a single cluster and apply different policies to different volumes. link:task-manage-backups-ontap#changing-the-policy-assigned-to-existing-volumes[See how to create new backup policies for a cluster and assign them to selected volumes].

=== A new option enables you to automatically apply a default backup policy to newly created volumes

In the past, new volumes created in a working environment after Cloud Backup was activated required that you manually apply a backup policy. Now, regardless of if the volume was created in BlueXP, System Manager, the CLI, or by using APIs, Cloud Backup will discover the volume and apply the backup policy you have chosen as the default policy.

This option is available when enabling backup in a new working environment, or from the _Manage Volumes_ page for existing working environments.

=== New Job Monitor is available to see the in-process status of all backup and restore jobs

The Job Monitor can be very helpful when you have initiated an operation against multiple volumes, like changing the backup policy, or deleting backups, so you can see when the operation has completed on all volumes. link:task-monitor-backup-jobs.html[See how to use the Job Monitor].

== 2 January 2022

=== Ability to back up persistent volumes from your AKS Kubernetes clusters to Azure Blob storage

If your AKS cluster has NetApp Astra Trident installed, and it's using Cloud Volumes ONTAP for Azure as backend storage for the cluster, then you can back up and restore volumes to and from Azure Blob storage. link:task-backup-kubernetes-to-azure.html[Go here for details].

=== Cloud Backup service charges have been changed in this release to align more closely with industry standards

Instead of paying NetApp for capacity based on the size of your backup files, now you pay only for the data that you protect, calculated by the logical used capacity (before ONTAP efficiencies) of the source ONTAP volumes which are being backed up. This capacity is also known as Front-End Terabytes (FETB).
