---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore, bluexp, bluexp backup and recovery, protection
summary: Learn what's new in BlueXP backup and recovery.
---
= What's new in BlueXP backup and recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in BlueXP backup and recovery.

// tag::whats-new[]

== 14 July 2025

This BlueXP backup and recovery release includes the following updates.

//v3.0.10
include::_whatsnew/2025-06-07.adoc[]

== 09 June 2025 
//v4.0.4
This BlueXP backup and recovery release includes the following updates.

include::_whatsnew/2025-06-09.adoc[]

== 13 May 2025
//v4.0.3
This BlueXP backup and recovery release includes the following updates.

include::_whatsnew/2025-05-12.adoc[]

== 16 April 2025
//v4.0.2
This BlueXP backup and recovery release includes the following updates. 

include::_whatsnew/2025-04-16.adoc[]

// end::whats-new[] 

== 17 March 2025 
//v4.0.1

This BlueXP backup and recovery release includes the following updates. 

include::_whatsnew/2025-03-17.adoc[]

== 21 February 2025 
//v3.0.9

This BlueXP backup and recovery release includes the following updates. 


include::_whatsnew/2025-02-18.adoc[]

== 13 February 2025

This BlueXP backup and recovery release includes the following updates.
//v3.0.9

include::_whatsnew/2025-02-05.adoc[]    



== 22 November 2024
//v3.0.8

This BlueXP backup and recovery release includes the following updates.


include::_whatsnew/2024-11-22.adoc[]


== 27 September 2024
//v3.0.7 

This BlueXP backup and recovery release includes the following updates.


include::_whatsnew/2024-09-27.adoc[]




