
//== Verify ONTAP networking requirements for replicating volumes
Before you activate backups in BlueXP backup and recovery, ensure that the source and destination systems meet ONTAP version and networking requirements. 

//This section and its subsections are an Include for Back up on-premises ONTAP to AWS, Azure, and GCP. 



==== Cloud Volumes ONTAP networking requirements

The instance's security group must include the required inbound and outbound rules: specifically, rules for ICMP and ports 11104 and 11105. These rules are included in the predefined security group.

//The following statement applies only to backup from CVO topics: 
//To replicate data between two Cloud Volumes ONTAP systems in different subnets, the subnets must be routed together (this is the default setting).

// The following statement is for different cloud providers and isn't available for July release. 
//* To replicate data between two Cloud Volumes ONTAP systems in different cloud providers, you must have a VPN connection between the virtual networks.

==== On-premises ONTAP networking requirements

* If the cluster is on your premises, you should have a connection from your corporate network to your virtual network in the cloud provider. This is typically a VPN connection.

* ONTAP clusters must meet additional subnet, port, firewall, and cluster requirements.
+
Because you can replicate to Cloud Volumes ONTAP or an on-premises systems, review peering requirements for on-premises ONTAP systems. https://docs.netapp.com/us-en/ontap-sm-classic/peering/reference_prerequisites_for_cluster_peering.html[View prerequisites for cluster peering in the ONTAP documentation^].
