
//== Prepare your on-premises ONTAP cluster
Preparing your on-premises ONTAP cluster involves the following steps: 

* Discover the ONTAP cluster in BlueXP
* Verify ONTAP requirements
* Verify cluster networking requirements

// This is an include along with the 2 subsections of "Discover your ONTAP cluster in BlueXP" and "Verify ONTAP requirements"


=== Discover your ONTAP cluster in BlueXP

You need to discover your on-premises ONTAP cluster in BlueXP before you can start backing up volume data. You'll need to know the cluster management IP address and the password for the admin user account to add the cluster.

https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html[Learn how to discover a cluster^].

=== Verify ONTAP requirements
Ensure that the following ONTAP requirements are met: 

* Minimum of ONTAP 9.7P5; ONTAP 9.8P13 and later is recommended.
* A SnapMirror license (included as part of the Premium Bundle or Data Protection Bundle).
+
*Note:* The "Hybrid Cloud Bundle" is not required when using BlueXP backup and recovery.
+
Learn how to https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html[manage your cluster licenses^].

* Time and time zone are set correctly.
+
Learn how to https://docs.netapp.com/us-en/ontap/system-admin/manage-cluster-time-concept.html[configure your cluster time^].